<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_InsuredName</name>
   <tag></tag>
   <elementGuidId>7e8b0511-0ed1-4a7b-b4a3-7a42d66a785b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@data-attribute-name=&quot;Insured name&quot;]//div//span[text() = '${insuredName}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${insuredName}' or . = '${insuredName}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.match-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Banco Bilbao Vizcaya Argentaria, S.A.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78299c2b-c1ae-4427-8919-1a83412077bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>match-highlight</value>
      <webElementGuid>6936d7b1-467b-4dd1-b80f-8217f6fcc0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${insuredName}</value>
      <webElementGuid>b0b62df9-f4cd-4b4e-9d1e-b7a677c11f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PD_InsuredListOnType_pa471830086209561pz$ppxResults$l1&quot;)/td[@class=&quot;autocompleteAGleft gridCell cellHover&quot;]/div[@class=&quot;oflowDiv&quot;]/div[@class=&quot;divCont&quot;]/div[@class=&quot;cellIn&quot;]/span[1]/span[@class=&quot;match-highlight&quot;]</value>
      <webElementGuid>82a1a793-1557-4ab6-ada1-4fe8d03140ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget0Ifr</value>
      <webElementGuid>672ad503-ce77-4b9b-be44-f11d8fdacffb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PD_InsuredListOnType_pa471830086209561pz$ppxResults$l1']/td/div/div/div/span/span</value>
      <webElementGuid>2289b475-c606-46c8-8acd-b9f13dd053bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::span[3]</value>
      <webElementGuid>1dd74de7-5665-4a76-9f35-f1e8c1d311fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BusinessUnitId'])[1]/following::span[4]</value>
      <webElementGuid>c147b8b7-747b-48a7-b927-1d748482e823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spain'])[2]/preceding::span[1]</value>
      <webElementGuid>791cfcde-aa52-4af5-9268-87e9f76d25a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P4887'])[1]/preceding::span[2]</value>
      <webElementGuid>bdc428ff-ec31-4d1a-92b5-61427f50f5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Banco Bilbao Vizcaya Argentaria, S.A.']/parent::*</value>
      <webElementGuid>35114036-1fe9-424b-af43-fa106fd1fad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>7324a255-88bc-42cf-96d3-ddf41deb7085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Banco Bilbao Vizcaya Argentaria, S.A.' or . = 'Banco Bilbao Vizcaya Argentaria, S.A.')]</value>
      <webElementGuid>cdd1eab7-676f-46c0-b3a6-3b91891b56fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
