analytics.onpremise.enable=true
onpremise.email="vkumar4@tmhcc.com"
onpremise.password="V/E8clZSspqvAT612gX93g\=\="
analytics.onpremise.organization="{\\"accountId\\"\:1342078,\\"id\\"\:1559289,\\"name\\"\:\\"Tokio Marine HCC\\",\\"role\\"\:\\"USER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false}"
analytics.onpremise.server="https\://testops.katalon.io"
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 1629374,\\n  \\"name\\"\: \\"Quality Engineering Managed Test Automation Service\\",\\n  \\"teamId\\"\: 1610424,\\n  \\"organizationId\\"\: 1559289,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 1610424\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=false
