<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompleteSuite31</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>af95aa71-03c5-4642-8bce-4693c5734339</testSuiteGuid>
   <testCaseLink>
      <guid>4eb5ff3a-9b75-41c0-95b3-67e7b740bb89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ViewMode/259890_CheckForEndorsementsTab</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a87eaceb-f3c6-4466-9086-04eb4559a773</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0795e29-56aa-4d16-9aee-b52ae6146d60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d8f8056-105d-4cb3-a757-b1db321e93bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>716ffc45-b5e5-4857-8d17-69ce0d4f7c09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71895d14-3d74-4a23-8e32-4a4907e9cbed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2729686-b7cc-4ec3-97e2-999cb62a0234</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35e4ac83-9a01-4ed2-8d4f-b0cd5b9838e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01f88469-3895-4b52-b3f7-35a244e735fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d19a1f19-8fd7-4dfe-948e-b52581c4c64c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a24d305-a75d-49b2-ab34-0153356449b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Reports_Validation/259892_ContractCertainityReports</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9753f8d-f6f5-4c7f-8764-2b4cf024b5c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d20c0e-c958-45d2-b525-eec736d971a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa39e08e-df0c-49f4-8c2e-3858c1531c72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe5874ae-a282-4c89-b430-7d28bcafeb3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SubmissionSearch/263886_ProgrammViewVerifyModlifybuttonfromProgrammeIDSearchResultsforBusinessAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba612b83-6712-4902-b000-d8a463928333</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d28c6a33-82ef-4252-a63a-3e665e31ff57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SubmissionSearch/262231_SearchPolicyReference</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9cfc5ef-ab74-47f4-84ee-8d18ea76e099</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d9da29f-80ea-4294-898d-7a28df454c61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43b80fd4-add5-4115-b674-affc9082bbaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SubmissionSearch/262230_ProgrammeViewSearchMultiLOBID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84ff34e5-d91d-4999-bab5-43756f07279c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0446761c-b1a8-406e-8833-3d392baf4751</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98000cc6-161f-48e2-ab79-914d4f3a6a0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewBusiness/262225_CreateNewBureauProportionalTreaty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c7780fb-ad57-4fae-9499-da452e327a74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1a29a00-4fa7-466c-b29a-9ff297d5cc00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a148a6ff-37bb-4942-83f5-19c974b9a3cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2593c3dd-53ea-478a-aaf2-31d244999986</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f50c3966-16f5-4169-b352-90d3bfb72c3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ff8bfb5-dde9-4e6c-b8e5-f2c5e2cbc05b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d90c5a3-b9c5-4ea9-9a96-53ee563cb258</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d69b8ca0-97fa-44ef-83da-793076247bac</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
