<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompleteSuite28</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>70bf9254-fc39-425d-87c6-2552f4fa5873</testSuiteGuid>
   <testCaseLink>
      <guid>1647d781-32ee-4749-80ba-30f1c744ef2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quote/262190_DeclineSubmissionCyber</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75190951-3daf-4373-8259-2b85d086ffe0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43d455e6-fefe-4134-a00d-713adb4e7245</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a29a7fa-8d78-4c7c-bf65-9a1d7867ee95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>399cabd5-b8a4-4a73-b2b0-fcbcb5f73f81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SubmissionSearch/263883_VerifyProgrammeIDSearchForInsuredViaUtilitiesForBusinessAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc2c11a7-7771-4ce0-b135-508dc45f70a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7198afc-c0da-4d54-b980-82d42852a774</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcc41280-4fb5-45cf-bc88-abd44d35d4b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Documentation/260058_CheckforBrokerBinderTemplatesWORDOrPDF</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>260468a1-dbc0-419a-a500-fe014a4fd809</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ca779ca-9a06-451f-8ed8-42d9500311d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e90954d6-d405-462a-bd9f-a5e27055fdab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52071ad1-7aa5-460a-9900-4eebba47cd14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Documentation/259731_CheckDocumentationMaintenanceActivity</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e20880d2-e253-4894-82eb-71e69e8a48ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>396e991c-b217-4480-9098-9f6a6b12ee11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e5f513d-471b-421d-8bc8-e0b1b1e2d90c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1179cea7-7c83-4cf2-b6bb-7aeef7038ee1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f2a80d6-9580-4f5d-be1a-36834d46e29d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
