<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CompleteSuite30</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f738cfb8-77d7-43e4-9dee-404cb4c889f2</testSuiteGuid>
   <testCaseLink>
      <guid>d7f319e8-a4e9-4271-adbe-1f613f313c43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Endorsements/262204_CreateEndorsementCancellationFromInceptionDO</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14b3e3c8-5496-427c-ab36-ecafb3112bf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97441adc-adc6-4313-9ffa-ca2ad9850279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecf74d01-437a-47c5-9a48-19a6c015dfe6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ed7816e-ca2b-48e7-a2b6-2680c2f2b181</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ViewMode/259889_ViewPolicyOnClickOnInsuredLinkFromSubmissionSearch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a87eaceb-f3c6-4466-9086-04eb4559a773</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ff73233-41e0-4af8-9745-273f93322114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25c3d28f-98fa-492d-90a1-7e90e730f3f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e9abc6c-95c2-40fd-9ef3-ef5d8bbc14d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SubmissionSearch/262228_SearchPolicyInsuredNameAndStatus</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10e2384f-e697-4053-953b-6e456d628b0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf23a562-5b66-4ca2-b463-f28555cb23a2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
