<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SmokeTest03</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1d097969-51eb-4300-b2d0-9b205238de53</testSuiteGuid>
   <testCaseLink>
      <guid>fbe08d3f-2f25-470f-a996-418a91f21d1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SmokeModifications/262201_CreateNewBureauBordereauFacilityMajorClassAsBLDEntityAsLloyds</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a831cc7f-897f-4fed-89f4-276d0ef3ec3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdb6bb56-d5cb-4bca-b301-8546d6a1fc1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffd44759-fdc5-413e-9f57-d54269e44d81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SmokeModifications/259889_ViewPolicyOnClickOnInsuredLinkFromSubmissionSearch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6ee0285-20e4-4996-8504-dfd4dc18febf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dd04684-662d-468d-b8db-9d712f489ada</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00651013-f180-4989-a5d0-485667d3f395</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
