<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_AddItem</name>
   <tag></tag>
   <elementGuidId>a630c971-9782-4cec-9fda-0a9d0907f8f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Add item')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.PolicyData_4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02109021712140578934&quot;] [data-test-id=&quot;\32 015071603054009744126&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bcece308-c6e4-4284-9cca-e2b19340edd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2015071603054009744126</value>
      <webElementGuid>013cc284-19e7-4c0a-9cc4-ba21fcb19647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>409a1401-0b87-4d76-bb7d-bd520e4393c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>f7523f84-c4d3-4607-9042-7f0fe8de0342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>d2daae47-ad71-4d30-a3ad-726090c5f675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.PolicyData_4</value>
      <webElementGuid>890f4464-44ac-40ad-89b7-6ad75f8a5bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;doListAction&quot;,[&quot;:event&quot;,[&quot;ADDITEM&quot;,&quot;&quot;, &quot;INSERTAFTER&quot;,&quot;&quot;,&quot;pyNextGenGridModalTemplate&quot;],[&quot;INSERTAFTER&quot;]]]]</value>
      <webElementGuid>db438243-3ff5-4948-b03e-2a459c9cea3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add item</value>
      <webElementGuid>5345c125-eae3-4233-bc1d-660b61351345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID2&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataLabelWrite gridActionAlignLeft&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex  content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-1   flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex  content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-2   dataValueWrite flex flex-row&quot;]/span[1]/a[1]</value>
      <webElementGuid>fdca33b4-91ad-4802-ae02-16d7a9c2f2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>6216fd13-dc06-41d9-8a82-3904405da8ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.PolicyData_4']</value>
      <webElementGuid>6526b74a-230b-4b27-87bc-d3266f1821d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/div/div/div[2]/span/a)[5]</value>
      <webElementGuid>208e389e-8c92-43e5-8227-ad6290576892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add item')])[3]</value>
      <webElementGuid>30582485-ac76-4d29-a474-6094ba0f2706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items'])[3]/following::a[1]</value>
      <webElementGuid>3bd55a7d-3cf5-4d9e-8b3a-56912d639a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[4]/following::a[1]</value>
      <webElementGuid>56bbb44d-a161-451d-9690-6405924645f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::a[2]</value>
      <webElementGuid>3bd17503-f7f1-452d-af34-4938a0f5d6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::a[2]</value>
      <webElementGuid>74429b9a-a7c4-43d5-9e12-d49de23e71d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>45b53df9-2a16-4e46-afc5-9b7a9e4a846b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div[3]/table/tbody/tr/td/div/div/div/div/div/div/div/div/div[2]/span/a</value>
      <webElementGuid>377e9b71-8281-428e-9b1a-2bd26de6fca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.PolicyData_4' and (text() = 'Add item' or . = 'Add item')]</value>
      <webElementGuid>4b696c09-339d-4814-8e10-6f25865b290a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
