<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>d7d3d7a4-53cf-48ec-846e-e32824cbbc93</elementGuidId>
   <selectorCollection>
      <entry>
<<<<<<< HEAD
         <key>CSS</key>
         <value>#ModalButtonSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ModalButtonSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53ad910f-038c-44f9-81be-fe93feda21af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonTdButton</value>
      <webElementGuid>aab9f51e-e2b6-4ff2-8b2d-12ec8a6699a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pega_version</name>
      <type>Main</type>
      <value>HTMLPROPERTY</value>
      <webElementGuid>2d710a8c-f2c5-46e9-9751-fa835f0a6b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ModalButtonSubmit</value>
      <webElementGuid>da241006-448a-4870-bfc7-a6117df49606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(typeof(pega) !='undefined' &amp;&amp; pega.u.d) setUserStart(); doModalAction(pega.u.d.submitModalDlgParam,event); </value>
      <webElementGuid>9d72a22d-412c-4ca4-aa22-8af8c9e91dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a342d420-36e4-4cf1-8aae-cecadb032d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Submit </value>
      <webElementGuid>1b5e389d-07c3-4986-8e90-f0ab24c5eacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalButtonSubmit&quot;)</value>
      <webElementGuid>7483ad08-173e-443f-a8a9-8916c46692e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Pega Case Manager Portal/iframe_No cases are being followed_PegaGadget0Ifr</value>
=======
         <key>XPATH</key>
         <value>//button[@id='ModalButtonSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ModalButtonSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53ad910f-038c-44f9-81be-fe93feda21af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonTdButton</value>
      <webElementGuid>aab9f51e-e2b6-4ff2-8b2d-12ec8a6699a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pega_version</name>
      <type>Main</type>
      <value>HTMLPROPERTY</value>
      <webElementGuid>2d710a8c-f2c5-46e9-9751-fa835f0a6b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ModalButtonSubmit</value>
      <webElementGuid>da241006-448a-4870-bfc7-a6117df49606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(typeof(pega) !='undefined' &amp;&amp; pega.u.d) setUserStart(); doModalAction(pega.u.d.submitModalDlgParam,event); </value>
      <webElementGuid>9d72a22d-412c-4ca4-aa22-8af8c9e91dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a342d420-36e4-4cf1-8aae-cecadb032d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Submit </value>
      <webElementGuid>1b5e389d-07c3-4986-8e90-f0ab24c5eacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalButtonSubmit&quot;)</value>
      <webElementGuid>7483ad08-173e-443f-a8a9-8916c46692e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Pega Case Manager Portal/iframe_PegaGadget0Ifr</value>
>>>>>>> branch 'FL_Staging' of https://hccins@dev.azure.com/hccins/Product%20Team%20-%20Financial%20Lines/_git/FinancialLines_Katalon_Automation
      <webElementGuid>14e5a54d-c491-49cc-af9f-7bfe377438ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ModalButtonSubmit']</value>
      <webElementGuid>de327eb8-5517-4aed-99aa-10f5ff9ba0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div/div/div/div/div/div/div/div/table/tbody/tr/td[2]/button</value>
      <webElementGuid>6e8e53df-5cbe-485f-9be6-331a28f63985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUNIT-37496'])[1]/following::button[1]</value>
      <webElementGuid>083929af-0d7b-40b3-b09e-0b7882fd7be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent Insured ID'])[1]/following::button[1]</value>
      <webElementGuid>f47959b9-b321-4648-9301-83a456647880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>496705bd-ec2c-4e47-9b53-c9d61866861d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You are about to replace an open work item which has changes that have not been saved!'])[1]/preceding::button[2]</value>
      <webElementGuid>0c5bf2cd-d1ea-4520-952b-caf8a88d496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>fbe4586b-b38e-48d6-a56e-8187aec7d92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/button</value>
      <webElementGuid>c7ed4340-c743-4599-b518-faab826786f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ModalButtonSubmit' and @type = 'button' and (text() = '  Submit ' or . = '  Submit ')]</value>
      <webElementGuid>4920c48f-2bae-45a3-a814-8dc548d5d554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
