<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkBox_IncludeVeriskEclipsesearch</name>
   <tag></tag>
   <elementGuidId>fc7dedfb-7f7b-49d7-b71c-6a1ad6ff2738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @name = '$PD_SearchSubmissionCriteria$pIsSBS' and @id = '04f3cbc7' and @ref_element = 'Object Repository/Page_Pega Case Manager Portal/iframe_QC-41722_PegaGadget0Ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#04f3cbc7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox' and contains(@name,'IsSBS')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02308220658280311967&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>463b31e7-55f4-4abc-af02-81ad4e488434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b1455ee8-9082-4a8c-a183-b9eef045d7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202308220658280311967</value>
      <webElementGuid>252c4012-5901-464f-b777-ae7e3058a90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox chkBxCtl </value>
      <webElementGuid>9e4d74e2-25cb-46b1-88ff-5a8e44d1881a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c2e04f7-b9cf-4131-acb9-24ca8f39bd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pIsSBS</value>
      <webElementGuid>d8aba802-c695-4055-a6b2-ee33d43f309b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pIsSBSError </value>
      <webElementGuid>7159c4ef-7570-4957-8b68-aa84a028b5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>04f3cbc7</value>
      <webElementGuid>e808b29f-a4f3-4677-bdde-e1d5acb8c7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>true-false</value>
      <webElementGuid>c21e405a-3ddc-4b9a-9187-04366d5f90f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Checkbox</value>
      <webElementGuid>b307318d-45af-46d5-85ae-ea52900efd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5c831559-b950-4f41-a9e1-c11c24ff2395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;04f3cbc7&quot;)</value>
      <webElementGuid>afd19ba3-b2f0-4e6d-8f63-3b41704c0c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget0Ifr</value>
      <webElementGuid>6f973241-fcca-4169-8d1c-988b5515b3e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='04f3cbc7']</value>
      <webElementGuid>4c38634f-7ee8-4392-8bd5-9b5625152ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/div[6]/div/div/input[2]</value>
      <webElementGuid>097d9341-8997-4969-96da-b0efd02d4c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input[2]</value>
      <webElementGuid>5b58d0fd-cc15-4d5e-ac61-d5f3e4994104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = '$PD_SearchSubmissionCriteria$pIsSBS' and @id = '04f3cbc7']</value>
      <webElementGuid>2ed3db2f-ad0c-4002-bf73-3fa5c603b10b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
