<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BrokerAgencyName</name>
   <tag></tag>
   <elementGuidId>faf83025-b369-40dc-826d-e72e701f8347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#691c73f0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains( @name,'AgencyName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02112070539230505640&quot;] [data-test-id=&quot;\32 01612081057060185133984&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>076c9d53-8733-4cc7-9547-35cdb5e78854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d50becd-5669-4aec-a370-e9606a4d8411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5e17f80-4b90-40b1-baaa-44dbc93b3697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a4572b6-ed36-4608-a92f-984a190e5c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>63125f4b-fa14-48ad-9b14-b2e4578764fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change-lazy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71436378-3df4-4c2d-a600-814e36e22c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ResetBrokerOrCoverHolder,Name=#~D_SearchSubmissionCriteria.AgencyName~#&amp;City=#~D_SearchSubmissionCriteria.SearchStringFirstName~#&amp;CountryCode=#~D_SearchSubmissionCriteria.SearchStringSSN~#&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH03MzA2OTMxYTEyYjcwMjMyNzE2MTg4NDUwMmIzN2Q0YWQ3Y2UwOGE3MGU3NGE5OWY2ZTFjNWE2ZWRjNTdlMjgyYWU4YzM2ZDgzZGUwMTI4YWQ4NjcyZWUxYmM0YjA5YmRmOTZjYjhjNWYxNjE2NDViOWNiY2ZlYWRkYjE5MzIxNTdlNWUwODcxYmY1MmQyNTM3NDQ3MWQxZWU0NWQ0OWQxOGU5ZWFhMjBkZjJkOTI3NDgwNzM4OWMwNjg0YzJiZmY0N2QwYzE4ZDVmYTNlZWVjNmIyNDEzMmJlMGEzZDA1NGYyZmM0ZmViOThjOWQyNzZlYWRlY2RiODdhODY4OTZmYTVmZWZlZjRhOGIyNTk5YTA0MzgyMWZjNzA0MjFkMDY4NjEyNjJlMzU4ZWQ0YWE0NjU1ZDc4ZDAzZGU4OWQwY2VjMWMzNTNjNzQwYTNjMTBjZjc3NmU2YWNiNTY2Y2ZlMTBmZTZmNzY1N2JjNjQxNGU0NTczYWJhMDZjYjgyZWM4M2NiYzAxNTgwYTM3ZGRkOWZhNGJmOTkyMzIxNTQwMTFkNDcyZjkzMDk2MjY4ODU5M2MzZTA0MDhiOTI2YzhmNTVmMjZmY2MzMWFjZDJiMzQ2Yzg2OGIyNzQxNmRmYThlOGVkZjVhMzVmZWIyZWQ4MWE4YmNjZWFiZmViNWJmNWMzMjZmODkyOTM5NjgzOGQ0ZTAzM2Q1ZGQ3MTFhZGIwZDZkYWE3NDQ3MTZmNjViZWQ3YTNhYmM2ODNiNDRlMDgzOGE0ZWQ2MDJkMDBlOGMxZDdlYjg0MDMwNGMxZjZlNw%3D%3D*&quot;,{},{&quot;entity&quot;:&quot;&quot;,&quot;CalledFromBroker&quot;:&quot;true&quot;,&quot;CalledFromCoverholder&quot;:&quot;&quot;,&quot;AvailableInList&quot;:&quot;&quot;}],&quot;D_SearchSubmissionCriteria&quot;]]]</value>
      <webElementGuid>0ae02b49-6038-4cbe-9676-a64324ee8394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201612081057060185133984</value>
      <webElementGuid>410573ab-226d-44ca-aafe-34d253585840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;AutoCompleteAG&quot;]</value>
      <webElementGuid>6e7d917c-4143-4a8c-a8f1-8c4e29287f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e7a7c837-d5d5-414a-b71f-2715f55300e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>691c73f0</value>
      <webElementGuid>139f4651-feda-4fed-a992-7ad5ed47bc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete_input ac_</value>
      <webElementGuid>19578971-9313-418d-acfc-8b107ec575e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-displayfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>585c34f2-8545-455b-a5ca-280cf4cd6018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attributes</name>
      <type>Main</type>
      <value>[&quot;EXPANDEDSubSectionSearchSubmissionCriteria19_AgencyName&quot;,3,170,{&quot;Name&quot; : &quot;.AgencyName&quot;,&quot;City&quot; : &quot;.SearchStringFirstName&quot;,&quot;CountryCode&quot; : &quot;.SearchStringSSN&quot;,&quot;entity&quot; : &quot;Literal_&quot;,&quot;PseudoName&quot; : &quot;Literal_&quot;,&quot;PseudoCode&quot; : &quot;Literal_&quot;,&quot;allResults&quot; : &quot;Literal_true&quot;},&quot;D_SearchSubmissionCriteria&quot;,0,false]</value>
      <webElementGuid>c6b93fb1-6e95-447d-8ef1-ab23133f35d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pAgencyName</value>
      <webElementGuid>ae08cb14-8bf7-4196-a02d-a076b9096e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pAgencyNameError</value>
      <webElementGuid>c609ba5d-16f1-4d79-a8d7-a2d4f121ac69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-ac</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>a0dcca38-0c3d-4b05-b8bc-215c3474469d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;691c73f0&quot;)</value>
      <webElementGuid>3ddaff9e-2475-44bc-b7d7-4b3c6d8f41ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget0Ifr</value>
      <webElementGuid>083f26d6-e512-4705-b81f-c6ea347105b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='691c73f0']</value>
      <webElementGuid>e45fb32a-dd91-4f2f-92aa-d36c4cd92fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/div[3]/div/div/input</value>
      <webElementGuid>4937a398-6f42-40a5-b427-f7c00ddd1e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/input</value>
      <webElementGuid>95f4719f-bf00-47dc-bf04-8319c9426eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '691c73f0' and @name = '$PD_SearchSubmissionCriteria$pAgencyName']</value>
      <webElementGuid>d012712e-aeca-4004-8242-a69a8d35b1b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
