<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Insuredname1</name>
   <tag></tag>
   <elementGuidId>af76abcd-0c25-420c-8454-05d97c098c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ec6fef95</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'BusinessUnitName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Insured name&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>216751ae-8357-4895-877a-d25b1c0b02bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddb3e1df-5ece-4676-9106-b3ffe5cfb2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bac10f3e-4b63-45da-9941-d59fee30ce4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>50a67e14-0f0d-4270-87ff-0b8cc9d2fd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>acd0a616-0ea6-442e-87be-7bc595524a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change-lazy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57944719-df2b-480e-9f46-4a596539146f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ResetInsuredDetails,Name=#~D_SearchSubmissionCriteria.BusinessUnitName~#&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH03MzA2OTMxYTEyYjcwMjMyNzE2MTg4NDUwMmIzN2Q0YWQ3Y2UwOGE3MGU3NGE5OWY2ZTFjNWE2ZWRjNTdlMjgyYWU4YzM2ZDgzZGUwMTI4YWQ4NjcyZWUxYmM0YjA5YmRmOTZjYjhjNWYxNjE2NDViOWNiY2ZlYWRkYjE5MzIxNTdlNWUwODcxYmY1MmQyNTM3NDQ3MWQxZWU0NWQ0OWQxOGU5ZWFhMjBkZjJkOTI3NDgwNzM4OWMwNjg0YzJiZmY0N2QwYzE4ZDVmYTNlZWVjNmIyNDEzMmJlMGEzZDA1NDhkOGEwZWMzMTVlZjJiMjNmZDE5MGUzMzNkZDMyNzkxZThjNDNkYjBhMjgzZmI3ZGE4NjIwMDRhOGFhZTk1ODhiMDliYTJlZjAxZmFkZGEwYTdkYzcwZGNkYTFiNzliYzNlYjI3NGY5YThkYTcxMmRlOWI4NzNlY2M0YjgwNzBkNjVlNjZjY2RlZTYzMWUxZWQ1ODgxY2QwODg4YWE3YmJmYzA4ZDlhMGUxODhlODVlMWVlNWM5NDlkMzFkZDAxNGY3OTc0NjA2OTAxMDE3Y2U0OGQxNDY3ZTc0YzE0NmYyMjJhNjYwZTYwMTYxMmI4ZDI2YzIxZTY0OGFhNzhiYjRlMmM2NDljNjdiOGE5N2Q4OTQ0YzIzZjNjMzdjODM4NDM0OWFlOTQ2YzJhNjQzMjliMjgzMWRiMmY2YjhlNmVhYTNkNTBmMjE5ZWFhMDk2MDc1YTM1NWU3N2JjZmRiMzgwMTE3OGM0ZjJhMmRkMDA3ZjYzOWY2NTY3Y2QwMzgxOQ%3D%3D*&quot;,{},{&quot;CalledFromInsured&quot;:&quot;true&quot;,&quot;CalledFromParent&quot;:&quot;&quot;,&quot;CalledFromActual&quot;:&quot;&quot;,&quot;CalledFromTarget&quot;:&quot;&quot;}],&quot;D_SearchSubmissionCriteria&quot;]]]</value>
      <webElementGuid>52c735c1-163e-4895-967c-69d0f200a87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2020091609050105532185</value>
      <webElementGuid>9b8eaae4-3f65-4506-b7a1-c98ea199050b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;AutoCompleteAG&quot;]</value>
      <webElementGuid>a63011a8-f1a8-4838-a828-782e16626140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f9ce5b0-2a3a-457e-afbe-70cbb993a783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ec6fef95</value>
      <webElementGuid>94f3a2fd-4c6f-4396-9d14-6d0756c914cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expr-id</name>
      <type>Main</type>
      <value>c29451e27ff46cc942ba71843ca5cb7673b69a79_16</value>
      <webElementGuid>3f0a6ebc-8bc8-43f8-96f0-08f0aa8f82c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-context</name>
      <type>Main</type>
      <value>D_SearchSubmissionCriteria</value>
      <webElementGuid>fda8b8ef-8785-45bb-8f84-571f2f6216f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete_input ac_</value>
      <webElementGuid>e89805db-b393-4709-9b97-cc19498ac7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-displayfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c23a4b0-f00b-4bcf-acbe-14be1055d57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attributes</name>
      <type>Main</type>
      <value>[&quot;EXPANDEDSubSectionSearchSubmissionCriteria2_BusinessUnitName&quot;,3,170,{&quot;BusinessUnitID&quot; : &quot;Literal_&quot;,&quot;BusinessUnitName&quot; : &quot;.BusinessUnitName&quot;,&quot;ActualInsuredName&quot; : &quot;Literal_&quot;,&quot;TargetName&quot; : &quot;Literal_&quot;,&quot;ParentPartyName&quot; : &quot;Literal_&quot;},&quot;D_SearchSubmissionCriteria&quot;,0,false]</value>
      <webElementGuid>ff375e0f-af74-4c6a-8c68-0c234aade4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pBusinessUnitName</value>
      <webElementGuid>5283eebc-b871-4b17-9c9f-c6a990fb755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pBusinessUnitNameError</value>
      <webElementGuid>4f393430-9773-4f4f-a089-6e867faa998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-ac</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>9b7ff3d0-582e-4e0e-bd2c-abb14cd80808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6955582-a66c-474c-8dc6-4af9790deb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec6fef95&quot;)</value>
      <webElementGuid>d325f724-dbe3-4e47-af59-0db9e6148126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>8603ea74-5272-4c15-80f7-3bdb20291dc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ec6fef95']</value>
      <webElementGuid>fb0d2cf7-1c5b-4a51-b249-ac2055378dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>0121e900-c52c-4e0f-bd04-d94ff9a6410a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4ee45bdb-4e65-4942-b624-32a77d6f36f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ec6fef95' and @name = '$PD_SearchSubmissionCriteria$pBusinessUnitName']</value>
      <webElementGuid>2b734c7a-b5ae-461d-9259-8c3e13c2a682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
