<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Insuredname</name>
   <tag></tag>
   <elementGuidId>c75b0391-a95e-411f-a945-03f91abd88e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ec6fef95</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'BusinessUnitName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Insured name&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16826370-782b-43bd-a8dc-5d2619d8b1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81da9599-27d4-46d8-8e23-b53ad5608d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>869b25f5-78ed-413d-8356-e53e6253a449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>819e89a7-38d9-4cea-b7cf-feb22887927b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2aea2796-156f-4879-9897-d6e3806f0078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change-lazy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>373eb736-d8e9-433e-8fed-31bbae8dee03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ResetInsuredDetails,Name=#~D_SearchSubmissionCriteria.BusinessUnitName~#&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH03MzA2OTMxYTEyYjcwMjMyNzE2MTg4NDUwMmIzN2Q0YWQ3Y2UwOGE3MGU3NGE5OWY2ZTFjNWE2ZWRjNTdlMjgyYWU4YzM2ZDgzZGUwMTI4YWQ4NjcyZWUxYmM0YjA5YmRmOTZjYjhjNWYxNjE2NDViOWNiY2ZlYWRkYjE5MzIxNTdlNWUwODcxYmY1MmQyNTM3NDQ3MWQxZWU0NWQ0OWQxOGU5ZWFhMjBkZjJkOTI3NDgwNzM4OWMwNjg0YzJiZmY0N2QwYzE4ZDVmYTNlZWVjNmIyNDEzMmJlMGEzZDA1NDhkOGEwZWMzMTVlZjJiMjNmZDE5MGUzMzNkZDMyNzkxZThjNDNkYjBhMjgzZmI3ZGE4NjIwMDRhOGFhZTk1ODhiMDliYTJlZjAxZmFkZGEwYTdkYzcwZGNkYTFiNzliYzNlYjI3NGY5YThkYTcxMmRlOWI4NzNlY2M0YjgwNzBkNjVlNjZjY2RlZTYzMWUxZWQ1ODgxY2QwODg4YWE3YmJmYzA4ZDlhMGUxODhlODVlMWVlNWM5NDlkMzFkZDAxNGY3OTc0NjA2OTAxMDE3Y2U0OGQxNDY3ZTc0YzE0NmYyMjJhNjYwZTYwMTYxMmI4ZDI2YzIxZTY0OGFhNzhiYjRlMmM2NDljNjdiOGE5N2Q4OTQ0YzIzZjNjMzdjODM4NDM0OWFlOTQ2YzJhNjQzMjliMjgzMWRiMmY2YjhlNmVhYTNkNTBmMjE5ZWFhMDk2MDc1YTM1NWU3N2JjZmRiMzgwMTE3OGM0ZjJhMmRkMDA3ZjYzOWY2NTY3Y2QwMzgxOQ%3D%3D*&quot;,{},{&quot;CalledFromInsured&quot;:&quot;true&quot;,&quot;CalledFromParent&quot;:&quot;&quot;,&quot;CalledFromActual&quot;:&quot;&quot;,&quot;CalledFromTarget&quot;:&quot;&quot;}],&quot;D_SearchSubmissionCriteria&quot;]]]</value>
      <webElementGuid>44d4db0e-fb4b-4a37-9dd8-d298b8c54d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2020091609050105532185</value>
      <webElementGuid>a672e3bb-26e4-418b-a837-e342cfb2cd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;AutoCompleteAG&quot;]</value>
      <webElementGuid>415e5723-c54d-4ea7-8b59-4ddbd762ff3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1f0d9042-8e64-4154-b537-7821957e76da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ec6fef95</value>
      <webElementGuid>7b6f817b-0905-486b-ac67-c74303410682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expr-id</name>
      <type>Main</type>
      <value>c29451e27ff46cc942ba71843ca5cb7673b69a79_16</value>
      <webElementGuid>9274ee4c-51ae-4f4f-ae05-d75f106efcc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-context</name>
      <type>Main</type>
      <value>D_SearchSubmissionCriteria</value>
      <webElementGuid>d8174525-a827-48e6-9340-ff48feaa2f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete_input ac_</value>
      <webElementGuid>0d7dcae7-47b7-4ff9-a39a-779129f636a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-displayfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc94a09a-37b5-4446-8844-9607bd6c826c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attributes</name>
      <type>Main</type>
      <value>[&quot;EXPANDEDSubSectionSearchSubmissionCriteria2_BusinessUnitName&quot;,3,170,{&quot;BusinessUnitID&quot; : &quot;Literal_&quot;,&quot;BusinessUnitName&quot; : &quot;.BusinessUnitName&quot;,&quot;ActualInsuredName&quot; : &quot;Literal_&quot;,&quot;TargetName&quot; : &quot;Literal_&quot;,&quot;ParentPartyName&quot; : &quot;Literal_&quot;},&quot;D_SearchSubmissionCriteria&quot;,0,false]</value>
      <webElementGuid>8334c986-1850-4ffa-be73-507276cccf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pBusinessUnitName</value>
      <webElementGuid>1d93ef14-d12c-4b23-8752-92171c7fa668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pBusinessUnitNameError</value>
      <webElementGuid>5db75d5c-8b70-4246-9d10-b4faa762701f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-ac</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>93e5ab80-4094-4a5a-a95e-f8669c0f8014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>156d0477-b3ef-4b18-ba0e-1d64a1015ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec6fef95&quot;)</value>
      <webElementGuid>04a74bff-cdb0-44d5-a815-c046d519d1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget0Ifr</value>
      <webElementGuid>cdec4eeb-7605-48f2-85e8-f62b43869b02</webElementGuid>
   </webElementProperties>
</WebElementEntity>
