<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BrokerCity</name>
   <tag></tag>
   <elementGuidId>0bf93809-9dca-49fe-b765-c5bc29344aa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#360a144c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name ,'SearchStringFirstName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0170118071945054217322&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cbe5acb-9ffe-48df-aa5a-7a0f0250556f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170118071945054217322</value>
      <webElementGuid>0715e91f-81f8-49a7-a3df-1cab4c0aa1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>e8ce362e-a0d6-48f6-a8e9-a9a9f4b4a7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3e262f3-efdd-408e-be83-48d4129368c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>360a144c</value>
      <webElementGuid>4e690ddf-a618-4c38-82fd-1f318e9cf2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>5ccd27f7-4664-4e1a-8050-ea26e89be82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pSearchStringFirstName</value>
      <webElementGuid>8607e1f0-bf93-4222-a7bf-cc9202008cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a Value</value>
      <webElementGuid>d85e6466-c573-490d-a3a2-08a098b2c52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PD_SearchSubmissionCriteria$pSearchStringFirstNameError</value>
      <webElementGuid>36364d1d-152f-4ef4-ad08-35c758279ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c66e46e7-c62f-46df-9a0a-aa07a274a0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e60dacd-6e87-47db-bc80-856dab18e80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;360a144c&quot;)</value>
      <webElementGuid>a0be1e1a-64d3-49e2-aee5-ef37209b0cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget0Ifr</value>
      <webElementGuid>893dd566-6f8d-49e5-9f30-e73d3074ca90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='360a144c']</value>
      <webElementGuid>3489d755-2ebf-46a8-b123-03e08965a015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>49cb1e4e-9d78-4539-9ec6-aba2e9b4116d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>c48449a6-e0f5-4720-983f-4772efcd8328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '360a144c' and @name = '$PD_SearchSubmissionCriteria$pSearchStringFirstName' and @placeholder = 'Enter a Value']</value>
      <webElementGuid>2c3b9cf0-6ab1-440e-9518-b02f808a15fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
