<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_MajorClassMagnifier</name>
   <tag></tag>
   <elementGuidId>01cfb84d-db0d-4fe4-888a-0cfbb0c2abb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;SearchMajorClass_D_SearchSubmissionCriteria_2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Click here to select Major Class']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0210802121239073466&quot;] [data-test-id=&quot;\32 0181026091045079725621&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f13e9035-306d-4c01-8715-2badf1530fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;processAction&quot;, [&quot;MajorClassMultiSelect&quot;,&quot;true&quot;,&quot;:event&quot;,&quot;pyDisplayHarness&quot;,&quot;Rule-HTML-Section&quot;,&quot;&quot;,&quot;MultiSelectModalTemplate&quot;,&quot;%7B%22mobile%22%3A%7B%22reveal%22%3A%7B%22effect%22%3A%22anim-null%22%7D%2C%22isCustomDismiss%22%3A%22true%22%2C%22dismiss%22%3A%7B%22effect%22%3A%22anim-null%22%7D%7D%7D&quot;,&quot;true&quot;,&quot;HCC-CL-LL-Work&quot;,&quot;HCC-CL-LL-Work&quot;,&quot;false&quot;,&quot;false&quot;,&quot;&quot;,&quot;&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CopyMajorClassValues,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH00ZGUzMTg1ZjNlYTQyOWYzNjkwZDMxZjYyZjkzYmFhMzgwZmYyMDE0MDcwZWZhMWU2YzJjZTc5MzU0MTdlZjNkMzJjNmU5OWZiMWIzMzJlNjZlYTQyODdjOWMxMjM3MzNhZGM2ZjNlYzE2ZTQ2YzE1NDFkNTJkOWNjMTE0NzdhYzc5ZTBhMjk5ODk2MWRmYzBiYTY0YmQ1YWQzZjZmZmFlODY4ZmE2NWRjNjY1ZWZhZGE2MjhlMGUwYTg4ZDUxNzQxN2QyOTQ5Mjc3NDY0ZTliOWY2NjI5ZTQxYjk0YjhkZDU4YzIwNDA4MjlkNDc5ZjBhY2I5NDg2ODg3MDM0NTQ5*&quot;,{},{}],&quot;D_SearchSubmissionCriteria&quot;]]]</value>
      <webElementGuid>8220f6bd-f961-4fe3-a8a5-eb116fed455c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20181026091045079725621</value>
      <webElementGuid>4a1ce1d2-a216-4c74-91b4-0b89e6eb9be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Icon</value>
      <webElementGuid>994410bb-5caa-4286-b354-287f3427c43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>webwb/rfsearch_on_metal_13030817380.gif!!.gif</value>
      <webElementGuid>fd9f2fcd-f80f-4500-ad0c-f6c589f949a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click here to select Major Class</value>
      <webElementGuid>7e93570f-3ee6-4b24-aeb3-2ff264d7c3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Click here to select Major Class</value>
      <webElementGuid>c761c3b6-46b8-4ed3-805d-418a4c28f885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchMajorClass_D_SearchSubmissionCriteria_2</value>
      <webElementGuid>e1f655c1-45ed-4b05-ab34-66185b41f572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>290ac7a5-bfae-4a48-acdb-b7af108722f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>09843b08-a752-4e83-8ab6-89c8f8f832ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click here to select Major Class</value>
      <webElementGuid>ae6a38e5-a065-41f5-8352-b4e8bd183ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harness-container&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;harnessBodyNoHead&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_grid_quaddouble_fixed_width  content-inline_grid_quaddouble_fixed_width&quot;]/div[@class=&quot;content-item content-sub_section item-6&quot;]/div[@class=&quot;content-inner&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/i[@class=&quot;icons&quot;]/img[1]</value>
      <webElementGuid>56153e1e-14e3-4c10-adb3-77a394c6a2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget0Ifr</value>
      <webElementGuid>a32d87d2-66f4-43dc-a25e-3e5c73343d1c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
