<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_StatusMaginifier</name>
   <tag></tag>
   <elementGuidId>610a5e06-4f89-47bc-a541-ab90cea46255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;SearchStatus_D_SearchSubmissionCriteria_2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Click here to select Status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02108021210340853912&quot;] [data-test-id=&quot;\32 0181026091045079725621&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb6f3e8b-b251-4525-9744-734f6882e6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;processAction&quot;, [&quot;StatusMultiSelect&quot;,&quot;true&quot;,&quot;:event&quot;,&quot;pyDisplayHarness&quot;,&quot;Rule-HTML-Section&quot;,&quot;&quot;,&quot;MultiSelectModalTemplate&quot;,&quot;%7B%22mobile%22%3A%7B%22reveal%22%3A%7B%22effect%22%3A%22anim-null%22%7D%2C%22isCustomDismiss%22%3A%22true%22%2C%22dismiss%22%3A%7B%22effect%22%3A%22anim-null%22%7D%7D%7D&quot;,&quot;true&quot;,&quot;HCC-CL-LL-Work&quot;,&quot;HCC-CL-LL-Work&quot;,&quot;false&quot;,&quot;false&quot;,&quot;&quot;,&quot;&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CopyStatus,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH00ZGUzMTg1ZjNlYTQyOWYzNjkwZDMxZjYyZjkzYmFhMzgwZmYyMDE0MDcwZWZhMWU2YzJjZTc5MzU0MTdlZjNkMzJjNmU5OWZiMWIzMzJlNjZlYTQyODdjOWMxMjM3MzNhZGM2ZjNlYzE2ZTQ2YzE1NDFkNTJkOWNjMTE0NzdhY2ViOWUwNTAzOTJiNmJiZWNjMGJjYTg4OWQ2NjlkNDAzYmU4ZTIxMDI3ZGE0ZmNhMzQ0OTIxZGEzN2E4YTA5MGFhMGQ1OWExZjY0NmVkMzkyNGMzY2ViYzIzYjA5ZWZkNQ%3D%3D*&quot;,{},{}],&quot;D_SearchSubmissionCriteria&quot;]]]</value>
      <webElementGuid>3ee643fc-329b-47eb-bbb4-c02cdc59f4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20181026091045079725621</value>
      <webElementGuid>8e629283-5c04-4232-b595-af8f448f9832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Icon</value>
      <webElementGuid>db4d7d4c-a62e-4a4a-93a3-c7a6fba8cc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>webwb/rfsearch_on_metal_13030817380.gif!!.gif</value>
      <webElementGuid>cdb3b1fe-e537-4b94-a2a8-873955be997e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click here to select Status</value>
      <webElementGuid>b8c358c6-8ed6-42e2-9865-91b83fb14450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Click here to select Status</value>
      <webElementGuid>6486ec55-edec-408f-9184-ae50653a5e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchStatus_D_SearchSubmissionCriteria_2</value>
      <webElementGuid>e9440176-a287-49d3-bf30-48821a5fc0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5eb8f1fd-14a5-469a-b287-b6b6e3991b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>df140bd4-0c9d-4f40-b288-b77c65c38d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click here to select Status</value>
      <webElementGuid>9ae20e81-1356-4b67-8e93-47b78b9de240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harness-container&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;harnessBodyNoHead&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_grid_quaddouble_fixed_width  content-inline_grid_quaddouble_fixed_width&quot;]/div[@class=&quot;content-item content-sub_section item-5&quot;]/div[@class=&quot;content-inner&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/i[@class=&quot;icons&quot;]/img[1]</value>
      <webElementGuid>9c3fb092-50e5-4fe0-9ac8-600e2ae09554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget0Ifr</value>
      <webElementGuid>8326b2c9-a01c-4103-afae-62dda4cb8067</webElementGuid>
   </webElementProperties>
</WebElementEntity>
