<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Create</name>
   <tag></tag>
   <elementGuidId>69e8ae44-c61e-4711-bdb3-4f1927a6bfdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Create')] | //a[contains(@title,'Create New Submission')]/following |  //span[contains(text(),'Create New Submission')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pyPortalHeader_pyDisplayHarness_27&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 014100609491604293426&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cfdc0848-bcf7-483c-a059-8501d8382e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2014100609491604293426</value>
      <webElementGuid>9f2d638f-ab50-4a66-928b-d5490b605995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;showMenu&quot;,[{&quot;dataSource&quot;:&quot;pzStartProcessMenu&quot;, &quot;isNavNLDeferLoaded&quot;:&quot;false&quot;, &quot;isNavTypeCustom&quot;:&quot;false&quot;, &quot;className&quot;:&quot;Data-Portal&quot;,&quot;UITemplatingStatus&quot;:&quot;Y&quot;,&quot;menuAlign&quot;:&quot;left&quot;,&quot;format&quot;:&quot;menu-format-header-menu&quot; , &quot;loadBehavior&quot;:&quot;&quot;, &quot;ellipsisAfter&quot;:&quot;999&quot;,&quot;usingPage&quot;:&quot;pyDisplayHarness&quot;, &quot;useNewMenu&quot;:&quot;true&quot;, &quot;isMobile&quot;:&quot;false&quot;, &quot;navPageName&quot;:&quot;pyNavigation1737963570686&quot;},&quot;:event&quot;]]]</value>
      <webElementGuid>7e78d54c-ef86-4d81-9ac9-bfec603e95a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>9a5a3697-4a7f-4cb0-a95d-c71a3a12e5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eac1db74-d3f2-4f16-8c5c-5adcf17e7c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>39906165-958f-4446-a4fc-2412638e78f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href_original</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6ebedbcc-ebf4-432f-8023-0cf3d6ab2100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>105cea1b-1878-4b1f-8c00-34f09e36ab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyPortalHeader_pyDisplayHarness_27</value>
      <webElementGuid>71d0695e-076d-45df-9e5e-0bacf7b152e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Header_nav</value>
      <webElementGuid>f6819f10-c055-4d15-ade3-e69d18d54ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>d4c5fdb1-e4c6-4d5b-8053-0672ced8bfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1&quot;)/div[@class=&quot;screen-layout-region-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-portal_header  float-left set-width-auto&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-portal_header_group_primary  content-portal_header_group_primary set-width-auto&quot;]/div[@class=&quot;content-item content-field item-3 remove-top-spacing remove-bottom-spacing create-icon&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/a[@class=&quot;Header_nav&quot;]</value>
      <webElementGuid>105bf6bd-2dcf-4962-9b25-c93235b7512f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pyPortalHeader_pyDisplayHarness_27']</value>
      <webElementGuid>388c7e87-ab8a-4209-b76c-f057ee0a3a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div[3]/div/div/span/a)[2]</value>
      <webElementGuid>71940ed1-8994-4884-ad8d-2cea8e8b0f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create')]</value>
      <webElementGuid>4d6a3445-86aa-4dc0-8564-047cd0a2d8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary for FL'])[1]/preceding::a[4]</value>
      <webElementGuid>a9f6b431-422c-4026-a453-3aa029c78062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::a[5]</value>
      <webElementGuid>3be715a8-f30d-40e7-a21b-aa0d47cd7c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>974a3439-82d0-41db-aa9f-f008711fe301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>47935ebf-9b5a-417e-b6bd-acc562aeba1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[3]/div/div/span/a</value>
      <webElementGuid>546339c9-a174-4e3c-8f49-663533f96907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pyPortalHeader_pyDisplayHarness_27' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>3c505ef2-e42a-4364-a8f4-58a40ee0f96b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
