<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LandingPage</name>
   <tag></tag>
   <elementGuidId>9bfdf51d-2e32-4a2f-991a-7ad51a30fb13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header//span/i//img[@role='button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
