<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget1Ifr</name>
   <tag></tag>
   <elementGuidId>e839337b-41fa-45de-98a5-d76b17c17d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='PegaGadget1Ifr']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'PegaGadget1Ifr' and @id = 'PegaGadget1Ifr' and @src = '/prweb/app/LiabilityLines/AQrj2LB4NQAOPtP9hXno2IIlYboujm6E8dIQk5abRysA6jNpGpr450806NH2tyh9*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=623b052b-bba2-3ac8-bea7-4f172d7b4112&amp;tabIndex=2&amp;prevContentID=88d0292e-17d9-4ddd-9c1a-7e474fd0068c&amp;prevRecordkey=Data-Portal%7CSearchSubmission%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HID2A89046096091A936B8342223F8F2A14' and @title = 'New']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PegaGadget1Ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;PegaGadget1Ifr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d470b7f8-3f67-4b30-876c-1233d80311ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
      <webElementGuid>755dec94-2a9a-462f-83d9-ed3fac0384d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *;</value>
      <webElementGuid>62ad2a66-58c4-4126-8178-7f99c9addfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
      <webElementGuid>2bee422a-6a34-493e-acf2-7cb4fe770594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f42b3e9c-0d42-4003-8ae2-86836580ef3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>458ec85b-ddbc-451d-a33c-8819310b9423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prweb/app/LiabilityLines/AQrj2LB4NQAOPtP9hXno2IIlYboujm6E8dIQk5abRysA6jNpGpr450806NH2tyh9*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=623b052b-bba2-3ac8-bea7-4f172d7b4112&amp;tabIndex=2&amp;prevContentID=88d0292e-17d9-4ddd-9c1a-7e474fd0068c&amp;prevRecordkey=Data-Portal%7CSearchSubmission%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HID2A89046096091A936B8342223F8F2A14</value>
      <webElementGuid>2589bcd7-32de-472d-977a-9e35aaf523f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>686c8a88-88e4-4682-adcd-6ac1f4f2a57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget1Ifr&quot;)</value>
      <webElementGuid>53415ea1-8324-4676-88aa-288bc3a5ab0d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
