<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BrokerAgencyName</name>
   <tag></tag>
   <elementGuidId>82e46a6c-9d69-4bc3-a031-ceb21ee40cd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4b4b3600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@name,'FLAgencyName')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01612081057060185133984&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b7b173b-84c9-4aa3-9228-f78ec024e6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d32defa1-9a2e-4da2-b024-3e48c2a14e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e8c599f2-862e-4ca9-8752-3c49dd8718d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4e58acc8-f55c-4678-b50b-31e29b9586f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e47fc20f-5c55-4990-a144-d16a8f63d76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter minimum 3 chars</value>
      <webElementGuid>00b285ea-1b10-45ac-99a5-d86c5ba6708f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter minimum 3 chars</value>
      <webElementGuid>8d33a54a-f58c-4aaa-9cd5-52c60a1d3f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change-lazy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd5136eb-082d-4e7a-a1f8-9442da6af922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;CaptureBrokerInfoWrapper&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetBrokerIndicator,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI1MWFlZmFlNTA0Y2EwNmUzYTgzM2Q0MGIwN2MxYzc5NTk0MGE0NTBkODFlMDE5NjJlYzEyZjQxZGNmYjM4OGNjNjA4M2UwODgwMWEwOWJkMmE5MTE0YzI3MzIwNThmMTgyZTBkNzBiNTgwZDE1ZDUwZTgyOWU4MWM3MzljZGRlZDkzMDgwNjE0OGVmZDY1ZGVjMGEwMThiZjVmMmM5OWM2MWM2N2Q1NGIyMTRkNjQ1ZTI3ZGRmMWMyNzViNTgwZjU2NzQ2ZjJkYWVlYTcyMTI4MTExNDQ2YmRiMDlkNDA2MDI0YTFhNWMwZjFjZDU1ZGZmMzEyZjQwYzY1M2RiMjA1Yjk5ZWEzMjc5Y2ZmZTI5OTU3ODU3MDJmZDQyNTVjOGI%3D*&quot;,{},{&quot;Domicile&quot;:&quot;&quot;,&quot;IsCalledFromBrokerScreen&quot;:&quot;true&quot;}],&quot;pyWorkPage&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;FLSummary&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmJiMTNlMzY1NDlhMzU1Y2NkOTlhZTdiOTQ0MmQ4Y2Q5YQ%3D%3D*&quot;,{},{}],&quot;pyWorkPage&quot;]]]</value>
      <webElementGuid>8100be0d-bcd4-4094-ada8-b6b6abffc9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201612081057060185133984</value>
      <webElementGuid>218540f6-2875-42b4-b959-f8ed798a42d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;AutoCompleteAG&quot;]</value>
      <webElementGuid>182dd072-0225-4caf-b13a-652522e3f99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60a2ce20-2446-4fd0-8ce5-cd3e158c798a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4b4b3600</value>
      <webElementGuid>e5835dad-6400-46ce-bddb-3871b3ecb7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete_input ac_</value>
      <webElementGuid>c0c6bc8c-9b54-4237-8734-d7d4658fc1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-displayfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>47d1a749-dba3-4dac-ade3-a803b719cb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attributes</name>
      <type>Main</type>
      <value>[&quot;EXPANDEDSubSectionCaptureBrokerInfo4_FLAgencyName&quot;,3,170,{&quot;Name&quot; : &quot;.FLAgencyName&quot;,&quot;City&quot; : &quot;.SearchStringFirstName&quot;,&quot;CountryCode&quot; : &quot;.SearchStringSSN&quot;,&quot;entity&quot; : &quot;Literal_&quot;,&quot;PseudoName&quot; : &quot;Literal_&quot;,&quot;PseudoCode&quot; : &quot;Literal_&quot;,&quot;allResults&quot; : &quot;Literal_true&quot;},&quot;pyWorkPage&quot;,0,false]</value>
      <webElementGuid>0714198e-31b5-4ddd-aa88-0e2822af5e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pFLAgencyName</value>
      <webElementGuid>001a430d-6f0b-4a3a-a728-3d72d63725fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pFLAgencyNameError</value>
      <webElementGuid>9bb66830-1e3e-4a3f-9429-6e0286748864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-ac</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>7f3db398-7ddc-4648-a063-fb73f3d9e56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter minimum 3 chars</value>
      <webElementGuid>17bd2015-b5fd-4d02-a5e7-bc807a0c0f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ba5f878d-a764-4bc1-99fe-2288e18b4c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-sub_section item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-primary_container_legend&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-layout item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-sub_section item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_grid_triple  content-inline_grid_triple&quot;]/div[@class=&quot;content-item content-field item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/input[@id=&quot;4b4b3600&quot;]</value>
      <webElementGuid>4817ecbc-ff6a-48dd-9f76-a1ecb80c567f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>fc7ce7de-7ab4-42b7-a8b4-be2923c43f34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4b4b3600']</value>
      <webElementGuid>da54b0ab-7105-482e-9c34-a2f1e82af18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>3956af10-8a38-4d27-949f-046420570f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>8c39ece3-7839-4fb5-bf6c-ebaad1896039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter minimum 3 chars' and @title = 'Enter minimum 3 chars' and @id = '4b4b3600' and @name = '$PpyWorkPage$pFLAgencyName']</value>
      <webElementGuid>c8fbc928-5bd1-4c5a-958c-53c6120f6afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
