<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PolicyHolderTurnover</name>
   <tag></tag>
   <elementGuidId>2d57a886-98a5-48e7-bd8a-9622481674d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='da94a2bc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#da94a2bc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Policy Holder Revenue/Turn Over/Fee Income&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ad0220b-0085-4bfa-9e91-a8a0df192787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170201075401045450729</value>
      <webElementGuid>cf6f2f70-f5f7-44ef-be19-68f5eaaed049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>5a9e60ac-281c-453d-9b9b-d3c3592241df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>da94a2bc</value>
      <webElementGuid>2790bf9c-d79d-4650-91ee-d14c187808b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>513ee0c7-9c04-4c35-9b95-98dadf23263f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cef13f2-d29a-432b-af6c-375b47ba7465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-formatting</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>6e0cf801-f287-40b5-82a5-f882767551e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>9454e0b2-ea49-4c12-be87-7f37141eeb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>dc920249-5f94-4913-842c-908cc96b7792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pPolicyData$pPolicyHolderTurnover</value>
      <webElementGuid>5217d687-0198-4365-ab3a-4dfe8624f949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightJustifyStyle</value>
      <webElementGuid>c98561a0-0847-451a-8517-28214efedc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;FieldTrackingChangeForBindproperties&quot;, &quot;PropertyName=PolicyHolderTurnover&quot;, &quot;pyWorkPage.ApplicationPage.PolicyData&quot;,&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDk4MjA1ZGI0ZjRkNzViNTE2Yzg3MGJlMTI1OThjODk5YmQ4YzhhNmI1M2Y5MmMwMjg3ZWI4MDZiYTc1NTdlMDM2*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BindInformation&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetBLDproperties,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDkzNjM1NzE2YjcyMDUzZTdlODczNjk4NTU3ZWNhN2IzNWM1MjJlNDc1MTk4MmNkNmY5MDU5YmRhYWRkNjQyNDhmZDBjNzE4MWMxZjliMjZjYTg1YjQxZWVkZGM1MmFhZWI%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BindInformationforendormsent&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetBLDproperties,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDkzNjM1NzE2YjcyMDUzZTdlODczNjk4NTU3ZWNhN2IzNWM1MjJlNDc1MTk4MmNkNmY5MDU5YmRhYWRkNjQyNDhmZDBjNzE4MWMxZjliMjZjYTg1YjQxZWVkZGM1MmFhZWI%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]]]</value>
      <webElementGuid>a6342990-38db-439d-b307-f48056c6f369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d16116fd-0c55-43aa-91cd-b28b8a510762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;da94a2bc&quot;)</value>
      <webElementGuid>aca99829-abc9-4b23-aeac-87d77d74dd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>f49323dc-1905-4e02-96c3-0bb715cd5540</webElementGuid>
   </webElementProperties>
</WebElementEntity>
