<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TacItRenewalDate</name>
   <tag></tag>
   <elementGuidId>4b15e09a-bb9c-42fd-9737-e07a33e16680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e425a0b2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e425a0b2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02109140800140715925&quot;] [data-test-id=&quot;\32 0170201070101025711805&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36b4e5ae-2903-4d71-91cb-8117d458af1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c43e2189-8a50-403d-8b62-462f5cd53584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e425a0b2</value>
      <webElementGuid>19679c31-215c-4823-9c6f-6a94cd27f7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pPolicyData$pTacitRenewalDate</value>
      <webElementGuid>0fde139b-f722-426b-8be4-92cb5bb8db47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;DatePicker&quot;]</value>
      <webElementGuid>f0dcc4a4-6d1d-4136-9863-6b1508dcfada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170201070101025711805</value>
      <webElementGuid>5b1fb85c-66d8-4cfd-a8ba-a5bb97a49cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autoseparator</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93f733d5-039f-4c9d-83a8-38bc5b54ced9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactvDtTmTxt</value>
      <webElementGuid>d51bd12a-3751-4d8f-ac3c-08c37183c736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>validateyearlessthan1900,date</value>
      <webElementGuid>dd4ba352-7b79-4053-820c-5cbb1cdb101b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CalculateTacitDateOrPeriod,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDk4MjA1ZGI0ZjRkNzViNTE2Yzg3MGJlMTI1OThjODk5YmM5ZDA5NWNmMWE0ZDZmZjkwNTA5MjhlYzQ1ZjEwNmFiY2Q5YTJiZTQ3YzZhODZkOWZkMThjYjI5MTJkNmUwZTdkNGYxOTg1NzVlZTE2MDk2NDg4YTM2YjEwNTQ4YjNlNmU5YWRmZDZmZWQ2YTQxN2Y5YjIwZjI0YjA4ZDI5NmJiYjc4NWM3YzRiNjE4ZGJlOWNmY2U5MTUxOTZkMzk4OWUwY2RhYzk5NmRkYjljZWE0N2U2OWVlMjQwYTY1N2I0NGVlZjY5NzY5NzBhMjAyZWRmNGViYTgyMzE3Nzg5NjBkMzc4NGEwYzk5ZmEwMGMwNTZiZWMxMmIxMTEwMTk1MzkxN2I5YWM0ZjI2Zjc2YWE0Y2IyOWU0MmEzMjBhY2JmYmNiM2MzZDJhNDBkNmMyZWYzNTNlOTQyNGY1NTc0NzI5*&quot;,{},{&quot;IsTacitDate&quot;:&quot;true&quot;,&quot;IsPeriod&quot;:&quot;&quot;}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]]]</value>
      <webElementGuid>b1882c0c-a22e-48f0-bbd2-f26d663bae61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>773146b7-123e-494f-acba-c192d3290abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e425a0b2&quot;)</value>
      <webElementGuid>ddd491e7-ee1e-4e4e-bd58-2c9c35e2b4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>992f8e50-ccd2-4721-b4de-8eb4e82f1684</webElementGuid>
   </webElementProperties>
</WebElementEntity>
