<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Address1</name>
   <tag></tag>
   <elementGuidId>cf606673-f656-44f6-ba0b-fdcedcf21690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = '28a69d61' and @name = '$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pAddressInfo$pAddress1' and @ref_element = 'Object Repository/Pega_CreateInsured/Page_Pega Case Manager Portal/iframe_QC-41722_PegaGadget1Ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#28a69d61</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'Address1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 014121907381100698857&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d28be3a-e0f3-45e6-b16d-9cbc94600747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;runDataTransform&quot;, [&quot;SetNewInsuredSelection&quot;, &quot;=&quot;, &quot;pyWorkPage.NewCustomerInfo.CustomerInfo&quot;,&quot;:event&quot;],[&quot;&amp;&quot;,[&quot;Pop&quot;]]]]</value>
      <webElementGuid>ce97e416-adef-4acf-9b62-071bf9186bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2014121907381100698857</value>
      <webElementGuid>47bd0d82-7e5f-4c14-a9da-efdc04f15267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>d0b9f131-39c6-4d3b-ae54-d91018cf9d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b319a4f-5615-4874-a8c4-2ea724568ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>28a69d61</value>
      <webElementGuid>6e61ec39-d70d-4bf6-9a53-5e94d807f2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>293cc9d5-fce0-45f4-9e44-fa56cd72d09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>0eed1ffb-161f-4862-b796-77dec391cb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pAddressInfo$pAddress1</value>
      <webElementGuid>d5a878b7-1e0f-4bbf-9770-ac0df3bfa511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>116e8a43-442a-40bd-96f2-0f0ecec9cdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pAddressInfo$pAddress1Error</value>
      <webElementGuid>4986f98c-a650-445e-8a70-b6a0410d57de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c34769b-2bf5-4196-b9a7-6744f78b048b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee580345-dcdc-42f4-921f-880659da3074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;28a69d61&quot;)</value>
      <webElementGuid>41b3e9af-e50c-4dcf-b26b-0f351d377a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>27439a78-1922-40a8-8cd4-ae764bbedca3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
