<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DueDate</name>
   <tag></tag>
   <elementGuidId>872bbeb2-3459-4221-8393-ec70fa1f1db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='8414fbbe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8414fbbe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02109021856370655590-R1&quot;] [data-test-id=&quot;\32 0170301112027023568219&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50703330-1821-425f-a0b8-1d6289298dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78b8d96a-e9f8-4d0b-b557-6eaa25e87e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8414fbbe</value>
      <webElementGuid>a793a9a0-8207-4a27-a956-e60681dcdb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pSelectedQuote$pPremiumData$pInstalments$l1$pDueDate</value>
      <webElementGuid>82c946ce-f96d-482e-b731-380827b3dbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;DatePicker&quot;]</value>
      <webElementGuid>22e14c06-7bc9-48a9-8bca-ee23086ccb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170301112027023568219</value>
      <webElementGuid>f6bade1e-8439-4aa5-b53c-79e7fce29349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autoseparator</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9af1ad27-f48e-4990-be95-0567e45b947a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactvDtTmTxt</value>
      <webElementGuid>2fcb30c8-5e6c-4655-9e03-e24ea6f2ad8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>validateyearlessthan1900,date,required,auto_format</value>
      <webElementGuid>b58156c3-3fb9-4676-893c-e5c94e70518d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;PopulateDueDates,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDk4MjA1ZGI0ZjRkNzViNTE2Yzg3MGJlMTI1OThjODk5YjcyZTQ5NWZlZTM2MTdiZDNiM2VhOWVhMWI1MGJjOGY2YjliYzY1ZWQxMTA5NjljYmI4OTQ1MjI0ZDg3ZmMxYjU2ZDZiYjZiOWJjZTI5OWI1Nzk1OWIxYWQ5YzE0OWI0MjExNWVmZjNmMWNiZDA4MGQ4ZGUxNzI0MDM2M2E2MjM5*&quot;,{},{}],&quot;&quot;]]]</value>
      <webElementGuid>4a2a6301-e423-440b-a11f-b94ee6dd68e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5a0db66-682d-4972-8911-8139c31db0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8414fbbe&quot;)</value>
      <webElementGuid>552271d6-1c68-4c3e-be1d-0c5b13772d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>c5fef607-d653-447f-bac5-fa36b7fa388f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
