<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ApplicableLaw</name>
   <tag></tag>
   <elementGuidId>a920afff-58b0-4ad2-bf21-8fef527f01f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d18b702e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RULE_KEY']/div/div/div/div[2]/div/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Applicable Law&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c35dbf1c-a94b-4617-bc78-e1523ff15a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20161122055128076680286</value>
      <webElementGuid>30916237-121e-4f54-addc-8480df477f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>28b63a24-c359-44d1-90e0-c5bf6648bc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d18b702e</value>
      <webElementGuid>bb1e4187-71f4-4d57-b6b6-fe7cd4920aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2a167c1-0acb-478c-be55-22d4ef06ae21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pProposedQuotes$l1$pApplicableLaw</value>
      <webElementGuid>cf4c3768-a6ab-4b09-8bd3-b282946e6691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>8f2c851c-f356-4261-bb92-063ed2da74f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;FieldTrackingChangeBindStage&quot;, &quot;PropertyName=ApplicableLaw&quot;, &quot;pyWorkPage.ApplicationPage.ProposedQuotes(1)&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>639395c9-780b-4e40-b42d-eaef5ad7541f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce35033d-66f7-4b2b-96b3-e0bd18cc5301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d18b702e&quot;)</value>
      <webElementGuid>a26cfc94-143e-4bdb-b1b0-a0a4a4969299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>d12f6ecb-3169-422e-b45b-26283c0e4226</webElementGuid>
   </webElementProperties>
</WebElementEntity>
