<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DeclineDescription</name>
   <tag></tag>
   <elementGuidId>ec4f6e86-aa89-4fa5-945d-e1320cf61914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='c457450a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c457450a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 016123011511401018825&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5a3327a1-40f8-4004-b21c-139a343a47cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2016123011511401018825</value>
      <webElementGuid>afc101f0-acc5-4c6b-a62f-1f77c31869a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c457450a</value>
      <webElementGuid>aa2b1e6a-fe34-435e-8ca1-ec18a96f2cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;pyWorkPage&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX0wZDI4YzVlNTZiNGQ2NWQxZmJhN2I5NjRlODVlMGE5ODBhZDlhOTRjNjNkMWM3YzNmYTU4YWNiMGUxNzkyNDE2NWM0ZjQ2OWYyZDRmODZiMGRkYmJhY2UzYmZiZmI4Mzc5YjlmMGJiNThmNTRlNzk1NjM4MzMyN2Q5OTk1MDJmMDZmMmU3YTViNGU5MTU4MThlOTRiNzEzZTQ1MTBjN2FmNTkyNTgwODY0YmIwOTcwOGYxYmNjN2E1NTZlNjFkZTgyMzk3NmQ0ZDc0M2NiMWMxYTdiNjBkNTcyNzI1ZGQ0NmM2MTU0YjU5ZDdkZGI1OTY2ZWJjZjQzNjBjMTVkZTE1*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX0xMzE4ZDZhNjM0NTkyMzk5ODFkMTk3NGYwMjUzYjZjMjcyYjcxNzdiZmI3OWY1YTRkMWU0YjJjYjM0ZWY0MjM5ZjQ2MmY1NDNjMmNjYjViZDY5Y2U4NjA4ZjQ0ZjFlYWQ5YTA1OWU2MDY0ZmU2ZjY1Zjg0YmIyNzE5ZDMyZjIyOWY4NmMyZGZhNjVkNjZhODE4YzRiNjZjOGQ4NjY2ZTU5YjZhZmE4NTUyMTYwZTQ2MDNkZTgyZDBmNTY0NTRjMGQ%3D*&quot;,{},{}],&quot;pyWorkPage&quot;]]]</value>
      <webElementGuid>abea8e7d-d5d7-41c3-8a74-bfbebb810cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TANORM textAreaStyle</value>
      <webElementGuid>d34f2e13-f62e-41f5-b52f-7c3e99f5fbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pDecDescription</value>
      <webElementGuid>b1db3153-3b58-4867-993a-8247f2602038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-exp</name>
      <type>Main</type>
      <value>Enter to Collapse</value>
      <webElementGuid>ed93be54-cb91-46ee-8e0c-caaaf6197a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col</name>
      <type>Main</type>
      <value>Enter to Expand</value>
      <webElementGuid>a89ea6d9-9fef-4241-a755-6684cc13e19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Declined Reason Description</value>
      <webElementGuid>8a5023d6-ece0-4fbc-978a-832a645f326b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f6c071ef-f0a8-4848-b72e-4fbcda06cebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>updatecounter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1733cfd4-f7bf-471b-b626-e21f76e9cc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>3bd40ac6-bf75-4c2f-aacf-ee67f65a3b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextArea&quot;,{&quot;height&quot;:&quot;content|5|rows&quot;}]</value>
      <webElementGuid>467090f5-8e1d-4227-af33-a798c16d3e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pDecDescriptionError</value>
      <webElementGuid>123dbae0-3332-4ee4-9f20-8c1413a51336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Declined Reason Description</value>
      <webElementGuid>2daa7de1-3204-4d11-83a5-97f9eb63b5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc76c5e5-24e2-4c95-8436-fd9c04096aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-heightupdated-onload</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a1aad37c-c056-4949-bb7a-1dca054aa94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c457450a&quot;)</value>
      <webElementGuid>bd3873ae-73c7-41cf-9023-1e21c31932b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>18d79ad5-a84f-4c38-9cf5-9d01a0909126</webElementGuid>
   </webElementProperties>
</WebElementEntity>
