<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IsParent</name>
   <tag></tag>
   <elementGuidId>d8710209-e9dc-462e-828b-a0a9f0f21129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @name = '$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pIsParent' and @id = '85fabb9a' and @ref_element = 'Object Repository/Pega_CreateInsured/Page_Pega Case Manager Portal/iframe_PegaGadget1Ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#85fabb9a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox' and contains(@name,'IsParent')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0161109182816032562852&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4baf4ac-ff27-4aac-b225-7bcdf152a694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9697f4c0-512c-4252-b4d1-daa050782acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20161109182816032562852</value>
      <webElementGuid>e82e2262-0962-4028-8134-8ddc6eb22c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox chkBxCtl </value>
      <webElementGuid>60b66280-6a02-4bc8-a61e-73309c7bd729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6fa54a75-6b60-45b6-b4a0-2840028eb4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pIsParent</value>
      <webElementGuid>d04ad88f-62bc-4628-bc02-1024160cb6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pIsParentError </value>
      <webElementGuid>56ad73aa-2cd5-4bd9-aaad-26ae283186eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>85fabb9a</value>
      <webElementGuid>c368696d-424c-4cf6-bc6f-09ecd2f86e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>true-false</value>
      <webElementGuid>8bc334b0-1bb5-477e-896d-e6db74eca5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Checkbox</value>
      <webElementGuid>72c98e1d-6f3c-4a68-9c73-1cf238c442cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>[[&quot;runDataTransform&quot;, [&quot;FLTooltipParam&quot;, &quot;pharagraph=InsuredDetailsIsParent&quot;, &quot;pyWorkPage.NewCustomerInfo.CustomerInfo&quot;,&quot;:event&quot;]],[&quot;showSmartInfo&quot;,[&quot;FLToolipsInformation&quot;,&quot;&quot;,&quot;:event&quot;,true,&quot;&quot;]]]</value>
      <webElementGuid>470650d2-dc7d-46d2-8a2d-c8e9d840be49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;ResetParentInsured&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTRmNWFkYTg3MjliYWEwYjgwMTMxOWQ0YjgyNzg1OGY5YmJkZjhkOTI4YTBlOGE0OWU0M2YwYzc3MGI4MmE1Mzk2Nzg4NzAzNGNjMzU5NmExZWMyOGU3MWVkMGEyZDc0NmMxMDVmYTBiNDY1MTA0ODI2NjNkYTVmY2ZmYzM2MzJi*&quot;,{},{}],&quot;pyWorkPage.NewCustomerInfo.CustomerInfo&quot;]]]</value>
      <webElementGuid>90849ada-90de-4375-a45b-f0070210c16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>pega.c.cbe.processHoverEvent(event)</value>
      <webElementGuid>6c35e78f-ae05-495f-a6fd-d461dc535b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>930ceb1f-fefd-429e-bc11-189f53816d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>047286ee-6164-48f3-a4ad-4872467a9be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-back-nav-id</name>
      <type>Main</type>
      <value>key4</value>
      <webElementGuid>658cfd13-b217-41f2-820d-3f4dc09812c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;85fabb9a&quot;)</value>
      <webElementGuid>ab77b9bb-8c73-4432-a17c-6c2270f9c52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>a739cdee-f2b7-45ca-83ba-4ff31e8b56fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='85fabb9a']</value>
      <webElementGuid>d0dd5a7f-3103-4001-adff-c8a15ed3e83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div/input[2]</value>
      <webElementGuid>b9fca299-fcf1-4172-9fc3-991d8f88a7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input[2]</value>
      <webElementGuid>73873ccd-a62a-43b5-8eb5-4712788b89e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = '$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pIsParent' and @id = '85fabb9a']</value>
      <webElementGuid>1d9a8021-c750-4cbb-980e-4f04e51e4cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
