<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CoverHolderName</name>
   <tag></tag>
   <elementGuidId>b86964ad-11fe-4282-8bb6-d43ad6e08e93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = '$PpyWorkPage$pCoverHoldersName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#0ac9bab4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02111111043000780299&quot;] [data-test-id=&quot;\32 01612081057060185133984&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7d10b84-7441-4109-b453-9480742d676a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>299c37de-62d0-4a69-b031-c0cca929bc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2179f76d-e151-4c1b-846c-f1beb55519f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5b327825-89ea-43f9-9557-feb1d8f69c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>063eacc5-1339-49d7-9380-983da3032ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201612081057060185133984</value>
      <webElementGuid>977931e9-b014-4715-8501-f0f171bfd8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;AutoCompleteAG&quot;]</value>
      <webElementGuid>062a84ae-8d6b-4e6f-8917-78af035e519b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba4f070d-dbbf-4c21-87eb-c1961e9fe6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ef6b9bd-1137-485f-a2dd-e6d4c96c0ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0ac9bab4</value>
      <webElementGuid>8637f4f5-446e-401c-999d-f96346b1ce46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expr-id</name>
      <type>Main</type>
      <value>cebfe10a11f8132f03f810bbf4b6549d35fa6519_7</value>
      <webElementGuid>da793a47-f01e-4d77-93ef-e707651db3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-context</name>
      <type>Main</type>
      <value>pyWorkPage</value>
      <webElementGuid>cd1fa1d1-d417-476b-9782-7d00aaf6e9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete_input ac_</value>
      <webElementGuid>819e7982-91a9-493c-bfe6-2bc17306059a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-displayfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b2aba4d7-86f4-4f5f-a9be-fd20b4bbf085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attributes</name>
      <type>Main</type>
      <value>[&quot;EXPANDEDSubSectionCoverholdersDisplay1_CoverHoldersName&quot;,3,170,{&quot;Name&quot; : &quot;.CoverHoldersName&quot;,&quot;City&quot; : &quot;Literal_&quot;,&quot;CountryCode&quot; : &quot;Literal_&quot;,&quot;entity&quot; : &quot;Literal_CoverHolders&quot;},&quot;pyWorkPage&quot;,0,false]</value>
      <webElementGuid>163044cb-3827-474e-8c65-7794dd642778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pCoverHoldersName</value>
      <webElementGuid>230d3f2c-8e9f-4fef-b528-d8adc93dd528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pCoverHoldersNameError</value>
      <webElementGuid>a9a06a35-8122-4baf-97aa-c1e05656a9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>166f3a99-0855-4309-9804-6400d8da1028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-ac</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>9a81416f-84b6-43f3-986e-68169f52ff9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db3d9ac0-3a9d-40ee-bcb1-75acc057a4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0ac9bab4&quot;)</value>
      <webElementGuid>f9c5cc64-41aa-4ddf-a779-5558158aefce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>52b93861-bbfc-4d1e-a7fd-48eafdcaadad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
