<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_InceptionDate</name>
   <tag></tag>
   <elementGuidId>b226aac2-f023-4bb0-a574-d8fcf8648816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c54671b9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'EffectiveDate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Inception Date&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dd2f209-20ea-4bd2-9228-2814f00c3e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5af9c09-c63b-4bee-8bdd-18aade954f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c54671b9</value>
      <webElementGuid>e5e2f6a1-fcdd-4882-82e0-b538f0a2032b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pSelectedQuote$pEffectiveDate</value>
      <webElementGuid>b921cb55-cd56-430d-90a3-6b41b695f431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;DatePicker&quot;]</value>
      <webElementGuid>b11c6e16-5dc4-48e6-9528-b0329c2d3b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170201070101025711805</value>
      <webElementGuid>b6675611-e248-4317-878b-343ce751fc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autoseparator</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a899ed3-c2b1-4a78-86b0-0506194f3a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactvDtTmTxt</value>
      <webElementGuid>0f0673d5-f507-46d2-951d-3da88f66eab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>51147823-e0e8-4695-85cc-b0ee663cf903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;IsLeapYear&quot;, &quot;=&quot;, &quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;,&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CalculateDateOrPeriod,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTcwOTcyMGFhYzk3ZDM5ZWY2M2MwYTk4YzAzODg5ZjcxYmMwOTgwMDU2ODQxM2RjNDliMzdiYTlkN2M3MDlkMjAyYzhjNTEwZmFlNzEyMzU3ZDNjMjEzOWQ2MDFhZTBkNDNmN2UzYjUxY2FiZWM1MjU3ODMxMzNhZmE4NjhjMWU5YWI4NzVhZGY5NWU1NjcxY2YwMDU5MGJmODI0NWJiOTM5MmI1ZmMwOTdhNWNkM2ZlY2YzYjVkY2NmZmRlODQ4YjE2OTkyYTk0ZDEzZDJiYjE3Zjc4OWI1YzkwZmI4YmI1NGNjYjAxMWMzYTIyODE1MWYzZTQ5ZTljNjI2ZWUyODIxMTNjMjY5Nzc1MGIyYzZhYmVjZjViMTQ3Y2U1YzllMWVjYTYzODdiYTdjMWZjNGRlYzIzOThkMzk1Mzk3MjI3OTcyMDcyNDFmMGYwY2I4MzQ0OWYxOWZhMmMwMmY4MDBlYWJiNjExMGM1NzI4NGIyMTE2ZDcxZDU2MjViODE5YTQyMDM5NWRjNDExMDZkNDU2YmM0Njk4NDdmNjExYmMx*&quot;,{},{&quot;IsInceptionDate&quot;:&quot;true&quot;,&quot;IsExpiryDate&quot;:&quot;&quot;,&quot;IsPeriod&quot;:&quot;&quot;,&quot;spa&quot;:&quot;&quot;}],&quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;GeneralDetails&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmJiMTNlMzY1NDlhMzU1Y2NkOTlhZTdiOTQ0MmQ4Y2Q5YQ%3D%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;]]]</value>
      <webElementGuid>afd9058e-2fb8-4439-bde8-d444f4335eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76c0f3a4-07d5-47ae-89cc-85ca654be195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c54671b9&quot;)</value>
      <webElementGuid>8f167739-d602-4f95-a9e2-92b3269bc82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>1b570ce0-e2a7-47e8-891d-620974d790f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c54671b9']</value>
      <webElementGuid>aff6b242-71d8-4dd5-9570-8697ebfcb528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='$PpyWorkPage$pApplicationPage$pSelectedQuote$pEffectiveDateSpan']/input</value>
      <webElementGuid>6e3a73a3-1228-49db-9bba-5ad865cb01de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>0a67f776-9318-40ff-9376-74bafdcf4ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'c54671b9' and @name = '$PpyWorkPage$pApplicationPage$pSelectedQuote$pEffectiveDate']</value>
      <webElementGuid>52344a6f-a64e-4403-b2f1-e15d4d191d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
