<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TMHCCWrittenParticipation</name>
   <tag></tag>
   <elementGuidId>e53b7afd-3d26-4dbd-9ce5-e8dc6d8b7c19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c855d3d0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'TMHCCWrittenPartPercent')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;TMHCC Written Participation %&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efa09252-3887-4789-a046-26cffe033b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20161122060106049911402</value>
      <webElementGuid>a57b1c32-3720-468b-959d-0023c1a45bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>c82dcb28-26a8-4423-88ad-53743896d8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c855d3d0</value>
      <webElementGuid>2690572f-283b-493e-bba8-ca061d437f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>5031768d-2f9e-4892-9646-5c74fa5d8353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4e49cd19-cf25-4035-99aa-d73e7b808555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>isvalidpercentage,decimal</value>
      <webElementGuid>79499ede-b602-471c-94ae-606eb00e9351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>51785296-6eb4-4483-99d9-989c4c9ee2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pProposedQuotes$l1$pTMHCCWrittenPartPercent</value>
      <webElementGuid>90f40504-a464-4993-b523-5493522d61dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightJustifyStyle</value>
      <webElementGuid>d9f5f8b3-08a1-4a9d-b2cd-45c80b574036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;ComDisplayGrid&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CalculateLimitDetails,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTQ5MjNlZTJjMTNiN2I2MzhkZjNlODkzMjk3YjU0ZDJiN2U1MjJlNzJjYjk2NThjYTMyMzdkM2IyMjM1MjUyNmI3ZTc0YWZmZmE0YzRlZjNmMmE4YWNlMzU5ZDcyMzg1NjA%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.ProposedQuotes(1)&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BindInformation&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetLeadBasedOnEntityAndTMHCC,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTQ5MjNlZTJjMTNiN2I2MzhkZjNlODkzMjk3YjU0ZDJiNzQ2ZjM2MjM4OGQzY2Q3NjAzZTU3Mzg5NGUyYWRlMjQ4YjBkYWFkMWE0ODIxYzMxNjc3ZDJjOWI1OWIyN2VmMTk5NzdiMjAxYWI0YzkxODQ5NjVkYzJkNThlNzg5NmNiOTIxOWI4NDljZjQ1ZTkyYmE0ZTBiZThiMmI1NWU2MjdmZmE3Mjg5YjNiZjNlNDliNDRkOGZlNGE3YzdiNjEzZTg4NmE4NjRmMjczNWE0NWJlZDkzYTVhYzRmMmNhNzVmNDc0MjAzMmFlZTZhZDU1ZTFhZmYwODhhZTRhNDg4YzdhNDVjOTI4ZGY5MzY3OTkyZmFmNWIyZmM4Mzg4YjM0ZDg%3D*&quot;,{},{&quot;FromEntity&quot;:&quot;&quot;,&quot;CalledFromLead&quot;:&quot;&quot;}],&quot;pyWorkPage.ApplicationPage.ProposedQuotes(1)&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BlendedPremiumDetails&quot;, &quot;CalculateBlendedPremiumAmount&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTRkOTE5MjZlZDM0MTc3NDQzZDY3Y2QxYmViNmZlMTJlMGNiYzQxNzVlOGJmZDYzYTc3ZGEzNDU1OTc4NjJkM2ZjZDQwZDk0NDlkZjNlM2UyMTA4ZjM0ODIyMTdlYmZkYWU4NTZiMzExYmM3ZWViYzYzNzU5Mjc5Yzc1N2IwNTYyNmZlOTFiN2FlNzk4MDY2MTE3NmEzZWU2MTI1MjM0N2I2MTc0YjFjNmZhZGQzZGY1MzEzNWM1OWIyYzU4NTdiMTk3OTE5YTg1YTcxZmUzMDhkNmNhOWM0ZGQxMTFjMWVmMw%3D%3D*&quot;,{&quot;div&quot;:&quot;&quot;},{}],&quot;pyWorkPage.ApplicationPage.ProposedQuotes(1)&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BindQuote&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetLeadBasedOnEntityAndTMHCC,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTQ5MjNlZTJjMTNiN2I2MzhkZjNlODkzMjk3YjU0ZDJiNzQ2ZjM2MjM4OGQzY2Q3NjAzZTU3Mzg5NGUyYWRlMjQ4YjBkYWFkMWE0ODIxYzMxNjc3ZDJjOWI1OWIyN2VmMTk5NzdiMjAxYWI0YzkxODQ5NjVkYzJkNThlNzg5NmNiOTIxOWI4NDljZjQ1ZTkyYmE0ZTBiZThiMmI1NWU2MjdmZmE3Mjg5YjNiZjNlNDliNDRkOGZlNGE3YzdiNjEzZTg4NmE4NjRmMjczNWE0NWJlZDkzYTVhYzRmMmNhNzVmNDc0MjAzMmFlZTZhZDU1ZTFhZmYwODhhZTRhNDg4YzdhNDVjOTI4ZGY5MzY3OTkyZmFmNWIyZmM4Mzg4YjM0ZDg%3D*&quot;,{},{&quot;FromEntity&quot;:&quot;&quot;,&quot;CalledFromLead&quot;:&quot;&quot;}],&quot;pyWorkPage.ApplicationPage.ProposedQuotes(1)&quot;]]]</value>
      <webElementGuid>201150ea-bb73-4017-9c73-c941303fb656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c855d3d0&quot;)</value>
      <webElementGuid>46c55c2e-57e6-4ea8-8178-1008508d496d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>e92ed89e-2245-4dd4-b705-a2aeee0254e3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
