<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EntitysTotalAsset</name>
   <tag></tag>
   <elementGuidId>8ad16aef-7453-40d4-b4d7-4c5f29003b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='5bcc748d'] | //input[contains(@name,'EntitysTotalAssets')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5bcc748d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Entity’s Total Assets&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b429a3a-5a93-4c78-96cf-c877cde66376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201702030859380409204411</value>
      <webElementGuid>013c8928-740a-453b-9caf-104beccb3772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>771eb640-fa40-423f-bb7a-4f165da6a930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5bcc748d</value>
      <webElementGuid>1bbf591e-c082-4814-aa59-01ad33cd0fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>38f9b264-7623-4ce9-84f0-27f73f27ae95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21fe94e0-a9f2-4a0a-91f6-01e4df0c512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-formatting</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>419a0906-8906-484a-9556-1c815e64dcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>1a7fb293-840e-4e77-97e0-6713dd2a6068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>b41130e5-cbe8-4c17-bf6d-374982ecfcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pPolicyData$pEntitysTotalAssets</value>
      <webElementGuid>c18f4f9f-0f96-4451-a103-39df3803f8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightJustifyStyle</value>
      <webElementGuid>011b1b40-05d6-44ff-a3f6-a83f5383bd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;FieldTrackingChangeForBindproperties&quot;, &quot;PropertyName=EntitysTotalAssets&quot;, &quot;pyWorkPage.ApplicationPage.PolicyData&quot;,&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDk4MjA1ZGI0ZjRkNzViNTE2Yzg3MGJlMTI1OThjODk5YmQ4YzhhNmI1M2Y5MmMwMjg3ZWI4MDZiYTc1NTdlMDM2*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BindInformation&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetBLDproperties,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDkzNjM1NzE2YjcyMDUzZTdlODczNjk4NTU3ZWNhN2IzNWM1MjJlNDc1MTk4MmNkNmY5MDU5YmRhYWRkNjQyNDhmZDBjNzE4MWMxZjliMjZjYTg1YjQxZWVkZGM1MmFhZWI%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BindInformationforendormsent&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetBLDproperties,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDkzNjM1NzE2YjcyMDUzZTdlODczNjk4NTU3ZWNhN2IzNWM1MjJlNDc1MTk4MmNkNmY5MDU5YmRhYWRkNjQyNDhmZDBjNzE4MWMxZjliMjZjYTg1YjQxZWVkZGM1MmFhZWI%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]]]</value>
      <webElementGuid>99ea94cd-ecfc-4967-adc3-f565df782de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>99d92a95-eaab-4d75-9f74-2e12960f9a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5bcc748d&quot;)</value>
      <webElementGuid>e519e0d3-d312-4550-abf1-3137842df8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>88c65650-67a0-4a83-b1f8-240ae920cbee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
