<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownPolicySlipInsurance</name>
   <tag></tag>
   <elementGuidId>72e76383-ae8e-4f01-b99e-931526dfe38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy/Slip Insurance'])[1]/following::select[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e9e50bd0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 017112415145900097931&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>89b3ca9e-b57c-47f3-8a4e-ddd663ba71c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;currentharness&quot;,&quot;&quot;, &quot;SaveAssignPage&quot;, &quot;{\&quot;sp\&quot;:\&quot;=\&quot;,\&quot;dp\&quot;:\&quot;\&quot;}&quot;, &quot;&quot;, &quot;InitializeStatus,{\&quot;sp\&quot;:\&quot;\&quot;,\&quot;dp\&quot;:\&quot;\&quot;}&quot;,&quot;:event&quot;,&quot;&quot;,&quot;pyWorkPage&quot;]]]</value>
      <webElementGuid>70584e4c-d9e5-43d8-8891-1fb8c293ee26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2017112415145900097931</value>
      <webElementGuid>1f063768-c6b0-49bf-a744-2f1831e286d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>1073e2fe-a13f-457a-8c77-f6b1d6c00b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c873049-465e-43d6-9165-a58b14902a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a3ccff6-ee08-4567-99cb-b6c3691028a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e9e50bd0</value>
      <webElementGuid>b55977fd-2a5a-4e8f-9b22-d31d81f6f315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>8c46c7f3-023c-47d9-8ea6-58272e57be30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pPolicySlipInsurance</value>
      <webElementGuid>8224eb8d-ba9e-4f57-b847-a2bd9062a785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>737ce4f4-0530-4cbf-9425-8c8f0c0a6798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pPolicySlipInsuranceError</value>
      <webElementGuid>e4713f50-b47f-4c07-9a83-7121be02cc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

  Select Value

Slip - CC Check requiredPolicy/Legally Approved Wording - CC Check not required

</value>
      <webElementGuid>37143d02-5f2c-449f-a8f1-f87879350db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e9e50bd0&quot;)</value>
      <webElementGuid>cd046efc-a78d-479f-8ecc-7392bbf8d65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget2Ifr</value>
      <webElementGuid>31714ff6-60d0-43ed-990b-249045324c60</webElementGuid>
   </webElementProperties>
</WebElementEntity>
