<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownEntity</name>
   <tag></tag>
   <elementGuidId>8708139f-23cd-460b-a3ab-e179f28b9513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#52e33282</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'Entity')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Entity&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e9f1d839-3a4d-4629-a637-e975efd24f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>de0b6fef-e265-4c20-9b80-33ebe6c81fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20161122060106049911402</value>
      <webElementGuid>0dec8564-1f2a-4719-8d16-66db814f4ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>adc1209b-7f2f-49ff-89bd-853bd1d07466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>52e33282</value>
      <webElementGuid>fd879c04-2d5c-4539-9c92-d1aeb341119f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pSelectedQuote$pEntity</value>
      <webElementGuid>bfff3fa0-b080-4092-ba87-26b0bbe7ebaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ResetBureauIndicator,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTcwOTcyMGFhYzk3ZDM5ZWY2M2MwYTk4YzAzODg5ZjcxYmMwOTgwMDU2ODQxM2RjNDliMzdiYTlkN2M3MDlkMjAyYzhjNTEwZmFlNzEyMzU3ZDNjMjEzOWQ2MDFhZTBkNGYwYWUyMzllMWY4MmFjMDI3YzU0MmFmOThkNzYxZDg5ZmYxMGFlNWI0MTE5NjA5YTFkNzE0ZmE1MzM1NzkxYjlkMjUxZjdmZmZjM2YxNDhiODE2NTQ1Y2ZkZmM0YTEyZDk3Y2E1MDM3Y2ZmOTk2OTA1ODQzYTUxN2NiNjFjNWNhMjY4MmQ2MGFhYTYwNGI1MTVkZTg5MzgwZDFiYzI4ZTUzOWNlYmQwYjVjM2M2ODExYzM5NDQwNTUyNjk4NzcyNDY1ZDE1ZmQ1OTBlNTJjYzljOTdlMGY0YTI2ZmU0ZDQw*&quot;,{},{&quot;FromEntity&quot;:&quot;true&quot;,&quot;FromLegalBranch&quot;:&quot;&quot;}],&quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BindInformation&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetLeadBasedOnEntityAndTMHCC,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI1MWFlZmFlNTA0Y2EwNmUzYTgzM2Q0MGIwN2MxYzc5NTFmZmZkZTllZjY0MjAwNTg3MTU3ZjgxNjM1ZTA4MDNkODVlZTAzODIwZTI4OTljZmJkZTdmZmJiNTY3ZTA1MDllY2Q2NzRmNTJhMzI0YTg2ODE1NDY5ZmQzOTVjMzY2YmQ2YTg5MDJkNDZlNzY2MzUzMmEwMzJmMjdkOWNkNjhjNjY4ZTc2MTE3MTdiODFjMTYwNDFlYmI4YWM1YjAzODRiMGNiY2FlOGIwZTJlMWZiOWM5YjIzYWY1OTM0MDQ1MQ%3D%3D*&quot;,{},{&quot;FromEntity&quot;:&quot;&quot;}],&quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;]]]</value>
      <webElementGuid>c8813537-c11b-48ff-b534-f9e01acab7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...HCC InternationalHCC Syndicate 4141Houston Casualty CompanyTokio Marine Europe</value>
      <webElementGuid>c6aa1302-f8d1-4b82-bd76-37d3646d190a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;52e33282&quot;)</value>
      <webElementGuid>0d2dd35d-bb14-4ef3-9aa8-b50b25876bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>22d392f2-7f6f-4371-983a-bbef49a04a43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='52e33282']</value>
      <webElementGuid>114d2eb0-271e-418e-a709-a121a5cdb4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div[2]/div/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>a71949a0-04ea-4a1e-9f24-1fb648418dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity'])[1]/following::select[1]</value>
      <webElementGuid>a2c7fb05-98d5-47f7-ab95-d4e45fef3af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Period'])[1]/following::select[1]</value>
      <webElementGuid>d2a750e1-5890-44c7-82da-5fafd7635274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal Branch'])[1]/preceding::select[1]</value>
      <webElementGuid>511dafec-482f-4e74-bad5-a115e0c9b950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bureau Indicator'])[1]/preceding::select[2]</value>
      <webElementGuid>e3039c8a-389e-449f-b77c-378d42a1ecc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>98c16cfc-8441-4653-9e25-da1606760815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '52e33282' and @name = '$PpyWorkPage$pApplicationPage$pSelectedQuote$pEntity' and (text() = 'Select...HCC InternationalHCC Syndicate 4141Houston Casualty CompanyTokio Marine Europe' or . = 'Select...HCC InternationalHCC Syndicate 4141Houston Casualty CompanyTokio Marine Europe')]</value>
      <webElementGuid>cf885783-d806-465f-ad8e-f5149e60a9de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
