<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownMajorClass</name>
   <tag></tag>
   <elementGuidId>ff8f4826-03a4-459c-ab2f-7f022b70f185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#61e6d1a4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'MajorClass')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Major Class&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ea915a1-4d59-4358-9908-8dfff28ff6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>2370ff97-d77f-4f78-b82a-07bf122001df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201610070553050950186780</value>
      <webElementGuid>9cf19693-bb89-4584-9849-c4c941928fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>7e3dd724-0d56-4f0f-9d25-c5f5ed818b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>61e6d1a4</value>
      <webElementGuid>48b4c85a-67ba-43e4-8c21-64b2da8da7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pMajorClass</value>
      <webElementGuid>39df00b4-68c2-4e02-be99-6cdc2c5e47e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ResetTRIDetails,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTRlZjNhMjU0OWFkZGJhM2NjNWVhMDdlNjcwYjFhMjIxMTJjYmM3ODdlODkwNjc2NGNlMmE0MWY4MTllODVkNjFmNzFiNWQ0MDEyMTk4YzRmZGE2ZGNhMzUzYzQxNGEyM2Y1N2M0MmViNDg3N2M1Y2I5MWMyYmEyNjhmMDljNDBl*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;AddDefaultRowsForBlended,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTRlZjNhMjU0OWFkZGJhM2NjNWVhMDdlNjcwYjFhMjIxMTJjYmM3ODdlODkwNjc2NGNlMmE0MWY4MTllODVkNjFhNTExNDhiZGE0ZWRkNTVhYThkMTg4N2FhMDc5MWI0MmRkMzBjYWY1ZGNhMTI1NmUzYWVkNDVjYzMxOTA5YmEy*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;FLSummary&quot;, &quot;ResetDuplicateSubmissionCheck&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmJhOWY2MGNlMmQ3MTExOWEyYzQ4MTVhMDZmMTI0YzRjN2IyNGYyNzE2MDcxOTgzYjgwOGVhODQ1YTZhYjliMGJiMWM5MGMyNzg5ZGY2Mjg0Njc1NDUyYjc0ZmRjYmZmY2RhNDhhMzgxZTc5NzRkYWE1OWJiMmQwNmZhYTczNWI5NmY4YzcyNzQ1Zjg2N2ZiMGIyY2JkMWIxYWJmMzkyYjRmN2YxNDgyNDViYjljN2JjNjkzMDRjYzkxODM5M2ZlYWQ4ZDFiODUyMGEzMTdjOTMxOGM2YzkwYjQyZWZhMmYyOTYzNTRhYjgzODQwYWE0ZDdlYzU2YjMyM2M1NmM3NTRlZDUyYTUwNDg5N2U3OGZhODkwZjllYWNiOTZlY2Y3ZjQyZTc2ZjQzOTNiNDUzNTY3MTg3MzIzMGM5Y2QwNTI3YTZmZWQ0ODQ5MzFjNDg0YzAwMDU5ZDcxZGIzYmE1ZjQ0MjBiNDgwMTUwYmFlNzNhODJkYmE5YjhiNTJkZjA0MDg0OGVlNzU5MTI3OTJiOGMzNDU2M2IxMzFjMmI1ODBjZWYwMjlmNzYwYjM3ZDc1M2Y2NDE0MmRiYjZkMzkyYTJkZDAwNDQxNDRkNjcwMTFjY2U5MGYyMTBhODQ5NTI4ZmQ0ZTk2MGM4YjY1ZjA0N2M2YmUyMjk1NjI5MWNmNDgzNTgyZjU4YmY4NzVmOGUxMzA2MDhhOWMwNWYzZjI4NmZkZjhiMmRlNTA5MjUxMDcxMDM1MGEwYjRjYTUyNzkyMDc3OWE5YjAxYWEzM2NiZmVjNDNhMzRkODFhZTdhYTNmZTRjZDVmNmIzNGJlMmNjZDcwNWIwMTdkMzU3MzVlZWE5ODc3N2RkMDY5ZDZiMDljM2ZmOTJlMTI0MDMzZDViMDc%3D*&quot;,{&quot;flag&quot;:&quot;&quot;,&quot;pyID&quot;:&quot;&quot;,&quot;LOB&quot;:&quot;&quot;,&quot;OwnerID&quot;:&quot;&quot;,&quot;pyReportName&quot;:&quot;&quot;,&quot;pyReportClass&quot;:&quot;&quot;,&quot;pyPageName&quot;:&quot;&quot;,&quot;FromDate&quot;:&quot;&quot;,&quot;Todate&quot;:&quot;&quot;,&quot;DaysToAdd&quot;:&quot;&quot;},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTRlZjNhMjU0OWFkZGJhM2NjNWVhMDdlNjcwYjFhMjIxZjQ4OWEwZDNkN2I1ZDIxMWZkMWNiYmQ5MTQ3NmU0MTI%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;BindInformation&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetTacitRenewalValue,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI1MWFlZmFlNTA0Y2EwNmUzYTgzM2Q0MGIwN2MxYzc5NTJiZmU2ZmNlOTRlMzY4MDU0ODBkYmFhNDE5MjczMzM0ZjcyNDA1YTQ0MzcwYmRhZTc3MTI4YzQxOGQ3OTRjZjc%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]]]</value>
      <webElementGuid>fcd450a9-1f75-417c-ba8d-8dc99b48cd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>calculateexpression</value>
      <webElementGuid>a33a0a47-2c12-4da3-ab4e-c88659c38404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Major ClassBlended PoliciesCrimeCyberDirectors &amp; Officers LiabilityEmployment Practice LiabilityErrors &amp; Omissions - Professional IndemnityFiduciary  - Pension Trustee LiabilityGeneral LiabilitiesLegal ExpensesPropertyTransaction Risk Insurance</value>
      <webElementGuid>3adbf444-3855-44d5-be12-3323863de951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;61e6d1a4&quot;)</value>
      <webElementGuid>01f99dc5-f6f4-46f9-813a-a6e8b56d2b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>94118af2-b1f8-4ea7-a281-9782882a5576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='61e6d1a4']</value>
      <webElementGuid>b3cbcaa5-3da4-4971-b2e0-c9e6bc668d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/div/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>d1e767d3-f83e-4414-b3a0-656118ed7c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Major Class'])[1]/following::select[1]</value>
      <webElementGuid>7296de2e-f93d-459a-b581-ff32a7e2009a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Type'])[1]/following::select[2]</value>
      <webElementGuid>bebd24ce-c69e-4400-b63d-62512d5dd19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minor Class'])[1]/preceding::select[1]</value>
      <webElementGuid>a48ac722-7093-4d47-95ae-fd6f831a6238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[1]/preceding::select[2]</value>
      <webElementGuid>b2c672aa-4a47-4535-9933-7684211f5eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>ece7c188-02b6-4137-8a5f-4ab217d0b9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '61e6d1a4' and @name = '$PpyWorkPage$pSubmissionData$pMajorClass' and (text() = 'Select Major ClassBlended PoliciesCrimeCyberDirectors &amp; Officers LiabilityEmployment Practice LiabilityErrors &amp; Omissions - Professional IndemnityFiduciary  - Pension Trustee LiabilityGeneral LiabilitiesLegal ExpensesPropertyTransaction Risk Insurance' or . = 'Select Major ClassBlended PoliciesCrimeCyberDirectors &amp; Officers LiabilityEmployment Practice LiabilityErrors &amp; Omissions - Professional IndemnityFiduciary  - Pension Trustee LiabilityGeneral LiabilitiesLegal ExpensesPropertyTransaction Risk Insurance')]</value>
      <webElementGuid>69ba5708-cb74-4802-9dd4-9d6797cc0d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
