<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownClassType</name>
   <tag></tag>
   <elementGuidId>f7b09c28-00b8-4313-bf4f-2b3595ff3c60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eadeee9e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'ClassType')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Class Type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c7973eb3-3db5-443c-b5e1-7a1805cf4277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>a8aaec90-ffb0-47f2-83f6-95b146769e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201610070553050950186780</value>
      <webElementGuid>a99aaa9a-68c9-4a0d-a4cc-57222a1b92b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>2d87c388-1dc5-4cfa-8f4d-03edef33a890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eadeee9e</value>
      <webElementGuid>aaf72c15-ffdb-40e6-8b5b-48bdc0d7dad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pClassType</value>
      <webElementGuid>238c3512-90bb-4be0-b13f-651d38879978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;DefaultMajorClassValue,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTRlZjNhMjU0OWFkZGJhM2NjNWVhMDdlNjcwYjFhMjIxMTJjYmM3ODdlODkwNjc2NGNlMmE0MWY4MTllODVkNjE1MDNlOTliMDU1ZmJlMDU5NjU4MTMwNmMzODZkMWI4OTczNTA1NThjNmZhZGJhZGVjYzg5Y2I3MWMxNzdhMjNlYzJmNGZmMDgwYjU2NDFkYWY4ZTk2YTU0M2QwMTJkNTQ5M2NlN2Q2MDMzNzI4MzdiNmExMDBhZTM3OTNhMDljNmU1NDA1MmRlYzFmY2ZlNzFmN2ZmYmQ4ZmQ4OGMzZTk2ZjlmYTA2MWQ1NTAzYzk0ODI2ZDAyNjIzZWMyOTRkYzM3YWMxYzhiYmZlNmMyMDZmMTNmZDQ5YmU2MDMyMzFkZWVmMWNlYzViNGY3ODNkNjZhY2QxMGMwOTg4ZWVhNjhl*&quot;,{},{&quot;IscalledFrom&quot;:&quot;MajorClass&quot;,&quot;CurrentIndex&quot;:&quot;&quot;}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ClearClassandMinor,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTRlZjNhMjU0OWFkZGJhM2NjNWVhMDdlNjcwYjFhMjIxMTJjYmM3ODdlODkwNjc2NGNlMmE0MWY4MTllODVkNjExNjkyOGNhOGEyYWE4MzY0OGU2MDQwMDE5YmE3YzNlMzgyMmExYWRmMWY5YTZkYjhhMzZhZGFkYmU3YzgwYzc1*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;FLSummary&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmJiMTNlMzY1NDlhMzU1Y2NkOTlhZTdiOTQ0MmQ4Y2Q5YQ%3D%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]]]</value>
      <webElementGuid>3e5faea2-84ff-4691-989c-f3a9e0e06d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>calculateexpression</value>
      <webElementGuid>ea7425d2-42dd-4560-9e22-65284ba1b996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Class TypeFinancial LinesKidnap &amp; Ransom</value>
      <webElementGuid>9c4c9268-fd38-40cc-bc07-2a5be46c06b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eadeee9e&quot;)</value>
      <webElementGuid>1528689a-a412-46d3-9320-e0309e9e7abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>1829fb79-a533-4d79-8e57-9da30c84e1fd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
