<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownUWAuthority</name>
   <tag></tag>
   <elementGuidId>1be6c29e-fbe7-412a-8fc4-29ecdb97ad6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'pUWAuthorityOperator')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7740e6d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;UW Authority&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ab8bf69-afec-47f9-9bd0-d0b16878d0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>4c8d09e5-3879-4343-a865-914e9258c71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201610070553050950186780</value>
      <webElementGuid>ad956d26-23d3-4a5f-bd73-2a9e4383257d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>67e7fe5f-309e-4214-a7f7-34bb5d016fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7740e6d</value>
      <webElementGuid>344c1e12-857f-457e-8c7b-8d7a7e699d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pUWAuthorityOperator</value>
      <webElementGuid>53ce91b4-ced5-4f86-aabc-e2bd347f00d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05NjhiZDZkMTE5NmZkN2FmN2Y3Yzg2NTAyYzkwNDk0MzRiOTBmYjQ2NmJiNjY2ZDQ4YTQ5ODE2Y2NkYzNmMjk3YzAzNWFhZjEwMzQ1N2JkNDJmZWVlYmJhZGE0OGYzZDk4MjA1ZGI0ZjRkNzViNTE2Yzg3MGJlMTI1OThjODk5YmFkZDI1YjA4OTFkMTU3MDA4NTRkYjIwMThkYWY1ZmVkZGEyYzIxNjYzZDE5NDMyYzRlOTU0ZmNkNTRmYzMxZWU%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]]]</value>
      <webElementGuid>4c29e164-61d0-4895-a316-77174e026b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select UW AuthorityA.J. KritzmanAdam BohleAdam MaciaszkiewiczAdria VazquezAdriano BarkhordarAlan WrightAleksandra OsieczkoAlessandro GaianiAlex CasanovasAlexis FranksAna AlvesArnaud LapillonneAstrid MedinaBert Van WagenenBirgit RummelCameron WilliamsonCamila CortesCaretta HoppCassandra Lim Jen NieCesar Andres,VasquezChristie JonesCristina BrauDalmar Mohamed PikabeaDamien BarthezDaniel Alvarez BoixaderaDanielle BouchardDebora D'AllevaDominic BrookeDoris PajonEduard BlanxartElisa AltieriElisabeth HartlElisabetta RocchiEllie PottsElodie NourryEmanuele CavalleroEnzo AguileraEzechiel SymenouhFarhad DabestaniGerhard WeissGulsah DagdelenGuy EveringhamHanna MessingerHenk BakkerIrene PattarelloIzzy St Clair AlcockJake NormanJames UrquhartJasmine Van HeukelomJennifer BarreraJeremy LangJohn CsukaJonathan PfliegerJoscelin Erskine-ThomasJoseph CastelliJuan Manuel VelázquezJulia ÖttlJuliette MartínezJürgen BertlingKate LawrenceKotryna ZubkeviciuteLaura RomanLayla KhaddaouiLeo GradinaruLucas SartorelliLukas DollerMagdalena GmurMarco PompitaMargaret KingsleyMarlies JoustraMarta GrauMason CohenMathieu PeteauMaximilian LöwMaximilian PortzMeiyi SimMichael DillingerMichelle RosinMiguel Angel HernandezMorgan JonesMoritz KopkaNicolas PelletierNina Van OmmerenNinotchka ReyNisha GandhiOliver CloughOlivia PomannOmar IbrahimPaul RaynerPhilip HallPhilip JungPim Van Der DriftRenzo PeruzziRichard GiermannRoger Gordo BachRolando PaganoRonny KöhlerRoshan MenonRui WangRuth CalcenaSabrina BürgenerSandra FerreiraSarah BrownSarah TappendenSean CurtinSebastian GembergShane de BurcaShun KitagawaSigned off by ReinsurerSimon CalderbankStéphanie LandesSusan Schroeder BavieraThibaud HervyThomas BurkeTobias CalnanToby MoonVaishali VoraValentin WeihrauchValeria FerrariVanesa HerreroWilliam DowlingXavier MarguinaudXin Ying SeeYannis Lancre</value>
      <webElementGuid>5fe24164-63df-4758-a031-9f15718626de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7740e6d&quot;)</value>
      <webElementGuid>e49b5074-a870-4c92-8ebe-ab545429f8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>f6869f8a-716e-4a98-8db6-f46452f527b6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
