<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownBaseCurrencyCode</name>
   <tag></tag>
   <elementGuidId>574e9270-57e9-40bd-9a1b-5dfb235b6787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d8d7f774</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'BaseCurrencyCode')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Original Currency&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>594f283a-c2f5-4e5a-bc63-f520fa5e524e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>28bd206c-f5d9-4b45-b0b8-69e80edfa959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20161122060106049911402</value>
      <webElementGuid>98e92b15-f062-4663-88c6-0d5685400266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>d0b11edd-240e-4b00-88a4-281e5db81ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d8d7f774</value>
      <webElementGuid>f4b21999-da5d-49cd-ab8e-d82969d955ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pProposedQuotes$l1$pBaseCurrencyCode</value>
      <webElementGuid>9d8645ce-809a-49f8-8fb9-4e5979d7a959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>b0802412-e4a1-4bed-9778-cac35a2fb06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...EURGBPUSDAUDCHFNZDKRWCADPLNINRAEDAFNAllAMDANGAOAARSATSAWGAZNBAMBBDBDTBGNBHDBIFBMDBNDBOBBRLBSDBTNBWPBYRBZDCDFCFPCLFCLPCNYCOPCRCCSKCUPCVECYPCZKDEMDJFDKKDOPDZDECDECSECUEEKEGPERNESPETBFIMFJDFKPFRFGELGGPGHSGIPGMDGNFGTQGYDHKDHNLHRKHTGHUFIDRIEPILSIMPIQDIRRISKITLJEPJMDJODJPYKESKGSKHRKMFKPWKWDKYDKZTLAKLBPLKRLRDLSLLTLLVLLYDMADMDLMGAMKDMMKMNTMOPMROMTLMTPMURMVRMWKMXNMXPMYRMZNNADNBRNGNNIONLGNOKNPRNTDOMRPABPENPGKPHPPKRPTEPYGQARRONRSDRUBRURRWFSARSBDSCRSDGSDRSEKSGDSHPSITSLLSOSSPLSRDSTDSVCSYPSZLTHBTJSTMMTNDTopTRLTRYTTDTVDTWDTZSUAHUGXUYUUZSVBSVEBVEFVNDVUVWSTXAFXAGXAUXCDXDRXOFXPDXPFXPTYERZARZMKZWD</value>
      <webElementGuid>1fdef130-d6bc-49a5-966f-51ba27f4ce5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d8d7f774&quot;)</value>
      <webElementGuid>28bf4182-170e-40d1-a020-37399167ad78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>cfe86fcc-33be-40dc-a2b9-ec4d4d284517</webElementGuid>
   </webElementProperties>
</WebElementEntity>
