<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownUnderwriter0</name>
   <tag></tag>
   <elementGuidId>bfa4da19-c08b-44da-ad06-1766c2c6d81c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='$PDashBoardFilter$pUnderwriter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9db72001</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Underwriter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8aa6e4df-95ab-4207-8ddd-87c050d57143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>f832abad-9ede-4924-8e77-af35b1b9dc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201610070553050950186780</value>
      <webElementGuid>ef79b6e3-e154-47e7-a96c-3e32753b9a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>8e8654ca-2e3a-4547-932f-1677fa03229e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9db72001</value>
      <webElementGuid>de4fe1b5-5e99-4902-a456-455e587b58f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pUnderwriter</value>
      <webElementGuid>3920d04d-6a03-4047-89c8-6d51d73e811b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;DefaultMajorClassValue,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTQ4MWU0MTZkYjU1NjVlYmE0Yjg0MTE5YzA1ODQ2ZWU0ODRmMTViODg4OWQwOWY1OTg3OWU2NGUwOGZhOTIwYjg2MzU2MDY2MjU5NmUxM2ZkMzFhNGYyYzU1OTk3NWZmN2I1OWE0NjA5MjdlMGE0MDQxYTRiZTI3MzUwMzQ5ZTU3MWExYmM0NThkYzJhNDNhNzU1YzEzMjljYzZhNzhlZWZiNjQ1NzdkZjQxMjlhYWRhMzhiNTZiMjNkZmM4NGVmYjRhMGUzN2EyMTI3NTVjMTE0MGY1NDljZThiNzU5NDA0YmQwZTBkZWZlNjBmN2U3MDYxNmM0MzUxNmE3NjJmYTJiMmU0MDJmODUxMDJmZDBmZGE3ZGM3ZTdiNDJlNzdmOTg3YmVmMWM1NzMyMzg2NWVmNzg1NDc5YTZlMzdlN2QwNmM2NjM2YTQzOTk3NGYwNzBhOGRhZDY4ZmE3NzUwMTI2*&quot;,{},{&quot;IscalledFrom&quot;:&quot;Underwriter&quot;,&quot;CurrentIndex&quot;:&quot;&quot;}],&quot;pyWorkPage.SubmissionData&quot;]]]</value>
      <webElementGuid>15eb7864-4401-4fba-919f-3347f16de740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select UnderwriterA.J. KritzmanAdam BohleAdam MaciaszkiewiczAdria VazquezAdriano BarkhordarAlan WrightAleksandra OsieczkoAlessandro GaianiAlex CasanovasAlexis FranksAna AlvesArnaud LapillonneAstrid MedinaBirgit RummelCameron WilliamsonCamila CortesCaretta HoppCassandra Lim Jen NieCesar Andres,VasquezChristie JonesCristina BrauDalmar Mohamed PikabeaDamien BarthezDaniel Alvarez BoixaderaDebora D'AllevaDominic BrookeDoris PajonEduard BlanxartElisa AltieriElisabeth HartlElisabetta RocchiEllie PottsElodie NourryEmanuele CavalleroEnzo AguileraEzechiel SymenouhFarhad DabestaniGerhard WeissGulsah DagdelenGuy EveringhamHanna MessingerHenk BakkerIrene PattarelloIzzy St Clair AlcockJake NormanJames UrquhartJasmine Van HeukelomJohn CsukaJonathan PfliegerJoscelin Erskine-ThomasJoseph CastelliJuan Manuel VelázquezJulia ÖttlJuliette MartínezJürgen BertlingKate LawrenceLaura RomanLayla KhaddaouiLeo GradinaruLucas SartorelliLukas DollerMagdalena GmurMarco PompitaMarlies JoustraMason CohenMaximilian LöwMaximilian PortzMichael DillingerMichelle RosinMiguel Angel HernandezMorgan JonesMoritz KopkaNicolas PelletierNina Van OmmerenNinotchka ReyNisha GandhiOliver CloughOlivia PomannOmar IbrahimPaul RaynerPhilip HallPim Van Der DriftRenzo PeruzziRichard GiermannRoger Gordo BachRolando PaganoRonny KöhlerRoshan MenonRui WangRuth CalcenaSabrina BürgenerSandra FerreiraSarah BrownSarah TappendenSebastian GembergShane de BurcaShun KitagawaSimon CalderbankStéphanie LandesSusan Schroeder BavieraThomas BurkeTobias CalnanToby MoonVaishali VoraValentin WeihrauchValeria FerrariWilliam DowlingXavier MarguinaudXin Ying SeeYannis Lancre</value>
      <webElementGuid>b5e37aac-5b9a-487b-ba05-72667e68a9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9db72001&quot;)</value>
      <webElementGuid>16fb35c7-b2b3-4666-ac9d-353926f359ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>08ff4590-6a16-4769-9dcf-16dcdae0814f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
