<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownUnderwritingAssistant</name>
   <tag></tag>
   <elementGuidId>a293a234-6243-404b-af74-7c6319472885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'Assistant')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3f490b5e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Underwriting Assistant&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8118595a-4087-4447-89ea-42a0d7c7ee4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>6020cf5a-1dea-4efa-b182-2aec665042f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201610070553050950186780</value>
      <webElementGuid>da1412c3-881d-4c08-8f04-505b7e45cf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>2d076340-2f16-4550-a171-0083e897d46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3f490b5e</value>
      <webElementGuid>82b938c5-d45a-48c7-9175-299a38b6ce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pAssistant</value>
      <webElementGuid>e3eb1c51-2b33-46ab-804d-1001ffe49a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTQ4MWU0MTZkYjU1NjVlYmE0Yjg0MTE5YzA1ODQ2ZWU0ODRmMTViODg4OWQwOWY1OTg3OWU2NGUwOGZhOTIwYjg2YWMyZjVkNTg5Y2E0NjVhZTA0ODk2YWY3ZmEzMzE2OGY%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]]]</value>
      <webElementGuid>7150d2bd-f404-4b55-9e5e-fef93806afd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Underwriting AssistantAna Carolina AguilarAnna WróbelBelinda GostoliCaitlin JohnsCallum HarveyCeri BaileyClara BeauvilainCristina FongElba Bello LarruyEstelle MüllerFrances RadcliffeGemma CastroGethin ThomasIrina Adriana LascuJosep BayonaJosie DaviesKatarzyna LeszekKonstancja PreisnerLibelle VargasLuana NardocciLucia GantestiMariza OliveiraMelesa MartinNadia FranckPukky NaonanRebecca HowellsSandra SimonciniStacey RossTom EllisWilliam HaleyYlenia Biancini</value>
      <webElementGuid>3d69137d-159d-490e-a643-91251b35e582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3f490b5e&quot;)</value>
      <webElementGuid>be327631-6ee2-45c1-b4b3-ff7dd62b2af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>fc4fc4b9-314a-4487-806d-b64a3c980d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='3f490b5e']</value>
      <webElementGuid>9b7d72aa-795c-4f6f-9201-8db7b24c11f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div[2]/div/div/select</value>
      <webElementGuid>14cc888c-e4f5-49a0-9fdc-4cc1dd240eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwriting Assistant'])[1]/following::select[1]</value>
      <webElementGuid>2fd6e0c1-bbbe-4894-99e0-0f290222cd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwriter'])[1]/following::select[2]</value>
      <webElementGuid>640eaac9-378c-4865-8ae5-7caffa4ca6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producing Team'])[1]/preceding::select[1]</value>
      <webElementGuid>818de71e-f21e-47dd-be7d-21ae2e6d2939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submission Details'])[1]/preceding::select[2]</value>
      <webElementGuid>89b68cae-87a3-4448-aa38-e409e81e1676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/select</value>
      <webElementGuid>ee38c001-804b-44ab-bd9a-0d485dbb0ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '3f490b5e' and @name = '$PpyWorkPage$pSubmissionData$pAssistant' and (text() = 'Select Underwriting AssistantAna Carolina AguilarAnna WróbelBelinda GostoliCaitlin JohnsCallum HarveyCeri BaileyClara BeauvilainCristina FongElba Bello LarruyEstelle MüllerFrances RadcliffeGemma CastroGethin ThomasIrina Adriana LascuJosep BayonaJosie DaviesKatarzyna LeszekKonstancja PreisnerLibelle VargasLuana NardocciLucia GantestiMariza OliveiraMelesa MartinNadia FranckPukky NaonanRebecca HowellsSandra SimonciniStacey RossTom EllisWilliam HaleyYlenia Biancini' or . = 'Select Underwriting AssistantAna Carolina AguilarAnna WróbelBelinda GostoliCaitlin JohnsCallum HarveyCeri BaileyClara BeauvilainCristina FongElba Bello LarruyEstelle MüllerFrances RadcliffeGemma CastroGethin ThomasIrina Adriana LascuJosep BayonaJosie DaviesKatarzyna LeszekKonstancja PreisnerLibelle VargasLuana NardocciLucia GantestiMariza OliveiraMelesa MartinNadia FranckPukky NaonanRebecca HowellsSandra SimonciniStacey RossTom EllisWilliam HaleyYlenia Biancini')]</value>
      <webElementGuid>9277aefb-9084-4c62-a9f6-d731e6447aec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
