<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownTerritorialScope</name>
   <tag></tag>
   <elementGuidId>36b3f6f9-cd86-4d09-8553-d5cba8f99a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name, '$pTerritorialScope')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#66654b21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01807230639270745552&quot;] [data-test-id=&quot;\32 01610070553050952188346&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>610c88bd-84fc-48c1-bd9d-2948aebfa4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>a65f5681-b025-42b5-ac98-1f4ad7e843a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201610070553050952188346</value>
      <webElementGuid>d2be2437-b768-46c8-a647-67642ea2fd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>2b20c9f3-f568-4268-9291-10c62c0f3c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>66654b21</value>
      <webElementGuid>e311bc10-150d-48be-80cb-ee6f21411690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pProducingTeam</value>
      <webElementGuid>f3c6bae7-27fe-4049-b631-af802d44b3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetSkipQuoteFlag,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTQ4MWU0MTZkYjU1NjVlYmE0Yjg0MTE5YzA1ODQ2ZWU0ODRmMTViODg4OWQwOWY1OTg3OWU2NGUwOGZhOTIwYjg2MzU2MDY2MjU5NmUxM2ZkMzFhNGYyYzU1OTk3NWZmN2I5ZDJmYzg4ZmI2ODcxMzFkYzQ5ZTAxMjlhOGViYzliM2UyZTFhNWJiZWYzNDlmNmNlYWE1ZWYwOWUxMjdhMDA0*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetInfoForSMEMunich,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTQ4MWU0MTZkYjU1NjVlYmE0Yjg0MTE5YzA1ODQ2ZWU0ODRmMTViODg4OWQwOWY1OTg3OWU2NGUwOGZhOTIwYjg2MzU2MDY2MjU5NmUxM2ZkMzFhNGYyYzU1OTk3NWZmN2JhNjVmZTJlNjE0YmE5MWMwOGIzYTgzZDZkZjg3MTFkZGVmZjljZjQxNjI4Y2Y2OThjNGM3YmYyNzk5OTJhMWNh*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]]]</value>
      <webElementGuid>4030ae31-e5c9-43b2-ae8c-6dc76f424245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Producing TeamFL - Asia &amp; Middle EastFL - Barcelona - CyberFL - London - CDOFL - London - FIFL- Barcelona - Southern Europe</value>
      <webElementGuid>50269e3b-8f43-44b7-8964-3b1924def428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;66654b21&quot;)</value>
      <webElementGuid>a614144b-4625-4a5e-8713-5620e3f9a79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>40527854-7c5e-49de-a4c6-e80d3ad35d79</webElementGuid>
   </webElementProperties>
</WebElementEntity>
