<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget2Ifr</name>
   <tag></tag>
   <elementGuidId>cf6e00c2-c77a-4327-a6b6-b52746c993de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PegaGadget2Ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='PegaGadget2Ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;PegaGadget2Ifr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f88403fe-5270-4a78-a2cb-8c31597d3b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
      <webElementGuid>773e2a96-20d3-45ef-9fcd-5d2290ed4686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *;</value>
      <webElementGuid>5003efc4-0c58-44bd-a9ea-e0777190ad79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
      <webElementGuid>a72c6ee6-3bfa-468d-9e5d-44b1a5854979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78770b4f-cf10-4db2-9f57-d010f45dcaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>03798736-5b31-494d-b618-2ac9aa22a8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prweb/app/LiabilityLines_/AQrj2LB4NQCKaV10lflPLOnOAP4olJWCG1vcOaRKU9iAwaE8P9peJQ*/!TABTHREAD2?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=b439bd93-74c0-e170-d1f9-cc85056c4489&amp;tabIndex=3&amp;prevContentID=c07cd4b3-c5cd-c000-f81c-dd4c2fcfa7a4&amp;prevRecordkey=2T&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HIDDBCFAE7F947B812F65F135AA122D5A5E</value>
      <webElementGuid>32ffb059-3d5e-4a8b-85ac-e2c1888230ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>37b6f2fd-d368-4ef9-a9db-f08118603022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget2Ifr&quot;)</value>
      <webElementGuid>86c750ac-c627-4f93-8141-c68b8416d3b3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
