<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_InsuredTaskLink</name>
   <tag></tag>
   <elementGuidId>9119fa5f-403f-4e6c-a13e-161dcf7d6cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@name,'Insured')  and contains(@href, '#')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;CustomerSearchBusinessGrid_D_InsuredList_pa2361217707745747pz.pxResults(1)_34&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0141230004908018332205&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a783852c-8786-44d0-a283-450cbfef4ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20141230004908018332205</value>
      <webElementGuid>b80e5e1b-563a-476d-82f3-c0813f90e62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7efd4945-61ac-4f3f-818c-b6d8e288ac97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>3863dcc3-cd87-4f13-8f9d-c1a2a4ecd9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>23263f15-ae9c-4595-b140-535b9912b9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerSearchBusinessGrid_D_InsuredList_pa2361217707745747pz.pxResults(1)_34</value>
      <webElementGuid>76718cb4-0bb2-4d2f-8e34-7d2fdfc03aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runActivity&quot;, [&quot;&quot;, &quot;OwnerId=#~D_InsuredList_pa2361217707745747pz.pxResults(1).BusinessUnitId~#&quot;, &quot;&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05YTUyZDA1ZWRlYjM3YTIwODc3ZTQxYzQxNTVhMDgzYTM3Yjk1NWEzMzYzOTE1NjQ3MzEzOTNmNmM3ZGUxNzQ4MDIyOTAwZWJhYTU0ZTljOWJhZjY1N2QyMWJkMDhlMmE5YmI3ZjVhMjY0ZDM5Mzk0NDIyY2JiYzgxYjFlY2NhMGJiMjJjY2Q3NGFjNDM5MzNmNjhjNmRjNjlkYzI3YWI4MGUwOWU0YmZjYTJhZjI3ZDJkNmE2MzYzNWIyY2RhYjE1MzEzMmUzMjI2MGFjMzdhOTcwY2NiYTVjMDFkOTcxMWNjMWJhZmNkYTUwNWJmNTNiMDc0N2Y1NjYxMjZiYWJiYjVlYzBkYTgxMjUwNDI5OWM1NDRjZGMzMTgwMDJkNTE1NjQwODY3MDdhMzNiYTI4ODgzZGU0MDM4MWVkODQ0YmRmMjE3ZDdiMTIyYjhhMTllMTE0MTlkYTAwNjI0ODc3*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1hODRlMzQwMjJhNjAyOWJiYjRkYWYyY2U4Y2Q1MjVmYjk5NWU5ZWRjNWE5ZjI5MjBiNDdmMzM3YzI5NjIxZjMxOTZlOWVkNDMxMDlkY2NlNWM3ZWYyNjhjMTdjODkwYjA2YjY4OWNhMTcwYmFmM2U2NDUzOTMzYjgzYzMzMWE5YjQ3NTEzMTE5YTkxNjI3MDk4NzU1YzkxMWUyOTgxNDcwOGU3MzA0MmMzOGE2ZTMwYmMzZWFmMTBkM2Y1M2E4Nzk%3D*&quot;,{},{}],&quot;&quot;]],[&quot;openAssignment&quot;,[&quot;#~TempAccount.ContactId~#&quot;,&quot;81ed642e-f0a5-4f38-8130-3e75eb85c83c&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;#~D_InsuredList_pa2361217707745747pz.pxResults(1).pyIsOfflineEnabled~#&quot;,{&quot;pyReloadAlways&quot;:&quot;&quot;}]]]</value>
      <webElementGuid>30f6ae81-6eb0-484c-9048-d3bf609b4074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BUNIT-81991</value>
      <webElementGuid>f559d6d1-705d-4305-a9e9-da2026368306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PD_InsuredList_pa2361217707745747pz$ppxResults$l1&quot;)/td[@class=&quot;gridCell  wrapText&quot;]/div[@class=&quot;oflowDivM&quot;]/span[1]/a[1]</value>
      <webElementGuid>8714ae6f-d92a-41c0-a066-97d588466d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PartyManagement/Page_CreateNewInsured/iframe_PegaGadget0Ifr</value>
      <webElementGuid>356c0258-47c3-447c-8701-98bb159eb8a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='CustomerSearchBusinessGrid_D_InsuredList_pa2361217707745747pz.pxResults(1)_34']</value>
      <webElementGuid>a4c279a8-6458-4150-b0fd-1db31938a36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BUNIT-81991')]</value>
      <webElementGuid>a95e6337-8388-410a-b32f-727cee32db4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autokjhgffghj'])[1]/following::a[1]</value>
      <webElementGuid>4cb613aa-0053-4f80-aebd-9d865e02e12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[9]/following::a[1]</value>
      <webElementGuid>7991e081-518d-4483-be7e-5665bd590b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::a[1]</value>
      <webElementGuid>91d1cc4b-e3f7-42e5-b00f-ce7467433000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If Insured is not found, you can create a new Insured'])[1]/preceding::a[1]</value>
      <webElementGuid>500de245-8fc3-4d8b-ade9-dd7dda9312f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BUNIT-81991']/parent::*</value>
      <webElementGuid>e1a59748-64d5-4410-bfb0-fc57e07681d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>3c2fef97-9edf-4b80-a2b3-04da5496c314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'CustomerSearchBusinessGrid_D_InsuredList_pa2361217707745747pz.pxResults(1)_34' and (text() = 'BUNIT-81991' or . = 'BUNIT-81991')]</value>
      <webElementGuid>e63cfe7d-d572-4a0e-a384-cc30306c29dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ec509b20-6f06-4055-a55a-7dde2ef71c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PD_InsuredList_pa2361217707745747pz$ppxResults$l1']/td[2]/div/span/a</value>
      <webElementGuid>a12f7313-8600-4821-98a2-e882ed545323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
