<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter to sort_pui_filter</name>
   <tag></tag>
   <elementGuidId>f0940b25-3982-46a7-8b5e-4406eaa95390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='pui_filter'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=columnheader[name=&quot;Activity Name* Click to sort Click to filter&quot;i] >> internal:label=&quot;Click to filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c973660d-e202-43f7-9f7f-9327b447a0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pui_filter</value>
      <webElementGuid>2ea83f60-a992-44a1-bb64-3a80186cdf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6aa219a6-40ee-42a3-87ac-59c9e9968baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to filter</value>
      <webElementGuid>208684aa-fec6-4b71-8b64-daeff3bd8bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Click to filter</value>
      <webElementGuid>57fa5701-cf25-4cdc-90ed-33fea2c4a9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>894ad3c6-0400-47ad-818e-e8b75d3a267d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter highlight-ele</value>
      <webElementGuid>78131ca5-6257-461f-9623-d7ded058ccf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filtertype</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d5e7a92a-63d2-48ed-bb86-1cfc0c2d9856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyTbl_right&quot;)/tbody[1]/tr[@class=&quot;cellCont&quot;]/th[@id=&quot;a1&quot;]/div[@class=&quot;oflowDiv&quot;]/span[1]/a[@id=&quot;pui_filter&quot;]</value>
      <webElementGuid>3ec32a60-9e3e-4ff5-8206-0d081d27166c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Renewal_Filters/iframe_Security guide not configured_PegaGadget0Ifr</value>
      <webElementGuid>62df7ea6-e778-459c-b4b4-8a2456f6297f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='pui_filter'])[2]</value>
      <webElementGuid>00d3f97b-55b7-448d-be20-761dbac76636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//th[@id='a1']/div/span/a)[2]</value>
      <webElementGuid>008f47b5-d815-4a17-827a-799e67a8ef1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/div/span/a</value>
      <webElementGuid>84754d3f-958a-4808-8e34-997d1d4f321f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pui_filter' and @title = 'Click to filter']</value>
      <webElementGuid>7bd1836d-c285-4713-b9b2-bd01f2a619b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
