<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ExpandItems_Frame2</name>
   <tag></tag>
   <elementGuidId>330fb835-21d9-4a22-97b8-d8b683adf862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='layout-group-tablist-menu']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.textIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Currently open&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c33ed126-1695-4f49-856e-5b1056f42d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textIn</value>
      <webElementGuid>c7ce969c-2a2f-432c-b075-f411bfa40fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>5c76ea27-6052-44fb-a163-377c5e43347a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_TABBED0&quot;)/div[@class=&quot;scrlCntr&quot;]/ol[@class=&quot;yui-nav tsb-menu tab-ul tab-ul-t tab-ul-t-ns  headerTabsList&quot;]/li[@class=&quot;tab-li tab-li-t tab-li-t-ns&quot;]/a[@id=&quot;TABANCHOR&quot;]/span[@id=&quot;TABSPAN&quot;]/span[@class=&quot;textMiddle&quot;]/span[@class=&quot;textIn&quot;]</value>
      <webElementGuid>431953d2-3801-4b34-b598-3edfcb21db6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget2Ifr</value>
      <webElementGuid>cb99b9e4-ec89-4363-9c15-4aa7850a4c0e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
