<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ExpandItems_Frame1</name>
   <tag></tag>
   <elementGuidId>c7e01b43-7e31-4742-b170-b7a0f05825ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.textIn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='layout-group-tablist-menu']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Currently open&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2824199f-1699-4cad-beaf-f05d629da4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textIn</value>
      <webElementGuid>8c9ec906-2eef-4b6d-84e0-da76923e7e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>340b47ac-4cd7-4186-8c43-e3efb6674b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_TABBED0&quot;)/div[@class=&quot;scrlCntr&quot;]/ol[@class=&quot;yui-nav tsb-menu tab-ul tab-ul-t tab-ul-t-ns  headerTabsList&quot;]/li[@class=&quot;tab-li tab-li-t tab-li-t-ns&quot;]/a[@id=&quot;TABANCHOR&quot;]/span[@id=&quot;TABSPAN&quot;]/span[@class=&quot;textMiddle&quot;]/span[@class=&quot;textIn&quot;]</value>
      <webElementGuid>9d86a571-4645-4df1-8213-5d433da8da9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Renewal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>041cd59b-d9f4-4346-92a3-d071c2c946d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='TABSPAN']/span/span</value>
      <webElementGuid>d4b463fb-8301-46e2-8cfc-be72005f7089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance'])[1]/following::span[4]</value>
      <webElementGuid>ff0a7f17-0fcc-417b-b186-9e8225287aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placing Type :'])[1]/following::span[5]</value>
      <webElementGuid>f9e72725-a72e-4537-9ceb-e79c403e5de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::span[1]</value>
      <webElementGuid>f422fbf5-486b-45cc-8d27-866236d84f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insured'])[1]/preceding::span[5]</value>
      <webElementGuid>6e16844c-1036-491d-b214-73b87a0191e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='▼']/parent::*</value>
      <webElementGuid>67818786-374b-414f-aec3-63f55a821363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>82652c0f-3455-4c1e-bd03-946656701c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '▼' or . = '▼')]</value>
      <webElementGuid>65ee07c1-0288-4ff0-b3cb-9047f437a73b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
