<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FeePercentage</name>
   <tag></tag>
   <elementGuidId>154f881c-e9b2-49e8-a9e4-67797ce7b603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#70759ac4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'pFeePercentage')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02207290744560978370-R2-L1R1&quot;] [data-test-id=&quot;\32 0170118134923024429622&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c9216e5-d371-4a83-b0b2-b72cb0948c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170118134923024429622</value>
      <webElementGuid>ae0b71ee-39ba-4040-a346-eff20587a8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>b8674bab-e0e5-4fe3-87e8-956101001de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>70759ac4</value>
      <webElementGuid>3744515d-297b-47f1-bd4d-64199b701975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b950274b-7928-45a6-b69c-0621f2b62fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-formatting</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>2021f7d5-cdfe-465f-90e9-06351d81a8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>isvalidpercentage,decimal</value>
      <webElementGuid>e90e09dc-14ee-4323-a222-5dbd53590038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>cd79d560-1395-4bd9-9507-bc0e81a0b270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pProposedQuotes$l2$pAcquisitionFees$l1$pFeePercentage</value>
      <webElementGuid>134ab1fa-3fda-44c4-a064-d9cd7c789c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightJustifyStyle</value>
      <webElementGuid>d4ab5ac1-84a8-4a8f-8901-c644f29b1957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CalculateFeeDetails,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1lNzc0Nzk4NTQ2NmQwMDg2NDhmNWViNmE0M2UyMzI0Zjc3NmRkZTk4NGE1ODI0MDc3OTYwYzRkMWNjNDgwNjQzZTU0MGRkNWVkNzgyYmE0ZTEwNDdmNjA0ZGEyZGUzNjA4MDM0ZmNkMWUzMDk4MDIyMzY5YjQ3NzJiODczZmQwMTI3OGZmMzAyMDc5ZjZkMDgzZWE5ZDYyZjQwOTg4YWU3MGU1Y2QwNGZiNmVmYzVmM2Q5MDNlZWRkNjJkZDVkNGY1MDdkZGEzMzk4NGE1NWFkZmNmY2U4OWY1OWE3NzAxY2ZlYjFlZDI4YTMwNTMzMTkwZTVkMzU3NmU0NzkwMzlmMmRiZjc2NTMzNzkwN2VlY2IwMDk0NzRhY2MyZTdjNzFlYjg4ZTFhYmMzYmZkNDBkMmE5NDc5YmUyMmIwOTg4YjI4NDAxYTg4M2Q2NGM3OTgzNThkMmE5ODk1NzA3MDU0NTAxZTE4Y2VmOTc0YzFlNzE4ZGMzMTA5NDQ5Zjg0NTAxZjRiZDlmZTU5OWFiMzM0YjBmMTliNjlmYjczMjdmYTVkZGMzNzUxODg0MzA4N2RlMTRlMjhhNGI4OGFmMTBjYTkxMjA3ODMxM2RiOTYyNzQ2OTdmNWM1YmU3ODUwNDI%3D*&quot;,{},{&quot;IsCalledFromFeePercent&quot;:&quot;true&quot;,&quot;IsCalledFromFeeAmount&quot;:&quot;&quot;}],&quot;&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ReCalculatePolicyVATAmount,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1lNzc0Nzk4NTQ2NmQwMDg2NDhmNWViNmE0M2UyMzI0Zjc3NmRkZTk4NGE1ODI0MDc3OTYwYzRkMWNjNDgwNjQzZTU0MGRkNWVkNzgyYmE0ZTEwNDdmNjA0ZGEyZGUzNjA4MDM0ZmNkMWUzMDk4MDIyMzY5YjQ3NzJiODczZmQwMTI3OGZmMzAyMDc5ZjZkMDgzZWE5ZDYyZjQwOTg4YWU3MGU1Y2QwNGZiNmVmYzVmM2Q5MDNlZWRkNjJkZDVkNGYyMTU5Mjk4YWQyODcwNDg3ZGVjMWIwZWVkYjY5OTNhMmI2NzEwM2YzNGU5NWRjZjFlOTc4YTBhOWJlYWM2MzM0*&quot;,{},{}],&quot;&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;PremiumInformation&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CalculatePremiumDetails,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1lNzc0Nzk4NTQ2NmQwMDg2NDhmNWViNmE0M2UyMzI0Zjc3NmRkZTk4NGE1ODI0MDc3OTYwYzRkMWNjNDgwNjQzZTU0MGRkNWVkNzgyYmE0ZTEwNDdmNjA0ZGEyZGUzNjA0NGUzYmNhNWZkZTkzYjdlZTQ5MTJkMDU4ZDczZmU4YmQ2YmU3ZmNlMjBjZDNjYzJjM2JiNTg2NTQ2MDc5YjlmYzU4OTQxZTM5MGVjZDBiMTgxOWJhMDVhMDM1Y2JmN2ZmMThiNmI3NGFiZjY2MmRhMjZhYjBjOWJmODRjZjQ2MTlhNjA5ZGY1MTU0ZTNjNGEwM2IxNzFjMmZmMmZlOWQ5OWNjN2FiYmJiMDg3ZjU5MTg5NzU1MWMzZmE3MTljOWE3NGY2ZWE1OGVjYjUzMjlkMjlhMmIwMzMwMGFkNWVhZTNlODI2NTUwZjcwOWIwNjkwNDgyNDcyYzUwYTI3NGEyOGViMmExNWQ4MzIzOGI0M2ViZTVhMDcyOGFhODE0N2NkOTI1NmRkMDJlM2UwMzhkMjUyNWVhNTQ1NGFkMDgxNDljZWRlZjMzMjU0MWVhNDg1NDMzYWY3OWVkOGJkNTM1MWExMGE1NThmYjIxOTg3ZTU2ZDEzZTI5YjljNmE3OWRlMWI2MTMwNjdiMGMyNTRjZTZlOThhNWVmOThlM2Q4YzcyMDc0YzFkMjAwMDYzZDRjZjk1ZGY0MGVkZjlhZmU3M2U0ZjU0ZTcwMDVkZjMxY2RlYTJhZjMzODE1Nzk2M2U%3D*&quot;,{},{&quot;IsCalledFromNetPremium&quot;:&quot;&quot;,&quot;IsCalledFromGrossPremium&quot;:&quot;true&quot;,&quot;IsPropertyHasError&quot;:&quot;&quot;,&quot;TotalFeePercent&quot;:&quot;&quot;}],&quot;&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;PremiumInformationE&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CalculatePremiumDetails,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1lNzc0Nzk4NTQ2NmQwMDg2NDhmNWViNmE0M2UyMzI0Zjc3NmRkZTk4NGE1ODI0MDc3OTYwYzRkMWNjNDgwNjQzZTU0MGRkNWVkNzgyYmE0ZTEwNDdmNjA0ZGEyZGUzNjA0NGUzYmNhNWZkZTkzYjdlZTQ5MTJkMDU4ZDczZmU4YmQ2YmU3ZmNlMjBjZDNjYzJjM2JiNTg2NTQ2MDc5YjlmYzU4OTQxZTM5MGVjZDBiMTgxOWJhMDVhMDM1Y2JmN2ZmMThiNmI3NGFiZjY2MmRhMjZhYjBjOWJmODRjZjQ2MTlhNjA5ZGY1MTU0ZTNjNGEwM2IxNzFjMmZmMmZlOWQ5OWNjN2FiYmJiMDg3ZjU5MTg5NzU1MWMzZmE3MTljOWE3NGY2ZWE1OGVjYjUzMjlkMjlhMmIwMzMwMGFkNWVhZTNlODI2NTUwZjcwOWIwNjkwNDgyNDcyYzUwYTI3NGEyOGViMmExNWQ4MzIzOGI0M2ViZTVhMDcyOGFhODE0N2NkOTI1NmRkMDJlM2UwMzhkMjUyNWVhNTQ1NGFkMDgxNDljZWRlZjMzMjU0MWVhNDg1NDMzYWY3OWVkOGJkNTM1MWExMGE1NThmYjIxOTg3ZTU2ZDEzZTI5YjljNmE3OWRlMWI2MTMwNjdiMGMyNTRjZTZlOThhNWVmOThlM2Q4YzcyMDc0YzFkMjAwMDYzZDRjZjk1ZGY0MGVkZjlhZmU3M2U0ZjU0ZTcwMDVkZjMxY2RlYTJhZjMzODE1Nzk2M2U%3D*&quot;,{},{&quot;IsCalledFromNetPremium&quot;:&quot;&quot;,&quot;IsCalledFromGrossPremium&quot;:&quot;true&quot;,&quot;IsPropertyHasError&quot;:&quot;&quot;,&quot;TotalFeePercent&quot;:&quot;&quot;}],&quot;&quot;]]]</value>
      <webElementGuid>e69930a3-a5ad-4193-b99f-aaa790bda1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>603c5116-f6fb-40d4-abe8-6a0ebd18dadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;70759ac4&quot;)</value>
      <webElementGuid>4b6b7319-cc15-498d-a0bc-7cfa6ae1c5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Endorsements/iframe_PegaGadget2Ifr</value>
      <webElementGuid>a5fd1314-ce49-49f3-ad74-4a515f97192c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
