<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ListOfEndorsementVersionTableHeaders1</name>
   <tag></tag>
   <elementGuidId>781cce35-043a-4c7a-9442-ee8f40610621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[contains(@pl_prop,'EndorsementVersions')]//tbody//tr//th[@role='columnheader']//following-sibling::div[contains(@class,'cellIn')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
