<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget1Ifr</name>
   <tag></tag>
   <elementGuidId>f9053436-6d8c-4c27-9cf4-33cdbe02d177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='PegaGadget1Ifr']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'PegaGadget1Ifr' and @id = 'PegaGadget1Ifr' and @src = '/prweb/app/LiabilityLines/AQrj2LB4NQAOPtP9hXno2IIlYboujm6E8dIQk5abRysA6jNpGpr450806NH2tyh9*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=623b052b-bba2-3ac8-bea7-4f172d7b4112&amp;tabIndex=2&amp;prevContentID=88d0292e-17d9-4ddd-9c1a-7e474fd0068c&amp;prevRecordkey=Data-Portal%7CSearchSubmission%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HID2A89046096091A936B8342223F8F2A14' and @title = 'New']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PegaGadget1Ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;PegaGadget1Ifr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c74242a9-2396-44da-937a-8015dad08ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
      <webElementGuid>68a4ae9c-5531-41f5-a96e-5f74b0c89a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *;</value>
      <webElementGuid>6a454122-536a-4d0f-8287-40ae7f5585e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
      <webElementGuid>e05b0df5-59ed-4122-85bd-d9e8159de1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1652727d-b198-4efe-b0a9-981445f71ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2a473faa-e917-4ba0-b15d-cbf3a860d176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prweb/app/LiabilityLines/AQrj2LB4NQAOPtP9hXno2IIlYboujm6E8dIQk5abRysA6jNpGpr450806NH2tyh9*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=623b052b-bba2-3ac8-bea7-4f172d7b4112&amp;tabIndex=2&amp;prevContentID=88d0292e-17d9-4ddd-9c1a-7e474fd0068c&amp;prevRecordkey=Data-Portal%7CSearchSubmission%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HID2A89046096091A936B8342223F8F2A14</value>
      <webElementGuid>7a403c05-9ccf-44cb-9447-5b0a73bbdf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>62e0060a-3d43-4c9b-9d98-94c1a24ec889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget1Ifr&quot;)</value>
      <webElementGuid>c8284fc7-6864-4cf9-8859-c99886daf577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='PegaGadget1Ifr']</value>
      <webElementGuid>808c69a3-4045-4df8-9693-2aead594db1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PegaWebGadget1']/iframe</value>
      <webElementGuid>3f926a03-702b-4e7b-aae7-af09598c5479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/iframe</value>
      <webElementGuid>b4f59cd9-4aed-4e10-95e6-2e7d3cd25b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'PegaGadget1Ifr' and @id = 'PegaGadget1Ifr' and @src = '/prweb/app/LiabilityLines/AQrj2LB4NQAOPtP9hXno2IIlYboujm6E8dIQk5abRysA6jNpGpr450806NH2tyh9*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=623b052b-bba2-3ac8-bea7-4f172d7b4112&amp;tabIndex=2&amp;prevContentID=88d0292e-17d9-4ddd-9c1a-7e474fd0068c&amp;prevRecordkey=Data-Portal%7CSearchSubmission%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HID2A89046096091A936B8342223F8F2A14' and @title = 'New']</value>
      <webElementGuid>aa3b1edd-b187-411b-8bcf-46213b764546</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
