<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget0Ifr</name>
   <tag></tag>
   <elementGuidId>a498d617-7ee7-4a77-b548-40ceb7bd79d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='PegaGadget0Ifr']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'PegaGadget1Ifr' and @id = 'PegaGadget1Ifr' and @src = '/prweb/app/LiabilityLines/AQrj2LB4NQAOPtP9hXno2IIlYboujm6E8dIQk5abRysA6jNpGpr450806NH2tyh9*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=623b052b-bba2-3ac8-bea7-4f172d7b4112&amp;tabIndex=2&amp;prevContentID=88d0292e-17d9-4ddd-9c1a-7e474fd0068c&amp;prevRecordkey=Data-Portal%7CSearchSubmission%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HID2A89046096091A936B8342223F8F2A14' and @title = 'New']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PegaGadget1Ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;PegaGadget1Ifr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c8161d8b-9b1f-4ca7-afc7-12896e68f0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
      <webElementGuid>d94453b4-0445-44de-9c21-aab9b7a17337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *;</value>
      <webElementGuid>b908f59c-b40f-4fa0-85cd-4bca381babce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
      <webElementGuid>2849c30f-cedd-403e-9791-f0e8dd581ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d7b6bf34-1f19-4e10-bb60-cabbd14567e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f0a42031-0c5b-4c76-9747-63b5a1099ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prweb/app/LiabilityLines/AQrj2LB4NQAOPtP9hXno2IIlYboujm6E8dIQk5abRysA6jNpGpr450806NH2tyh9*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=623b052b-bba2-3ac8-bea7-4f172d7b4112&amp;tabIndex=2&amp;prevContentID=88d0292e-17d9-4ddd-9c1a-7e474fd0068c&amp;prevRecordkey=Data-Portal%7CSearchSubmission%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HID2A89046096091A936B8342223F8F2A14</value>
      <webElementGuid>a9e803fa-3f91-4b7e-bb82-546bebe083c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>77828f29-4c8f-49c4-9316-abbb4abd32a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget1Ifr&quot;)</value>
      <webElementGuid>062c0295-3145-4708-9117-df932801d4d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='PegaGadget1Ifr']</value>
      <webElementGuid>164b3452-8a5c-4db7-9a1f-cfbb71a83389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PegaWebGadget1']/iframe</value>
      <webElementGuid>46b82afb-7dcb-4db8-a8ce-8fe036d1bd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/iframe</value>
      <webElementGuid>8407d0fc-771f-47a8-87ed-a895fdd8750c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'PegaGadget1Ifr' and @id = 'PegaGadget1Ifr' and @src = '/prweb/app/LiabilityLines/AQrj2LB4NQAOPtP9hXno2IIlYboujm6E8dIQk5abRysA6jNpGpr450806NH2tyh9*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=623b052b-bba2-3ac8-bea7-4f172d7b4112&amp;tabIndex=2&amp;prevContentID=88d0292e-17d9-4ddd-9c1a-7e474fd0068c&amp;prevRecordkey=Data-Portal%7CSearchSubmission%7Cundefined&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HID2A89046096091A936B8342223F8F2A14' and @title = 'New']</value>
      <webElementGuid>97bf5ef4-0a52-452e-96b5-f561617d3b4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
