<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_RecordsLink</name>
   <tag></tag>
   <elementGuidId>22b20b51-742e-49e0-a6db-d612c0a78b6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;WorksheetResults_D_WorksheetCases_pa2303013188457548pz.pxResults(1)_51&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@aria-label='Records']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0211223114632005763-R1&quot;] [data-test-id=&quot;\32 016072109335505834280&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca14961a-5504-4e4e-b2e9-ae6569efaa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2016072109335505834280</value>
      <webElementGuid>f5a5fa50-7949-42ef-80a8-96f2cf50bedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>09aa8eba-a6bf-44b4-a83f-85c1117143b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>84ff0319-1029-4db6-bfca-b928553a341b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>ceaea2b8-4ae5-48b4-9689-56c52828971c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WorksheetResults_D_WorksheetCases_pa2303013188457548pz.pxResults(1)_51</value>
      <webElementGuid>c5a26907-99da-423f-b8c9-39fa94809ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;]],[&quot;openWorkItem&quot;,[&quot;#~D_WorksheetCases_pa2303013188457548pz.pxResults(1).pyID~#&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,{&quot;pySkipConflictCheck&quot;:&quot;false&quot;,&quot;pyReloadAlways&quot;:&quot;false&quot;,&quot;target&quot;:&quot;primary&quot;}]]]</value>
      <webElementGuid>bbc30e22-de14-4515-a7f0-068565515c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>W-3925</value>
      <webElementGuid>af3db97d-6186-4286-90cc-2557761c0d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PD_WorksheetCases_pa2303013188457548pz$ppxResults$l1&quot;)/td[@class=&quot;gridCell    gridCellSelected&quot;]/div[@class=&quot;oflowDiv&quot;]/div[@class=&quot;divCont&quot;]/div[@class=&quot;cellIn&quot;]/span[1]/a[1]</value>
      <webElementGuid>796337f2-2aae-4a73-af23-433865d3c02d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
