<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ActivityNameFilter</name>
   <tag></tag>
   <elementGuidId>b32c0d7b-2140-4f05-975d-73d3d4635cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a8 > div.oflowDiv > span > #pui_filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@data-attribute-name='Activity Name*']//span//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=columnheader[name=&quot;Policy Reference Click to sort Click to filter&quot;i] >> internal:label=&quot;Click to filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10a64efb-5007-45ee-9971-844e1e3ebe7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pui_filter</value>
      <webElementGuid>208044ce-7f96-4b36-857e-2df7a9cab304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6c9e08e3-4431-41e6-8281-e6521d96a26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to filter</value>
      <webElementGuid>e898390f-2c05-4434-8af2-77adee87560c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Click to filter</value>
      <webElementGuid>636d9347-cc2a-454c-b68f-9fde6705fce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>aa7890c6-69af-4664-bd7b-09c1106d0b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter highlight-ele</value>
      <webElementGuid>abce8d71-4773-446a-baa8-6fe66c718dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filtertype</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>62c318c5-dd64-4bbe-aacf-cecaf33db212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a8&quot;)/div[@class=&quot;oflowDiv&quot;]/span[1]/a[@id=&quot;pui_filter&quot;]</value>
      <webElementGuid>87f52e44-b636-4d4d-bd72-70d473b11344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>a2f55c31-48b2-42d7-ac83-5f1a18b7e6a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='pui_filter'])[3]</value>
      <webElementGuid>4006ba5e-963d-4b55-be61-3a2fa65da579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Click to filter']</value>
      <webElementGuid>12aeb097-6eb7-4fe9-8531-5b1c9da97aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]/div/span/a</value>
      <webElementGuid>5b72679a-3249-487a-b614-56c5c883d8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='a8']/div/span/a</value>
      <webElementGuid>ac2bf53c-d1f8-4553-97b1-f8511bde24b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
