<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linkClear</name>
   <tag></tag>
   <elementGuidId>7afc413d-271b-47bd-9889-f6bae5f4e382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clearFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Clear Filter')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Clear Filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87c1ba39-f95c-4f3f-bfb1-c4a05a8826f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clearFilter</value>
      <webElementGuid>495e0d77-7254-4af8-a976-35aaf67a512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a16f0ea1-8fd8-4382-bc47-23514349c530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter to clear filter</value>
      <webElementGuid>d304e884-8dd9-4235-8365-2a093ab10479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear Filter</value>
      <webElementGuid>c23136e4-7a3d-4c1f-8a49-f3094b3b3a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clearFilter&quot;)</value>
      <webElementGuid>6029a4f9-72aa-4216-885b-ab18f00f93f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>c21912d6-aab6-445c-a980-67315500d946</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='clearFilter']</value>
      <webElementGuid>f5e10456-596c-4eab-aa4e-dad9ae188ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Clear Filter')]</value>
      <webElementGuid>af93e4d0-62cc-40a9-92c8-7bc1345cd7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtered by F23JD800A001. filter'])[1]/following::a[1]</value>
      <webElementGuid>8a6a9227-f292-450e-b886-55f9e175357c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Business'])[1]/following::a[1]</value>
      <webElementGuid>dd76dcfd-13db-41de-a2bf-54fb2cafde75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F23JD800A001'])[2]/preceding::a[1]</value>
      <webElementGuid>9f0102f4-b828-4010-9308-bd824ffee14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F23JE780A001'])[1]/preceding::a[1]</value>
      <webElementGuid>aad1cb45-3a18-49b0-9711-72724ef6bb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear Filter']/parent::*</value>
      <webElementGuid>9dc752ba-fbf4-41dc-978d-5dd8ea3f09a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Enter to clear filter' and (text() = 'Clear Filter' or . = 'Clear Filter')]</value>
      <webElementGuid>29c7ab93-7d26-49fe-b854-544b7b9ccfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>8fcebd50-3155-477b-a296-84fc9593499d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/table/tbody/tr/td[2]/nobr/label/a</value>
      <webElementGuid>bf305f81-7bc8-480d-9a49-7145c3d87543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
