<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_TaskID</name>
   <tag></tag>
   <elementGuidId>89bef357-8957-4704-88e4-26f8b14f4f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//table//tbody//tr//th[@data-attribute-name='Task ID'])[2]//following::tr//td//div//span//a </value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;DataAccuracyCases_pgRepPgSubSectionDataAccuracyCasesBBBB.pxResults(1)_229&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0180723161229075247538&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c663185-cd4b-4043-9dd7-bef12bed1e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20180723161229075247538</value>
      <webElementGuid>f1800b65-94dc-4c70-adae-668b8ddf7a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>291521f8-fa4d-46c6-a6e5-f382125644eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>10ff25ab-b9cc-4898-9c91-9ba18cfb74c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>caff930d-6e1c-4a78-bd04-32104f371382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataAccuracyCases_pgRepPgSubSectionDataAccuracyCasesBBBB.pxResults(1)_229</value>
      <webElementGuid>8174946a-5fd3-4326-9567-0d5e038f3dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;openAssignment&quot;,[&quot;#~pgRepPgSubSectionDataAccuracyCasesBBBB.pxResults(1).pzInsKey~#&quot;,&quot;77193e34-e683-4d66-b068-52d655fee1c9&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;#~pgRepPgSubSectionDataAccuracyCasesBBBB.pxResults(1).pyIsOfflineEnabled~#&quot;,{&quot;pyReloadAlways&quot;:&quot;&quot;}]]]</value>
      <webElementGuid>bc4303d8-5189-493b-a7b2-a273fa02eacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong</value>
      <webElementGuid>629654ec-0276-4cd2-b5ca-39a576f0aeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QC-50662</value>
      <webElementGuid>66c732b7-5846-4ac3-87a2-43d4e266157b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PpgRepPgSubSectionDataAccuracyCasesBBBB$ppxResults$l1&quot;)/td[@class=&quot;gridCell  gridCellSelected&quot;]/div[@class=&quot;oflowDivM&quot;]/span[1]/a[@class=&quot;Strong&quot;]</value>
      <webElementGuid>18129904-6329-40a9-b7fa-2f910a204e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>34a96c65-7868-440c-9e9d-c67e45531abf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='DataAccuracyCases_pgRepPgSubSectionDataAccuracyCasesBBBB.pxResults(1)_229']</value>
      <webElementGuid>36744013-519a-4bb8-93d2-155f9806e54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'QC-50662')]</value>
      <webElementGuid>0d26f518-b5d7-4466-a87e-649bb167c348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwriting QC'])[2]/following::a[1]</value>
      <webElementGuid>acd6c893-4bb0-464d-b163-9ccdc76c3636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[18]/following::a[2]</value>
      <webElementGuid>8890ceb7-beca-40c3-b0bf-a12c654af8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F23JD800A001'])[1]/preceding::a[1]</value>
      <webElementGuid>7d5ef1ed-1b9e-455a-a30e-cabccc2883e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolved-Signed'])[1]/preceding::a[1]</value>
      <webElementGuid>f2148e63-74d3-41a0-85ec-423fe3194998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QC-50662']/parent::*</value>
      <webElementGuid>b575cab4-2418-4088-af95-08f1281e3b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>f60bca8e-8e1b-4a6e-a3ca-68adb56f9d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'DataAccuracyCases_pgRepPgSubSectionDataAccuracyCasesBBBB.pxResults(1)_229' and (text() = 'QC-50662' or . = 'QC-50662')]</value>
      <webElementGuid>19390c6a-ab59-407e-96a1-2427ee1e6165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/span/a</value>
      <webElementGuid>8f5095c1-b16d-4c23-a07c-b225859d3970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PpgRepPgSubSectionDataAccuracyCasesBBBB$ppxResults$l1']/td[3]/div/span/a</value>
      <webElementGuid>88e1d57f-c3f2-4bc3-b937-62963da87844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
