<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_forValidation</name>
   <tag></tag>
   <elementGuidId>d318f45f-5741-4703-ba98-227f21c95fda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;WorksheetResults_D_WorksheetCases_pa2303013188457548pz.pxResults(1)_51&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Worksheet Type'])[2]/following::a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0211223114632005763-R1&quot;] [data-test-id=&quot;\32 016072109335505834280&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>610993c9-45b2-48dc-8a66-73393bc5f2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2016072109335505834280</value>
      <webElementGuid>d572d5c1-65e6-48ff-9b87-81002f8bc44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>dae92fd7-8d1e-413c-9ebf-b899589abbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>b46d52d4-218a-4583-987d-31153b10eb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>45e4ad34-ab56-458e-84e6-200c27891660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WorksheetResults_D_WorksheetCases_pa2303013188457548pz.pxResults(1)_51</value>
      <webElementGuid>6cf5aaef-fc3f-4dec-b509-e6e18073ff89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;]],[&quot;openWorkItem&quot;,[&quot;#~D_WorksheetCases_pa2303013188457548pz.pxResults(1).pyID~#&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,{&quot;pySkipConflictCheck&quot;:&quot;false&quot;,&quot;pyReloadAlways&quot;:&quot;false&quot;,&quot;target&quot;:&quot;primary&quot;}]]]</value>
      <webElementGuid>87fc90ee-3337-4cea-beea-3c91776213f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>W-3925</value>
      <webElementGuid>8cf0ba2d-0549-4cfe-8b56-67ffdcd3026f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PD_WorksheetCases_pa2303013188457548pz$ppxResults$l1&quot;)/td[@class=&quot;gridCell    gridCellSelected&quot;]/div[@class=&quot;oflowDiv&quot;]/div[@class=&quot;divCont&quot;]/div[@class=&quot;cellIn&quot;]/span[1]/a[1]</value>
      <webElementGuid>7f0401aa-c180-4961-b285-c266f3956162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget0Ifr</value>
      <webElementGuid>8e6e6b50-aa9b-4c4e-a68e-5b7065fab008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='WorksheetResults_D_WorksheetCases_pa2303013188457548pz.pxResults(1)_51']</value>
      <webElementGuid>5117d48c-ab62-42c4-873f-b345cc87f1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'W-3925')]</value>
      <webElementGuid>c5684702-196b-4ba5-b536-6ce23d74395b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[14]/following::a[2]</value>
      <webElementGuid>01de01f9-f023-43db-9c9f-756ee3354328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Worksheet Type'])[2]/following::a[2]</value>
      <webElementGuid>18b46201-c960-4c3d-ac70-676617e72516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::a[1]</value>
      <webElementGuid>cd754213-74c0-4f61-96f0-9c3b0d3d7442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M2369444'])[1]/preceding::a[1]</value>
      <webElementGuid>339c38db-9a4c-41e7-89e6-e6628a1bb0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='W-3925']/parent::*</value>
      <webElementGuid>e36d6f04-c44c-40c8-982f-62ed66410c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>a94963aa-a2bb-4bce-8bab-543980668abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'WorksheetResults_D_WorksheetCases_pa2303013188457548pz.pxResults(1)_51' and (text() = 'W-3925' or . = 'W-3925')]</value>
      <webElementGuid>f65aeffb-c631-4809-a565-32bf3f213b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/a</value>
      <webElementGuid>7390be7c-5ca6-49ff-8f07-4c4ece59421b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PD_WorksheetCases_pa2303013188457548pz$ppxResults$l1']/td/div/div/div/span/a</value>
      <webElementGuid>6eb2c173-afb2-421b-b509-5a6aed379630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
