# azure-pipelines.yml
# ======================================
# Main pipeline that calls reusable Katalon job template
# ======================================

trigger:
  - none

jobs:
  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'FluschCacheSuiteCollection'
      testSuiteCollectionPath: 'Test Suites/Collection/FluschCacheSuiteCollection'
      testRunTitle: 'FluschCacheSuiteCollection'
      artifactName: 'FluschCacheSuiteCollection'
      executionProfile: 'FinancialLinesCloud_UAT'