# azure-pipelines.yml
# ======================================
# Main pipeline that calls reusable Katalon job template
# ======================================

trigger:
  - none

jobs:
  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection1'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection1'
      testRunTitle: 'Collection1_UAT'
      artifactName: 'Collection1_UAT'
      executionProfile: 'FinancialLinesCloud_UAT'

  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection2'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection2'
      testRunTitle: 'Collection2_UAT'
      artifactName: 'Collection2_UAT'
      executionProfile: 'FinancialLinesCloud_UAT'

  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection3'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection3'
      testRunTitle: 'Collection3_UAT'
      artifactName: 'Collection3_UAT'
      executionProfile: 'FinancialLinesCloud_UAT'

  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection4'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection4'
      testRunTitle: 'Collection4_UAT'
      artifactName: 'Collection4_UAT'
      executionProfile: 'FinancialLinesCloud_UAT'
      
  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection5'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection5'
      testRunTitle: 'Collection5_UAT'
      artifactName: 'Collection5_UAT'
      executionProfile: 'FinancialLinesCloud_UAT'
 
  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection6'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection6'
      testRunTitle: 'Collection6_UAT'
      artifactName: 'Collection6_UAT'
      executionProfile: 'FinancialLinesCloud_UAT'
 
  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection7'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection7'
      testRunTitle: 'Collection7_UAT'
      artifactName: 'Collection7_UAT'
      executionProfile: 'FinancialLinesCloud_UAT'
 
  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection8'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection8'
      testRunTitle: 'Collection8_UAT'
      artifactName: 'Collection8_UAT'
      executionProfile: 'FinancialLinesCloud_UAT'

  - template: template/run-testSuite.yml
    parameters:
      collectionName: 'Collection9'
      testSuiteCollectionPath: 'Test Suites/Collection/Collection9'
      testRunTitle: 'Collection9_UAT'
      artifactName: 'Collection9_UAT'  
      executionProfile: 'FinancialLinesCloud_UAT'  