<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UWComments</name>
   <tag></tag>
   <elementGuidId>4c0a17a3-b370-4ac7-8fba-a189bf875e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fb03a90c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='fb03a90c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0170307114435065642540&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>31b5ad85-e296-4436-8f09-8c9d50cf87aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170307114435065642540</value>
      <webElementGuid>ebad1b4a-73a4-49b2-b428-8d49977fb3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fb03a90c</value>
      <webElementGuid>bcaf250e-272d-44c7-89fb-b81a85b53cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TANORM textAreaStyle</value>
      <webElementGuid>69d63e1b-cd72-44bd-a192-999ce391ad63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pAdditionalUWComments</value>
      <webElementGuid>c5795391-8114-4fc1-8023-71237a8d2739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-exp</name>
      <type>Main</type>
      <value>Enter to Collapse</value>
      <webElementGuid>1e64a236-8127-46b1-b44a-6057ad03be09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-col</name>
      <type>Main</type>
      <value>Enter to Expand</value>
      <webElementGuid>469227aa-b974-42ed-b589-4cc16411bb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c0ef49dd-8461-4378-b152-f0c56a650c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextArea&quot;,{&quot;height&quot;:&quot;auto&quot;}]</value>
      <webElementGuid>08f0f19d-27cc-4cc2-9900-534f93b5fa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pAdditionalUWCommentsError</value>
      <webElementGuid>4e27f3af-669e-4e9f-a6f4-0bc1d20854b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c0f084e0-ad6c-4443-ba25-1db12e31f5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fb03a90c&quot;)</value>
      <webElementGuid>2f17c634-65cf-45e0-9dda-af8c65e8fec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Reports/iframe_PegaGadget1Ifr</value>
      <webElementGuid>693670dc-3b24-40ef-ab7c-800e7400418f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='fb03a90c']</value>
      <webElementGuid>7b41de8d-403d-4a02-ade2-eeef2283e00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = '$PpyWorkPage$pAdditionalUWComments']</value>
      <webElementGuid>04441fa3-c604-4fd7-b6fe-d14cd70b0a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>655aeb81-7aa4-4100-9052-a4b06b2ae74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='CTRL_TA']/textarea</value>
      <webElementGuid>f1cdef41-8a0a-455a-bcb3-b04401d2e078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
