<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_QF19057323N_PegaGadget2Ifr</name>
   <tag></tag>
   <elementGuidId>fd457f43-3e04-4789-aea8-b2edae52a835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='PegaGadget2Ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PegaGadget2Ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;PegaGadget2Ifr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>45851228-a228-4c4d-b665-929220878233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
      <webElementGuid>6b257382-92c8-45fe-a456-ac47e129a872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *;</value>
      <webElementGuid>05de47b6-bf48-4b26-8dbe-04ce4e99e859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
      <webElementGuid>af53b1d4-d8a6-4c17-abec-fe1f9f194f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>126fb660-aa6b-4340-8ca3-f86e62b905bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>728999cb-1a79-43ef-bedc-6b54d8b3c6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prweb/app/LiabilityLines_/AQrj2LB4NQCKaV10lflPLOnOAP4olJWCG1vcOaRKU9iAwaE8P9peJQ*/!TABTHREAD2?pyActivity=%40baseclass.doUIAction&amp;action=openAssignment&amp;key=ASSIGN-WORKBASKET%20HCC-CL-LL-WORK%20W-11550!COMPANYSEARCHFLOW&amp;contentID=fa1569dd-6060-63cc-9446-eafea0e29a4b&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;tabIndex=3&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HIDF62E64191E9324DB1FF39A645FD26BDC</value>
      <webElementGuid>c53829a7-eccd-457f-9e35-8bdb5282d3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>W-11550</value>
      <webElementGuid>69b6d56e-f1f2-44ba-963a-f73689351387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget2Ifr&quot;)</value>
      <webElementGuid>7b0ed786-8f77-4872-bb5e-955e640f494c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='PegaGadget2Ifr']</value>
      <webElementGuid>d2b32b99-3a16-4189-a9e0-cc8a60e5b7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PegaWebGadget2']/iframe</value>
      <webElementGuid>e921cad1-1b3a-404b-a630-7caf706adc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/iframe</value>
      <webElementGuid>bbc47a7a-50be-4366-9159-52a7c945b224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'PegaGadget2Ifr' and @id = 'PegaGadget2Ifr' and @src = '/prweb/app/LiabilityLines_/AQrj2LB4NQCKaV10lflPLOnOAP4olJWCG1vcOaRKU9iAwaE8P9peJQ*/!TABTHREAD2?pyActivity=%40baseclass.doUIAction&amp;action=openAssignment&amp;key=ASSIGN-WORKBASKET%20HCC-CL-LL-WORK%20W-11550!COMPANYSEARCHFLOW&amp;contentID=fa1569dd-6060-63cc-9446-eafea0e29a4b&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;tabIndex=3&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HIDF62E64191E9324DB1FF39A645FD26BDC' and @title = 'W-11550']</value>
      <webElementGuid>2b78de0d-2d19-4faf-b6b1-4be2377419eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
