<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WebElement_DocumentMaintenance</name>
   <tag></tag>
   <elementGuidId>3de3a8ca-83e3-43f2-937d-484ad0ee3841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li//a//span//span[text()='Document Maintenance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Document Maintenance&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e686638-e452-4aa1-95e3-2e0808640445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-title</value>
      <webElementGuid>7ef7a886-93b5-459a-a08a-e14226f26b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>..</value>
      <webElementGuid>9a87a1ae-87d6-4842-b6d0-a66bbc3c761c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Document Maintenance</value>
      <webElementGuid>192b1d79-11e2-45e4-823f-9815bfaa06f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-$PpyNavigation1729568521933$ppyElements$l16$ppyElements$l1&quot;)/a[@class=&quot;menu-item-anchor menu-item-expand&quot;]/span[@class=&quot;menu-item-title-wrap&quot;]/span[@class=&quot;menu-item-title&quot;]</value>
      <webElementGuid>50128bff-c5de-408f-ae35-5e1ee305d113</webElementGuid>
   </webElementProperties>
</WebElementEntity>
