<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Page successfully removed from clipboa_26c21e</name>
   <tag></tag>
   <elementGuidId>192dd5fd-25d0-4638-a80c-32b064365c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnCancel']/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.buttonTextHover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>359eeac0-f6a9-49c0-a39d-0b9537084a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonTextHover</value>
      <webElementGuid>c1fee2c3-2e05-4711-a0b3-aa1b41e8a52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>this.className='buttonText'</value>
      <webElementGuid>375b00ab-2d27-4994-85ea-c2084649e866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.className='buttonTextHover'</value>
      <webElementGuid>0aaf7d3d-367f-48a4-9050-c697af193ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>d79e662c-10cb-4234-a408-174a5079893f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCancel&quot;)/span[@class=&quot;buttonMiddle&quot;]/span[@class=&quot;buttonTextHover&quot;]</value>
      <webElementGuid>b048c18a-40ff-41db-b6be-1f1cd6c44626</webElementGuid>
   </webElementProperties>
</WebElementEntity>
