<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Update</name>
   <tag></tag>
   <elementGuidId>fa4f30fa-ef8c-4014-bd78-aba85f3db88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > #CT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='.pyNote']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span > #CT</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d6b06ea-fc2f-4a1c-91a3-acba88e47f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CT</value>
      <webElementGuid>084dac0a-8205-44a0-9c57-c447104f4450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>.pyNote</value>
      <webElementGuid>ca09cc9d-1c11-439c-9f29-58f14c559302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disable_when</name>
      <type>Main</type>
      <value>SetProgrammeIDData.pyNote=='DontDsplyButton' || SetProgrammeIDData.Comments=='DsplyError' || SetProgrammeIDData.NewComments=='true'</value>
      <webElementGuid>a450249b-2351-4737-8e71-699bbef51384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update </value>
      <webElementGuid>cc3ae153-c485-46fa-b4cc-78819ed9bd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none float-right set-width-auto&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  set-width-auto layout-content-inline content-inline&quot;]/div[@id=&quot;CT&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/div[@id=&quot;CT&quot;]</value>
      <webElementGuid>1f60b6cd-ebe7-45fd-8f93-61c0aab49d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>82284a66-1a38-446a-b78c-6335a8a1af59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='CT'])[13]</value>
      <webElementGuid>0a80aef1-e793-4561-805d-1bec3ff2db69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::div[4]</value>
      <webElementGuid>84ecc6be-d91a-41f9-9385-b8b07ff08481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/following::div[15]</value>
      <webElementGuid>1b4099d4-8d25-4056-9e42-7267866a9ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[2]/preceding::div[5]</value>
      <webElementGuid>315c167c-0c93-4585-aa22-23642beb2b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = '.pyNote' and (text() = 'Update ' or . = 'Update ')]</value>
      <webElementGuid>aba67209-1a0f-4c19-83e2-851f6346b0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/div</value>
      <webElementGuid>36d6d1f4-af7f-4f08-94fa-7c61966dc86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CT']/div/div/span/div</value>
      <webElementGuid>e9880127-3d29-4c90-977c-400b1f753355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
