<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comment</name>
   <tag></tag>
   <elementGuidId>c122f17a-724d-4ac5-b8ea-d5b75734593f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@name,'ProgramComment')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#96e70369</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Comment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6870252-8057-45fe-881f-d72dcd509eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2021110114071602632371</value>
      <webElementGuid>0508cd33-5009-4936-b59a-632eb8d2befd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>fdd34b72-54c5-46ab-862b-cdc82a8f5501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>96e70369</value>
      <webElementGuid>accae5b1-ac5d-4635-afa8-6b0e564113b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10c9f6be-3dcf-4051-84c8-0fcaa0931727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PSetProgrammeIDData$pProgramComment</value>
      <webElementGuid>9dc51a5f-8485-4a38-a3a0-51af4142a149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>f58fe8f7-8777-4608-b84c-5070239eb2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;ValidateSameMajorClass&quot;, &quot;=&quot;, &quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;,&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;ValidateMultiProgramme&quot;, &quot;=&quot;, &quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>bcb1263d-06a4-47c9-b580-0e46835caf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1f811d82-a157-4151-acd4-874991fcabd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;96e70369&quot;)</value>
      <webElementGuid>e3280c4a-f5ea-4eaf-a2ce-0c456f78242c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>f75add34-fbff-44a6-a78e-f6c856dba307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='96e70369']</value>
      <webElementGuid>1f51a3e4-11bd-4632-9f85-57ac027bc0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '$PSetProgrammeIDData$pProgramComment']</value>
      <webElementGuid>c6d6da88-dbef-4d29-bd49-b1b23f5d8294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/span/input</value>
      <webElementGuid>c026d9ae-96b0-4886-bf82-67c142d327c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[3]/div/div/div[10]/div/div/span/input</value>
      <webElementGuid>d9ce9327-ec6d-4730-a87e-1c6c901218f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
