<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NewMultiProgID</name>
   <tag></tag>
   <elementGuidId>a0207948-028f-4e37-9d46-ea5b17ad2aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c896154f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'NewMultiLOBProgViewID')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0211005081406059920464&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb891b95-86f5-425c-9f60-61ba34271e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20211005081406059920464</value>
      <webElementGuid>2421333e-2801-455e-b00e-e06a11325d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd0ba074-2122-40f0-bb51-b020e5171834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;AutoCompleteAG&quot;]</value>
      <webElementGuid>39145522-e349-44f9-a40c-c394fef68198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dd753a56-1bfe-44bd-a891-6d9e6a59123b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ab724fc-02d0-41cf-9170-a2e87170d59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eb547bd0-9f03-4a25-953f-aba95a4e7329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f17c57b8-1e7b-4073-bb7b-471e2a79ed8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PSetProgrammeIDData$pNewMultiLOBProgViewID</value>
      <webElementGuid>dcbe9f9a-050a-4b2b-9c91-c32873a69602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c896154f</value>
      <webElementGuid>a02e53aa-5c60-4e34-8251-5179f46e872a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change-lazy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c1cff45-d730-442f-bee1-14d267dbf496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;ValidateMultiProgramme&quot;, &quot;=&quot;, &quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;,&quot;:event&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH0wOTlhMWZmNmRiZTY2NDNmMmYzY2E2ZWRlZmNlYTFkMDJiYzRlOGU0YzgzZmJkYTRlMGUxOTJhMmViMzM4MDY2MGM4OGM2MDMzZDM3NmNiNDVhM2JmM2EwOTNjZGM0NjM5MWQ2N2RkNGU0Y2JjNzdmYjZmM2M5OTdiYmM2OTcyOTZiMGM4YzIyMjA4YmE0OWY1OGU5NjIyZDc3ODJkMjZjZGY4ODQzZWI1MjBlODJhMzRhYzY3NGIzYjZiMmIwNDU3NmRhN2M0NzZhNGIwMmY4OTkyM2JiZjcxYmZlZjQwY2Y0YTFmYjEyMWQ3MDkxM2E4YjQ4NDMzZTNjMzNhZGY1YWZmYzc3Zjk3ZmIxMTdhMzhlOGJjMDM0NmRiNTljOTc2M2VkN2I0ODMxYjIwMDhlNDgzM2Y0MGVjM2FmZDQ1NWU2MzkzYzM0ZDdkZTI2NmVkYmRlNTQyOTgxMTQ2YjJlNjZiMWI0ZWZjNzFkZTBkNzI0Nzc4OTIxMjM0N2MxNzY2OWIzNjY5MmQ0MDRhYmUzOTg5MzAwNDAwYTgwNjc1Njg2MTE5YmVjZWY2NTU1MWNmYjFjMDliYjk0ZGEwMzY5OTg4MWUwN2VlOWFlYTA5ZmQ0OWZmN2NiMTA3ZjJlYTIxMTgyYzZkZGZiODI5ZGM2NGYxNjNmNDcxMDg3NjYyODRkMjBiYWViMDdkZTZmOTllNWQ4OGQyYmFiOTcwMmJj*&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH0wOTlhMWZmNmRiZTY2NDNmMmYzY2E2ZWRlZmNlYTFkMDJiYzRlOGU0YzgzZmJkYTRlMGUxOTJhMmViMzM4MDY2YWQ1NzNlZTVkMzFhZWM0M2Q5ZjIyNDZlMGMyMjBlZjRkOWUyYzg1YzJjMzI0NTMxNWQyMzg0NGQ3NjRjYjgyM2IxNTcwY2ViMzIwOGJkNzlmOWMyYWU5MDRmNDIzODYxYzMyYzlmMmY1YzNlYTQzNWVkMjk4OWEzYzQ3NDg5OWUyYmNhMGFhZWQ4MjcwODY4OTAzYjgwMjU4ZjU0OTEwYzVlNTljMTdlYTgwYjBlOWEyZTdkMTlmOTg0NWNlNDFmMDk4MTlmNjRkZmU3MGNmNjNhYjRmZjY5OTNmNTYyNDc2YjVmYmVhZjNlZTBhM2Y0ZDU1ODc5ZjA0MWNiMDRjMTJiNzViYmNkYjI5OTkzNTA0MDU5ZmQ2NDg4MDE4NjFmMDNhYTJiYjg3MTc4MTc2ZWFlZTU5MmUxMmU1OWExNTc%3D*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH0wODNkNTUyMGFiMTE5ZjJlYWVkODdkMmNkNzE4MjQ3ZTg4MGI0MDQ0YmNkNzM4ZTZmYjNlNTgzY2NiYjY2MWVjMmMxYTkyZmIzMDk3N2Q0NWVmYjlmMDllZjJmYjM1ZGE5ZDU5ZmMwM2E1MDAyMjJjMDZkODc1MTJlMjRhODlmMTBjZTA1NWNkMDVhNDYwY2I0YWZiN2Q0NjMxZGE5MzhiNTM5YzI4OWIxMDQ4ZjU4ODM3MDc2NTAzZjVjMzdiOWE%3D*&quot;,{},{}],&quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;]]]</value>
      <webElementGuid>906e2743-f9f8-4efe-8699-41cee1ea26c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete_input ac_</value>
      <webElementGuid>a63e43a9-118c-4a15-b514-59ffb7e9ce32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>jh</value>
      <webElementGuid>1f465591-7fc0-4720-ae8a-b44f97bfd41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attributes</name>
      <type>Main</type>
      <value>[ &quot;EXPANDEDSubSectionUpdateProgrammeID12SetProgrammeIDData_NewMultiLOBProgViewID&quot;,3,0,{&quot;ProgrammeIDType&quot; : &quot;Literal_Multi&quot;},&quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;,0,false]</value>
      <webElementGuid>f18338e8-8ad6-42f4-826e-e8c895f99391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95d17b23-f16e-4f5e-a561-9dd90491580e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-old-value</name>
      <type>Main</type>
      <value>jh</value>
      <webElementGuid>ea8f31f4-f68f-4755-9c58-22737b810a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c896154f&quot;)</value>
      <webElementGuid>0f48d675-7f53-472a-9a09-7696c8c2543b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>341ae139-6a01-4c75-9b6a-af441f13f999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c896154f']</value>
      <webElementGuid>02ddcc09-0a9a-44a5-aa4f-822b87f48b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '$PSetProgrammeIDData$pNewMultiLOBProgViewID']</value>
      <webElementGuid>45267c4a-007a-4121-88a7-8f75dc145853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span/input</value>
      <webElementGuid>29838642-82b2-485b-810a-e55b226c8877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[4]/div/div/div[4]/div/div/span/input</value>
      <webElementGuid>68cde86e-4f28-4e69-8036-4246eee51b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
