<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PropertiesValue_PRH_1ppyStepsl3ppyParamArrayl2pPropertiesValue</name>
   <tag></tag>
   <elementGuidId>0148e27b-66fa-4a4a-b717-3d0df4f1b58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='PropertiesValue'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.gridCellSelected > table > tbody > tr > td[name=&quot;RH_1.pySteps(3)-ParamValue&quot;] > #SL_Table > tbody > tr > #SL_Input > #PropertiesValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01801041203490824537-R3-L1R2&quot;] #PropertiesValue</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c0583c3-0a61-4121-86d0-a78ca9529a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PRH_1$ppySteps$l3$ppyParamArray$l2$pPropertiesValue</value>
      <webElementGuid>985c67b4-4ae4-46f5-ad4e-371f3c5df986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>2d008d2a-5b5a-43d5-bd70-c34932448b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PropertiesValue</value>
      <webElementGuid>c88399e1-eebc-4fc5-907e-c2860ba0bb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf2f2533-9431-424a-8477-164736b876c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>&quot;2024-09-03T00:00:00+01:00&quot;</value>
      <webElementGuid>9771c3b4-4dc5-4041-aaa4-1442ba232556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isns_class</name>
      <type>Main</type>
      <value>Rule-Obj-Property</value>
      <webElementGuid>b05af088-0c2c-4821-a8f4-243e0f43d23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isns_baseclass</name>
      <type>Main</type>
      <value>$PRH_1$ppySteps$l3$ppyStepsClassName</value>
      <webElementGuid>b37a3f72-0d50-4b55-8f63-31ffef664b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>if(window.objSmartPrompt &amp;&amp; window.setGridClassNameDefaults) { objSmartPrompt.doOnFocus(null, event); setGridClassNameDefaults(this); }</value>
      <webElementGuid>5fb658fe-8415-4ed4-9be1-657800a84b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputIntellisenseStyle</value>
      <webElementGuid>565e9cb2-a4fa-4747-8922-238bab2d0530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isns_onchange</name>
      <type>Main</type>
      <value>onChangeHandler</value>
      <webElementGuid>a403b21a-362e-49cb-8ec5-7860dfc6931a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isns_onpick</name>
      <type>Main</type>
      <value>onChangeHandler</value>
      <webElementGuid>5b20d6c4-2d16-44a7-93d6-279a2a1cf2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isns_listname</name>
      <type>Main</type>
      <value>List</value>
      <webElementGuid>a853a9eb-4730-4eb3-8b3f-a80bdea0cb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isns_propertyextras</name>
      <type>Main</type>
      <value>oOpenRuleAdvPropExtra</value>
      <webElementGuid>0fc203eb-e1b4-412a-a0d3-458aa94fc2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isns_popuptype</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>7413f346-d87e-41b3-8a9f-ea66ac7b63a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isbaseclassset</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd8c767a-b660-45a6-a5dc-94df57a6b7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8032f189-ed65-403f-9c1e-f3734dc5d5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>handlePropAndRulePrompting(this, event)</value>
      <webElementGuid>9cefb6d6-6403-49dd-8519-49b70bc8cfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>getGridDataSourceClass(this);</value>
      <webElementGuid>a0e8d0fd-5ccc-4a9b-82de-c429684f5bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>processExpressionField(this);</value>
      <webElementGuid>9d77c037-6679-496a-872c-12413aa40b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1edd6ea-cb11-4e14-b1ad-755bac445fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isns_fieldtype</name>
      <type>Main</type>
      <value>PROPERTY</value>
      <webElementGuid>6b26cb4c-c328-44bb-86cf-3a5c52e6eca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PRH_1$ppySteps$l3$ppyParamArray$l2&quot;)/td[@class=&quot;gridCellSelected&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@id=&quot;SL_Table&quot;]/tbody[1]/tr[1]/td[@id=&quot;SL_Input&quot;]/input[@id=&quot;PropertiesValue&quot;]</value>
      <webElementGuid>bd5564a0-e197-44fa-b05a-3818b6256f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RenewalAgent/Page_Pega Dev Studio/iframe_Resources_PegaGadget1Ifr</value>
      <webElementGuid>6c343a18-24f4-49a7-9696-7dbf53bd13c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='PropertiesValue'])[2]</value>
      <webElementGuid>23c8d1aa-d36b-4343-9e96-ef9c939607ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//td[@id='SL_Input']/input)[7]</value>
      <webElementGuid>2149934a-0a4a-4ece-80c7-bac6361f7824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>48309085-e2a0-41fb-974d-8cb5b895edf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '$PRH_1$ppySteps$l3$ppyParamArray$l2$pPropertiesValue' and @id = 'PropertiesValue' and @type = 'text']</value>
      <webElementGuid>b01d80c9-ce68-407b-a121-cd58f00b2ea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
