<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>40c6bd25-571d-475e-943d-7d78ea528408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;FindSurplusBrokerContact_pyDisplayHarness_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0170926085438052740906&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ee2a3f58-448c-421d-bb27-c3520e99813b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runDataTransform&quot;, [&quot;SetPyNote&quot;, &quot;=&quot;, &quot;pyDisplayHarness&quot;,&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;SurplusBrokerContactSearch&quot;, &quot;PostSurplusBrokerContactSearch&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH02NzA2NTdhNDMzYmFhNDZkMWI4N2M5MjlkNjA0ODBmYjM3NGZkMDM4OTA3ZWVkOTY5MTI5MWIxNmNkNWY3NzM4OTcxZDE1OWMyOTIyZTRkNzNiMWRjZjRjYmYwY2JlMGRmZTM4MTYwYTIyZWVkZjViMjU0OWQ3ZjRlMDM2ZGEwYTI0MDZmNGY5Mzk1N2ZhODZjY2M0YTcwYWZiNDg5OGU0ZmM1M2NhMjFkNjk1Y2FlNzE5MGM2NDg3ZTU3MDA4MjdjOTFhOGFjYWIxYTFjNmJmOTUxNDg0NjU3NjY5YzgxOA%3D%3D*&quot;,{},{}],&quot;pyDisplayHarness&quot;]]]</value>
      <webElementGuid>a00afed9-fae1-4e86-9ad5-be03c6197a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keydown</name>
      <type>Main</type>
      <value>[[&quot;runDataTransform&quot;, [&quot;SetPyNote&quot;, &quot;=&quot;, &quot;pyDisplayHarness&quot;,&quot;:event&quot;],,&quot;enter&quot;],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;SurplusBrokerContactSearch&quot;, &quot;PostSurplusBrokerContactSearch&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMH02NzA2NTdhNDMzYmFhNDZkMWI4N2M5MjlkNjA0ODBmYjM3NGZkMDM4OTA3ZWVkOTY5MTI5MWIxNmNkNWY3NzM4OTcxZDE1OWMyOTIyZTRkNzNiMWRjZjRjYmYwY2JlMGRmZTM4MTYwYTIyZWVkZjViMjU0OWQ3ZjRlMDM2ZGEwYTI0MDZmNGY5Mzk1N2ZhODZjY2M0YTcwYWZiNDg5OGU0ZmM1M2NhMjFkNjk1Y2FlNzE5MGM2NDg3ZTU3MDA4MjdjOTFhOGFjYWIxYTFjNmJmOTUxNDg0NjU3NjY5YzgxOA%3D%3D*&quot;,{},{}],&quot;pyDisplayHarness&quot;],,&quot;enter&quot;]]</value>
      <webElementGuid>89f3f060-0166-485b-9dc6-3a0e4db226cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170926085438052740906</value>
      <webElementGuid>1b49dcfa-4df8-4630-8300-23e650d67c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Icon</value>
      <webElementGuid>016f2e20-3011-47b8-958c-9ae7b449e811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>webwb/pxcasemgrportalsearchicon_13780558315.png!!.png</value>
      <webElementGuid>caba7aef-6d2e-4c30-b8ba-6a51d52c9895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FindSurplusBrokerContact_pyDisplayHarness_2</value>
      <webElementGuid>d7ae3a66-c182-48c7-99b1-18142077bcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6552cf47-d573-4866-916f-6c153db22401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>84c10152-fde5-438b-a709-a2f969a1bf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EXPAND-OUTERFRAME&quot;)/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-sub_section item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_labels_left  content-inline_labels_left&quot;]/div[@class=&quot;content-item content-field item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/i[@class=&quot;icons&quot;]/img[1]</value>
      <webElementGuid>83d42b0f-952a-436f-84d9-56afd0b6c4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PartyManagement/Page_InsuredSearch/iframe_PegaGadget0Ifr</value>
      <webElementGuid>216805b4-6734-4b7d-aabe-a85cd5843fe4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
