<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DeleteItem</name>
   <tag></tag>
   <elementGuidId>8a4f38b4-bd1c-4651-8fcd-d0cb07c9cff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.ProposedQuotes(1)_8&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@string_type='field']//span//a[contains(@name,'GridAddandDeleteOptions') and text()='Delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02207290744560978370&quot;] [data-test-id=&quot;\32 01507160305400976873&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8687956f-88c7-4567-8fba-e8b774bf3986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201507160305400976873</value>
      <webElementGuid>1ee78b33-c9d7-4bf9-a0e2-ab6531701e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f99a2bd0-cdd7-4c0d-b565-8cacf84d4091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>42df8824-054a-4d15-a658-bd7b84f150a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>bb182808-28f3-4f1f-ad37-199d1029dce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.ProposedQuotes(1)_8</value>
      <webElementGuid>80cb5db6-9a00-4090-8fe7-a1826fbcabaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;removeFromRepeatSource&quot;,[&quot;:event&quot;,&quot;false&quot;]]]</value>
      <webElementGuid>2b9596c4-ca7b-4ef5-88fa-a52ac81dbd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>d9dfd425-5e2d-47f1-ba4a-d90bb9de4c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID32&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataLabelWrite gridActionAlignLeft&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex  content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-2   flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex  content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-2   dataValueWrite flex flex-row&quot;]/span[1]/a[1]</value>
      <webElementGuid>415e32d1-7550-41d8-81d3-874dfb1ea1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>0b6265cd-5b29-4797-ba17-56bfb04301f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.ProposedQuotes(1)_8']</value>
      <webElementGuid>fc4f9eaa-5dfe-4341-8836-a27a2f6e02b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Delete')]</value>
      <webElementGuid>1912f1a1-46de-4b16-859e-36ef27bac331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>da52044c-39c5-477a-99e6-7c2915c86147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items'])[2]/following::a[2]</value>
      <webElementGuid>11d973f4-727e-4885-88c0-2b5d73d23956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TMHCC Fee Amount'])[1]/following::a[2]</value>
      <webElementGuid>fa36cf31-9efa-4129-b382-d6b39a5fdd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium Information'])[1]/preceding::a[1]</value>
      <webElementGuid>d89a8513-fdac-4556-aca7-ac94d8b478a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium Type'])[1]/preceding::a[1]</value>
      <webElementGuid>424866ff-1309-429d-8100-9545970fe356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>eb919d8b-4463-4878-a06a-43a7583e005b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.ProposedQuotes(1)_8' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>c47b0d6a-3229-46a2-9598-8a212682fd8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span/a</value>
      <webElementGuid>8986a859-ddaa-4750-802a-7aeca68b0278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div[2]/div/div/div/div[2]/span/a</value>
      <webElementGuid>36119c43-1cfb-49fc-ad87-9c444fd26fc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
