<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue_pre</name>
   <tag></tag>
   <elementGuidId>ebbf14ca-e1b2-44c7-8aac-1e2235df3a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[(text() = 'Continue' or . = 'Continue')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;GeneralDetails_pyWorkPage.SubmissionData_196&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02106280936320566502&quot;] [data-test-id=&quot;\32 01701181235120120327907&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14427b87-8f3f-42f5-ba90-8521372db510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201701181235120120327907</value>
      <webElementGuid>96224638-3e7f-42a0-ab0f-5d84656cf74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runDataTransform&quot;, [&quot;SetFloatingErrFlag&quot;, &quot;=&quot;, &quot;pyWorkPage.SubmissionData&quot;,&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;InvokeCreatePackageFromGenData&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEOH1iNzQ5YzllY2E0Y2RkODNiZDY0ZmU1NWUyMTUxY2YzNWYzNDVhZGFjOGQ1NzdiY2E2NTA0ZTM2YzRhYjBjNmZkNjY3ODJiYThkNTA2NGJkZDY2NTNkMzIyY2Y5NGRlMmU5MjVkMzMwN2I1NTBjOWViMmVhY2RjOTI2ZTBkNWUyMzQ3ZTliZWEyNzNkZWZiMzE4N2IxODg1YjI1ODdjMzQwMDU0NGQwODA4NmJlZDc0ZjQ2ZWE4OWQ1M2Q5NDNlYzI3NGJjZjQ0MzhlZTcxYjExNDRjZjk2MmMyMWM4MDY5YTU4MTJiY2MyYjdiZDg2NjQ5Y2NiMjdhMjU4NDAyN2Fl*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pyCaseContentInner&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEOH1iNzQ5YzllY2E0Y2RkODNiZDY0ZmU1NWUyMTUxY2YzNWYzNDVhZGFjOGQ1NzdiY2E2NTA0ZTM2YzRhYjBjNmZkNjY3ODJiYThkNTA2NGJkZDY2NTNkMzIyY2Y5NGRlMmVjNmQ3MGQ3YjA4N2FiYjY2YmRkZDAyZmUxNDQ4NDliOA%3D%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;runScript&quot;, [&quot;ContinueEventsConditionally(\&quot;#~pyWorkPage.SubmissionData.ContinueActionEvents~#\&quot;)&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;pyWorkPage.SubmissionData&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEOH03MGU4YWJiYmUzNGVjMTQ2ZGU2MzVlYmU0OWJlYjJkYTZlYzUxNjgwYjY0MzU0OWYzYTEwMmZhNDc2Mzk1YjZhYjNjZTdiMGQ4YzM5NmRkMjE4ODA1ZWY1MWViNGJiYWFhNjlmOGViNzUyNjBhODQ0YzA1NWNjNjBiZjBlNjZmZWFmMDI1ZjZmYTc0YTMyZGM4OWY0ODM2M2MzZGU1OTU0ZWUyZTU1MDIzMmFmYjQ4N2U4OTU0OWNjN2RlM2NmZWRjMTI1M2JiMjdkNWEwYTg3NWRjZGJmNzY0NmQzMjE3ZGU0YzdmYTQ5ZDIzOWRkNTA2ZWE4ZGNmNjBlZWQyMzEzY2Q1OWFmMWIwNTZmMDQ3YzlmMzg5MWVkMDljY2MyYTA4ZGZlNmE2ZGNiYTNjMDYyZGYwYmQwMjE4MzNlNDVkMw%3D%3D*&quot;]],[&quot;processAction&quot;, [&quot;DisplayPolicyReference&quot;,&quot;true&quot;,&quot;:event&quot;,&quot;pyWorkPage.SubmissionData&quot;,&quot;Rule-HTML-Section&quot;,&quot;&quot;,&quot;PolicyModalTemplate&quot;,&quot;%7B%22mobile%22%3A%7B%22reveal%22%3A%7B%22effect%22%3A%22anim-null%22%7D%2C%22isCustomDismiss%22%3A%22true%22%2C%22dismiss%22%3A%7B%22effect%22%3A%22anim-null%22%7D%7D%7D&quot;,&quot;true&quot;,&quot;HCC-CL-LL-Data-Submission-Com&quot;,&quot;HCC-CL-LL-Data-Submission-Com&quot;,&quot;false&quot;,&quot;false&quot;,&quot;&quot;,&quot;&quot;]]]</value>
      <webElementGuid>f2fc33e6-7004-4d96-89f8-118f18814f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GeneralDetails_pyWorkPage.SubmissionData_196</value>
      <webElementGuid>cbd36841-4a87-44b3-a74b-73d287593738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pzhc pzbutton</value>
      <webElementGuid>fa38be48-5077-42fd-a59e-92d612ef958e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c9f5bd0-45b3-4cc7-9048-f78118c17f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>ed3c1c36-429f-463c-8c5c-00f46f055ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default  clear-floated-layouts&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-simple_list  content-simple_list&quot;]/div[@class=&quot;content-item content-layout item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle auto-width-column&quot;]/div[@class=&quot;content-item content-layout item-1 remove-bottom-spacing float-right set-width-auto&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle set-width-auto&quot;]/div[@class=&quot;content-item content-field item-3&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/button[@class=&quot;pzhc pzbutton&quot;]</value>
      <webElementGuid>d5d89101-2493-425b-a109-bb5d7c06a7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>cbe0f80d-e493-4c0d-9345-b7c7c0768a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='GeneralDetails_pyWorkPage.SubmissionData_196']</value>
      <webElementGuid>d5c56038-acf2-4eab-8ca2-127168f52c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::button[1]</value>
      <webElementGuid>f43effe7-6ea7-4815-87b9-61fabe36d219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Quote?'])[1]/following::button[2]</value>
      <webElementGuid>34a13450-2568-4120-88a9-e5ba0898e812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[1]/preceding::button[1]</value>
      <webElementGuid>be9b9726-51e9-486c-ab0e-73dd460d1786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::button[1]</value>
      <webElementGuid>cf8ef835-6c94-43b3-8dd3-d5e02f99e2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>e4311425-dca1-46ba-875e-b764a9e19a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'GeneralDetails_pyWorkPage.SubmissionData_196' and @type = 'button' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>a543bbc2-bfc5-463f-b8cd-12311f574a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/button</value>
      <webElementGuid>d9bd15f9-4823-4da3-a9d5-26afa5405c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/span/button</value>
      <webElementGuid>8102e0bf-c0d7-4544-935b-889581a3022b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
