<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AddItemKR</name>
   <tag></tag>
   <elementGuidId>beca1260-1515-47ed-bb15-c129fc0cd069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@name,'KRSpecificDetails') and contains(text(),'Add Item')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;GridAddandDeleteOptions_pyWorkPage.ApplicationPage.SelectedQuote.KRSpecificDetails_4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02112070555380379407&quot;] [data-test-id=&quot;\32 018030913301903194833&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8481ff41-5a23-4458-8ccc-7308004fd9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2018030913301903194833</value>
      <webElementGuid>9801af03-d73e-454f-b0a6-543544d318d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9b39f5ea-a774-4d1a-b0c9-1e85a602a1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>f40dcb1d-0428-4443-a8c8-2a24dffff865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>b4422e11-c320-4bab-8da7-2581f28543d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GridAddandDeleteOptions_pyWorkPage.ApplicationPage.SelectedQuote.KRSpecificDetails_4</value>
      <webElementGuid>8128bebe-2049-4fcd-b8f6-562801f5bcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;doListAction&quot;,[&quot;:event&quot;,[&quot;ADDITEM&quot;,&quot;&quot;, &quot;INSERTAFTER&quot;,&quot;&quot;,&quot;pyNextGenGridModalTemplate&quot;],[&quot;INSERTAFTER&quot;]]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;Sublimits&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iNjllZDY1ZWNkZTVjNmE0NDZiMDAxNGYwOTRiMTY4NzNjMmYxNWFmNGM0ZmI1YWY4NjI5ZTI0M2NkMDZlNzBhM2YwYTc3ZGI2YWQ5NWRiY2FmOGQyNzIzYmM4OGM0YjUxOGM1ZTFmZTg4OTIyMjk3NjljMzBmZjE5NjMwMmIwMA%3D%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.SelectedQuote.KRSpecificDetails&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;Deductible&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iNjllZDY1ZWNkZTVjNmE0NDZiMDAxNGYwOTRiMTY4NzNjMmYxNWFmNGM0ZmI1YWY4NjI5ZTI0M2NkMDZlNzBhM2YwYTc3ZGI2YWQ5NWRiY2FmOGQyNzIzYmM4OGM0YjUxOGM1ZTFmZTg4OTIyMjk3NjljMzBmZjE5NjMwMmIwMA%3D%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.SelectedQuote.KRSpecificDetails&quot;]]]</value>
      <webElementGuid>337f893d-3ba7-41a4-9e11-161b9d586ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Item</value>
      <webElementGuid>ee229187-5bf2-432c-a6fd-7ba49251a55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID8&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataLabelWrite gridActionAlignLeft&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/a[1]</value>
      <webElementGuid>69b8ffdd-88b1-4e9f-83bc-a59eca559b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>4b84c17d-de9a-440d-9b98-74a9b2d2994d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='GridAddandDeleteOptions_pyWorkPage.ApplicationPage.SelectedQuote.KRSpecificDetails_4']</value>
      <webElementGuid>7aa52af6-c36e-4dec-bb14-1741277d9b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add Item')])[3]</value>
      <webElementGuid>6551d051-ed0f-464a-93d7-efd52bf1d6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K&amp;R Endorsements'])[1]/following::a[2]</value>
      <webElementGuid>629d1007-4531-461c-aa9f-542b8deb3831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payable in annual installments'])[1]/following::a[2]</value>
      <webElementGuid>b5c9d9a9-ca5e-4638-a9ef-a1a6a5054f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amended Asset Threshold (AAT) Endorsement'])[3]/preceding::a[3]</value>
      <webElementGuid>9b825206-b208-4258-94e6-76c72459dbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AAT Percentage (%)'])[1]/preceding::a[3]</value>
      <webElementGuid>dc4d46b2-679b-4efe-b33e-471683a3c071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[21]</value>
      <webElementGuid>bb3815ba-2e49-4b64-bdd1-55190a23192a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/table/tbody/tr/td/div/div/div[3]/table/tbody/tr/td/div/div/div/div/div/div/div/div/div/div[2]/div/div/span/a</value>
      <webElementGuid>8c01412a-7386-4ac5-b822-6d3d06863515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'GridAddandDeleteOptions_pyWorkPage.ApplicationPage.SelectedQuote.KRSpecificDetails_4' and (text() = 'Add Item' or . = 'Add Item')]</value>
      <webElementGuid>ae77559f-6ee9-48f5-b053-5f0fdc5e134a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/div/div/div/div[2]/div/div/span/a)[5]</value>
      <webElementGuid>0b73620f-0331-4c79-a457-719ce6cce059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
