<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>7436b402-d22f-450f-92e4-2b33f1de461c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > #CT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button//div//div//div[text()='Update']/ancestor::button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span > #CT</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a96af2ca-cb3f-453a-85b9-145268a94bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CT</value>
      <webElementGuid>61964946-0515-4f03-88d9-732717a82c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>.pyNote</value>
      <webElementGuid>fb6cdeb5-2dc4-4f4f-80a7-b0f83c001c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disable_when</name>
      <type>Main</type>
      <value>SetProgrammeIDData.pyNote=='DontDsplyButton' || SetProgrammeIDData.Comments=='DsplyError' || SetProgrammeIDData.NewComments=='true'</value>
      <webElementGuid>77098472-a4c7-48fa-8bff-815436243e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update </value>
      <webElementGuid>02e77fd1-a2b0-4cd5-864c-333d193cf7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none float-right set-width-auto&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  set-width-auto layout-content-inline content-inline&quot;]/div[@id=&quot;CT&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/div[@id=&quot;CT&quot;]</value>
      <webElementGuid>b0616593-099a-422e-94f9-df5c205a0389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget0Ifr</value>
      <webElementGuid>ee7717a8-501b-442d-91f1-043ee4815a8a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
