<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OtherCommisionAddItem</name>
   <tag></tag>
   <elementGuidId>c87f2706-ce3c-4714-9a61-14625ca6f9d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Add Item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.ProposedQuotes(1)_4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02207290744560978370&quot;] [data-test-id=&quot;\32 015071603054009744126&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10373aa0-4254-4e6a-a5db-387e26bdb36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2015071603054009744126</value>
      <webElementGuid>401afa99-bf49-4e41-82d6-523600184e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>874e7010-4fd1-45dc-b37c-f18d3e8ef593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>0bcf6ac8-232b-4ef9-8d56-e87b7add5c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>cf2dc4db-e850-4a2b-ab97-840e1183c5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.ProposedQuotes(1)_4</value>
      <webElementGuid>e588a0c2-1f76-4cdf-b19b-6b8a9294e09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;doListAction&quot;,[&quot;:event&quot;,[&quot;ADDITEM&quot;,&quot;&quot;, &quot;INSERTAFTER&quot;,&quot;&quot;,&quot;pyNextGenGridModalTemplate&quot;],[&quot;INSERTAFTER&quot;]]]]</value>
      <webElementGuid>7ec72ce4-dc45-4c97-a49c-ae4a5c45bccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add item</value>
      <webElementGuid>3d7f5858-750e-461d-8609-8fc5d42664dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID16&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataLabelWrite gridActionAlignLeft&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex  content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-1   flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex  content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-2   dataValueWrite flex flex-row&quot;]/span[1]/a[1]</value>
      <webElementGuid>67f698c6-b4ba-468a-826e-a3e4a1ff5fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>6b0e0ce8-feb8-4ffa-9164-394dc0f9fe1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.ProposedQuotes(1)_4']</value>
      <webElementGuid>543e122b-e045-4891-8b80-cec535d764d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add item')]</value>
      <webElementGuid>ea83842c-b19a-4930-ad0f-041e87238b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>07a01b72-de3d-4842-b3ba-82d5e5dc4452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items'])[2]/following::a[1]</value>
      <webElementGuid>0a68ecaf-9fd0-4477-8e9f-9d5c67e7add0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TMHCC Fee Amount'])[1]/following::a[1]</value>
      <webElementGuid>a8af557f-a4bf-4ee0-9ced-dcbe46071f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium Information'])[1]/preceding::a[2]</value>
      <webElementGuid>9ab0afa2-4119-443b-9f16-4411fac838a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium Type'])[1]/preceding::a[2]</value>
      <webElementGuid>c949fb9a-17fb-4051-88cf-6387a29ab464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add item']/parent::*</value>
      <webElementGuid>e6ea2814-9eca-4065-bdd3-39b8e5e1b295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pzPegaDefaultGridIcons_pyWorkPage.ApplicationPage.ProposedQuotes(1)_4' and (text() = 'Add item' or . = 'Add item')]</value>
      <webElementGuid>214e9eda-4ee6-4d2b-8b73-b6843e96b7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/a</value>
      <webElementGuid>4c208b35-d39c-436d-8d6b-2c622b73346f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div/div/div/div/div[2]/span/a</value>
      <webElementGuid>5bbfff97-bf30-484e-a936-5c6eae994002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
