<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_ViewAllCases0</name>
   <tag></tag>
   <elementGuidId>136f1d61-a1fb-4aad-8ec1-56ff330f44b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#be6fe132</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[text()='View All FAC RI Quality Check Cases']//preceding-sibling::input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01807250749120152755559&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c362542-aa90-4c5d-848f-9f9ec4ba7393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6e8abdc9-50ce-40ca-92bf-6b92980ed7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201807250749120152755559</value>
      <webElementGuid>a99e2ff9-fa50-4a57-819c-f0b7e992baf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox chkBxCtl </value>
      <webElementGuid>fc19cb71-ac78-4edb-8cb5-5f7df5bdaef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d182e64f-ec59-43bf-a1f2-d0acddf5369d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyDisplayHarness$pViewAllDACases</value>
      <webElementGuid>6568568a-59aa-4cb9-9cbb-4d9616f25e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyDisplayHarness$pViewAllDACasesError </value>
      <webElementGuid>4c63edb4-6d56-41cd-b6ba-5143c2114464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>be6fe132</value>
      <webElementGuid>bf443b66-2034-41b7-bd1c-4689202d86b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>true-false</value>
      <webElementGuid>10cee584-de0a-4da6-b59f-918b24089afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>26cf37a6-670f-4208-84bd-c6029e1e2209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae3b7332-82e4-471f-9a2e-67d9c67a9ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>727b76fb-ffd7-4410-b2fa-db42eb809458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be6fe132&quot;)</value>
      <webElementGuid>fd54f740-2634-4cfd-8aa7-f1df8ecfa608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>a5bf10a9-0665-4744-8751-5ac470c3e225</webElementGuid>
   </webElementProperties>
</WebElementEntity>
