<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_ViewAllCases</name>
   <tag></tag>
   <elementGuidId>59958412-e2d0-4d53-ba14-d2db79e1ce0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#be6fe132</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[text()='View All FAC RI Quality Check Cases']//preceding-sibling::input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01807250749120152755559&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93acb2df-c8b9-423f-beef-4e111eaaf4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d39ef774-f376-4802-b6eb-70711bbed743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201807250749120152755559</value>
      <webElementGuid>d2dd7d45-337e-496a-913c-0ee4cd6e7f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox chkBxCtl </value>
      <webElementGuid>49f5f88f-95b2-4b30-a947-41ee5ecc9bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19d9577f-ff0e-4da5-b058-e503dd77cb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyDisplayHarness$pViewAllDACases</value>
      <webElementGuid>ab1c0197-844b-44fa-9eb8-f937513eb4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyDisplayHarness$pViewAllDACasesError </value>
      <webElementGuid>6832c86c-0c41-4600-b05c-cdfbfcb00662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>be6fe132</value>
      <webElementGuid>bcd67f0a-0714-43a2-a60b-3036ae0166a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>true-false</value>
      <webElementGuid>ee3a66e3-29dc-4a7d-a511-c5cd526be627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>603642a2-ee5c-46db-9211-50b1900c2cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3f85aa79-0bba-4a26-8089-1fd25ad572bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12e95ac3-33ee-4bff-9f61-5d36b46cf2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be6fe132&quot;)</value>
      <webElementGuid>5cd21f18-66ae-42ca-a496-04d53541cc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>f53b1399-ca84-439b-8cea-2659dcdce743</webElementGuid>
   </webElementProperties>
</WebElementEntity>
