<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CBIWaitingPeriod</name>
   <tag></tag>
   <elementGuidId>38cc2fee-09bd-4e59-a4bb-3de4e658d44f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#4a929be1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'pCBIWaitingPeriod')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;\$PpyWorkPage\$pApplicationPage\$pPolicyData\$pCBIWaitingPeriod&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3298ce11-6cd9-40f4-b5c2-9cd0dd683f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2018070213565504191354</value>
      <webElementGuid>853ee887-1588-4963-927e-2a013f82ea50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>ef191a22-312b-40a3-8ab8-2a8ab3c8f151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4a929be1</value>
      <webElementGuid>05961e11-b752-4ec6-9408-99b3802368df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>360a1d0c-0b22-4229-a871-f65cfee3b53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>d8eb1a3e-8e08-4cca-ad4f-45d323fe8ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pPolicyData$pCBIWaitingPeriod</value>
      <webElementGuid>0546fc77-e350-4c71-88e8-011fc8a39dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightJustifyStyle</value>
      <webElementGuid>72ee89b7-c1ab-4c94-a305-ceb7de9d7efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;FieldTrackingChangeForBindproperties&quot;, &quot;PropertyName=CBIWaitingPeriod&quot;, &quot;pyWorkPage.ApplicationPage.PolicyData&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>41359c7e-09ff-4096-a7e8-3c0156a05817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>16b587d6-9e86-4f93-8740-267e30911eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pn</name>
      <type>Main</type>
      <value>.CBIWaitingPeriod</value>
      <webElementGuid>a15583d0-630f-4ac0-82d6-d6f1cd551c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4a929be1&quot;)</value>
      <webElementGuid>fe7384c7-f67d-4170-a77f-67957a965b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>01dceafb-12bb-4d77-8603-5f8e39162585</webElementGuid>
   </webElementProperties>
</WebElementEntity>
