<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sublimit</name>
   <tag></tag>
   <elementGuidId>36f51917-3530-4e1e-bd90-c4aa2d8fad11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acf160dc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@name,'pSublimitPercentage')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;\$PpyWorkPage\$pApplicationPage\$pSelectedQuote\$pSubLimits\$l1\$pSublimitPercentage&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf6b9814-be34-4046-a248-cbae4f8b364e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170118132405018771208</value>
      <webElementGuid>3f221a7e-628d-4fcd-9aaa-b32e5e4f6906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>7b0e05fd-8e97-453f-8dca-3c71357341f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf160dc</value>
      <webElementGuid>52524810-d276-4b58-a098-00213637d27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0c364dde-925a-4a92-9536-bffb2f6fc267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36b0a38b-9681-4327-860b-3c7899bb35c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-formatting</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>fa598611-a5b7-45b8-a1e3-8383dd13e27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>isvalidpercentage,decimal</value>
      <webElementGuid>567373a8-8f54-41d9-8545-e2320ae83ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>780b6016-27e4-4d39-b736-cf5dee9a0df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pSelectedQuote$pSubLimits$l1$pSublimitPercentage</value>
      <webElementGuid>5eebfb45-5958-49bb-8d1b-aea1b70f2ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightJustifyStyle</value>
      <webElementGuid>dad94ec0-4349-4470-9834-bf5304547ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetLayerSublimit,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTMzOGU0NDE4MGY5MDA3OTcwZmU5YTI0ZTIwNjg5M2JiMmRiNDhiZmY2ZWFiZjlmNjZiNGU3MDVlYWYwMzI1NGYzNWU4ZDM2ZTdkNWY0ZjE1OTgxNGU4ZDcwZTE2ZDNhYzU5NmVhNTkzOTJmMjAzMzRhZmVhY2MzYzc2NzdkZjI3MmUwY2NiNTJjZjBjODE1ZGI4OGY3MzNhZGFjM2QyMjcyNDk5Mzg0NWNmMWE3NmFiMTY0NjJlNzYxZGUwMzEyMWM0NjBkZWUzNjcxOTA1ODQ2ZGU4YzRiNjQzYmUwNQ%3D%3D*&quot;,{},{}],&quot;&quot;]]]</value>
      <webElementGuid>c3d90e0f-166a-426e-9821-db13fb75d557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>092b9428-109d-4f81-805a-34305beba5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf160dc&quot;)</value>
      <webElementGuid>fa110e3f-bac2-4457-8ad3-007d563f6ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>e6966869-1909-4153-a27c-439830a5fa8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acf160dc']</value>
      <webElementGuid>b25f06fd-c090-4db4-85e1-a7b5090afc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/table/tbody/tr/td/div/div/div/table/tbody/tr/td[2]/div/table/tbody/tr[2]/td[3]/div/span/input</value>
      <webElementGuid>f070103c-ffd4-41c0-9cd8-9f7956bd715b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'acf160dc' and @type = 'text' and @name = '$PpyWorkPage$pApplicationPage$pSelectedQuote$pSubLimits$l1$pSublimitPercentage']</value>
      <webElementGuid>1b445f4f-19fe-4af5-b058-e4c32c3fcde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PpyWorkPage$pApplicationPage$pSelectedQuote$pSubLimits$l1']/td[3]/div/span/input</value>
      <webElementGuid>a91f57f0-8996-48ab-a93d-f8807d9e2d0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
