<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SublimitSingle</name>
   <tag></tag>
   <elementGuidId>b70f3b30-7fd9-4ab1-8b63-f02ae8f486d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acf160dc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acf160dc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;\$PpyWorkPage\$pApplicationPage\$pSelectedQuote\$pSubLimits\$l1\$pSublimitPercentage&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>544942c3-29f2-4f18-8cda-f2d194c5766d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170118132405018771208</value>
      <webElementGuid>61809324-b9d2-41f3-a992-76c2a72ed73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>e27cbbd4-3983-4d0d-8ad6-b0e269b6d21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acf160dc</value>
      <webElementGuid>d7611489-1cbf-469e-a9f6-476bff5c211f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9f668cf4-6128-4e97-9a40-10b19b27dd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6083c6bf-2923-4ae4-81db-73f9f8b89361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-formatting</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>e6757422-fc7f-4339-870b-cf72e4e20b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>isvalidpercentage,decimal</value>
      <webElementGuid>7d312981-4468-491f-92f9-9e21db0425fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>9af009a1-5e3f-42c7-9f3d-77352958a234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pSelectedQuote$pSubLimits$l1$pSublimitPercentage</value>
      <webElementGuid>c2f153bb-6c3e-4236-bfbf-7410ba20126f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightJustifyStyle</value>
      <webElementGuid>cc15d5f9-d10a-4dec-bab1-38f90ba2bc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;SetLayerSublimit,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTMzOGU0NDE4MGY5MDA3OTcwZmU5YTI0ZTIwNjg5M2JiMmRiNDhiZmY2ZWFiZjlmNjZiNGU3MDVlYWYwMzI1NGYzNWU4ZDM2ZTdkNWY0ZjE1OTgxNGU4ZDcwZTE2ZDNhYzU5NmVhNTkzOTJmMjAzMzRhZmVhY2MzYzc2NzdkZjI3MmUwY2NiNTJjZjBjODE1ZGI4OGY3MzNhZGFjM2QyMjcyNDk5Mzg0NWNmMWE3NmFiMTY0NjJlNzYxZGUwMzEyMWM0NjBkZWUzNjcxOTA1ODQ2ZGU4YzRiNjQzYmUwNQ%3D%3D*&quot;,{},{}],&quot;&quot;]]]</value>
      <webElementGuid>b1399b79-1c66-4b8a-b253-fcf6276fcc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>525608d9-e3be-4407-b6ba-9da2fc74b54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acf160dc&quot;)</value>
      <webElementGuid>751dddd0-cf4d-4d8a-8b89-8f1992eca216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>3110b097-86c1-408a-bc59-aa215dff6a8e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
