<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BIWaitingDropDown</name>
   <tag></tag>
   <elementGuidId>2583650a-e1a1-44ab-8357-486900b79d1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#268943b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'pBIWaitingPeriodType')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\32 68943b&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>484bce79-8e15-4085-b55a-3efeb145fd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>80ac546e-f37c-47a6-aa47-a20fe5786574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2018070213565504191354</value>
      <webElementGuid>ab6e5623-4a33-4ae6-a8dd-4fe81d1ffc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>7d8594f3-575f-4ba5-b48e-8fc8eb3a8263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>268943b</value>
      <webElementGuid>dfaeb03c-a3cb-4d18-a62f-37c8036cd0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pPolicyData$pBIWaitingPeriodType</value>
      <webElementGuid>f191deb6-2634-44a1-808b-fc3d2b85eff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ClearBIFields,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTMzOGU0NDE4MGY5MDA3OTcwZmU5YTI0ZTIwNjg5M2JiMmRiNDhiZmY2ZWFiZjlmNjZiNGU3MDVlYWYwMzI1NGYzNWU4ZDM2ZTdkNWY0ZjE1OTgxNGU4ZDcwZTE2ZDNhYzU5NmVhNTkzOTJmMjAzMzRhZmVhY2MzYzc2NzdkZjAwYTM3OGI4NGJmMjY5YzRjZmRlZGM0OGJjYjExMDM5YTM5Y2YwM2E3MjdmYWJhOTk5Yzk5N2EwOWM2NzY5MjA5ZTY2MDU5YWM5NmM0MjkzY2JiOTJkNzY5N2NkZDZmNDk1YTNmYzk3NjU2NjVlYmFjNmUwYzczNTc5OGM0MDFm*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]],[&quot;runDataTransform&quot;, [&quot;FieldTrackingChangeForBindproperties&quot;, &quot;PropertyName=BIWaitingPeriodType&quot;, &quot;pyWorkPage.ApplicationPage.PolicyData&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>f939981d-8e1b-411a-bca1-81e34a7831bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectHoursMonetary Amount</value>
      <webElementGuid>4884b044-8c21-4c02-9ddf-b0a16cd22b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;268943b&quot;)</value>
      <webElementGuid>d353c1f7-c817-46b8-af20-bf08ef0c835e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>56cdc820-1232-4e7a-8fef-ce55306e8eb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='268943b']</value>
      <webElementGuid>f1f90d7d-2e45-4f6a-a1ab-f73d3d867534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BI Waiting Period in Hours/Monetary Amount'])[1]/following::select[1]</value>
      <webElementGuid>f299cf1b-d998-4882-b1ff-3c58e5f222cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cyber War Exclusions'])[1]/following::select[2]</value>
      <webElementGuid>3d336620-7153-40bc-ab99-78c868b4d3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contingent BI Applicable?'])[1]/preceding::select[1]</value>
      <webElementGuid>0f223d2f-a6af-419d-b8ea-2871f777420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sample text'])[1]/preceding::select[1]</value>
      <webElementGuid>d96bdf9a-683b-4d86-8c96-6f3853b24058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/select</value>
      <webElementGuid>a8ed3a08-9734-44ab-a48d-2254efa27a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '268943b' and @name = '$PpyWorkPage$pApplicationPage$pPolicyData$pBIWaitingPeriodType' and (text() = 'SelectHoursMonetary Amount' or . = 'SelectHoursMonetary Amount')]</value>
      <webElementGuid>a45397d7-a6af-4278-9e7d-62829e47cd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/div/div/div/div/div/div/div/select)[6]</value>
      <webElementGuid>a0ab8726-5723-4057-8e32-d72138a1fc3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
