<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BIWaitingDropDown</name>
   <tag></tag>
   <elementGuidId>2583650a-e1a1-44ab-8357-486900b79d1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#268943b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'pBIWaitingPeriodType')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\32 68943b&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>484bce79-8e15-4085-b55a-3efeb145fd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>80ac546e-f37c-47a6-aa47-a20fe5786574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2018070213565504191354</value>
      <webElementGuid>ab6e5623-4a33-4ae6-a8dd-4fe81d1ffc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>7d8594f3-575f-4ba5-b48e-8fc8eb3a8263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>268943b</value>
      <webElementGuid>dfaeb03c-a3cb-4d18-a62f-37c8036cd0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pPolicyData$pBIWaitingPeriodType</value>
      <webElementGuid>f191deb6-2634-44a1-808b-fc3d2b85eff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ClearBIFields,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTMzOGU0NDE4MGY5MDA3OTcwZmU5YTI0ZTIwNjg5M2JiMmRiNDhiZmY2ZWFiZjlmNjZiNGU3MDVlYWYwMzI1NGYzNWU4ZDM2ZTdkNWY0ZjE1OTgxNGU4ZDcwZTE2ZDNhYzU5NmVhNTkzOTJmMjAzMzRhZmVhY2MzYzc2NzdkZjAwYTM3OGI4NGJmMjY5YzRjZmRlZGM0OGJjYjExMDM5YTM5Y2YwM2E3MjdmYWJhOTk5Yzk5N2EwOWM2NzY5MjA5ZTY2MDU5YWM5NmM0MjkzY2JiOTJkNzY5N2NkZDZmNDk1YTNmYzk3NjU2NjVlYmFjNmUwYzczNTc5OGM0MDFm*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]],[&quot;runDataTransform&quot;, [&quot;FieldTrackingChangeForBindproperties&quot;, &quot;PropertyName=BIWaitingPeriodType&quot;, &quot;pyWorkPage.ApplicationPage.PolicyData&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>f939981d-8e1b-411a-bca1-81e34a7831bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectHoursMonetary Amount</value>
      <webElementGuid>4884b044-8c21-4c02-9ddf-b0a16cd22b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;268943b&quot;)</value>
      <webElementGuid>d353c1f7-c817-46b8-af20-bf08ef0c835e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>56cdc820-1232-4e7a-8fef-ce55306e8eb5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
