<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CBIWaitingDropDown</name>
   <tag></tag>
   <elementGuidId>c8e1394e-b670-4d6a-9f4d-6ccd7610b313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#6617c94d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'pCBIWaitingPeriodType')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;\$PpyWorkPage\$pApplicationPage\$pPolicyData\$pCBIWaitingPeriodType&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fc4ceb09-c505-4bdb-9d64-60a357ed19bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>cfdba6b5-a937-4c44-9e99-54cddbf78642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2018070213565504191354</value>
      <webElementGuid>e8d7a356-8141-45c5-8388-7fcaa637d303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>846f0fc7-0ee5-4ad2-bfc8-427cde164401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6617c94d</value>
      <webElementGuid>70c1603f-f80c-46f0-83d7-f8cc920308b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pPolicyData$pCBIWaitingPeriodType</value>
      <webElementGuid>cf348297-ff14-4626-bab2-9c13bd3b7352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ClearCBIFields,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTMzOGU0NDE4MGY5MDA3OTcwZmU5YTI0ZTIwNjg5M2JiMmRiNDhiZmY2ZWFiZjlmNjZiNGU3MDVlYWYwMzI1NGYzNWU4ZDM2ZTdkNWY0ZjE1OTgxNGU4ZDcwZTE2ZDNhYzU5NmVhNTkzOTJmMjAzMzRhZmVhY2MzYzc2NzdkZjAwYTM3OGI4NGJmMjY5YzRjZmRlZGM0OGJjYjExMDM5YTM5Y2YwM2E3MjdmYWJhOTk5Yzk5N2EwOWM2NzY5MjBmOWI0NTJiZTE4OGI3NDZlZmJjZWM1ODMxMGZjNTc1ZTQ4ZmQyNDcyYWVhZTdmMGZlYzU5Y2MwMjRhOTc0MDBk*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.PolicyData&quot;]],[&quot;runDataTransform&quot;, [&quot;FieldTrackingChangeForBindproperties&quot;, &quot;PropertyName=CBIWaitingPeriodType&quot;, &quot;pyWorkPage.ApplicationPage.PolicyData&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>3fba20e5-54ba-466f-be31-f2800dc76ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectHoursMonetary Amount</value>
      <webElementGuid>24068c0b-fbf8-42d0-8ef3-e4c9a0f6c210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6617c94d&quot;)</value>
      <webElementGuid>25e191f2-8219-4b4b-be64-8d5aac3092d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>7090e1cf-d7d8-426d-9a50-5bb97de29273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='6617c94d']</value>
      <webElementGuid>7e3edc92-a158-4d7f-a50f-eb65a88ff1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBI Waiting Period in Hours/Monetary Amount'])[1]/following::select[1]</value>
      <webElementGuid>49169d52-283c-4892-b12d-8a1151f74a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sample text'])[2]/following::select[1]</value>
      <webElementGuid>1c197f1d-219a-4516-b855-49baeda284a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[8]/preceding::select[1]</value>
      <webElementGuid>50a34ae2-8600-416b-8a80-c3b3fb9c72ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Major Class'])[1]/preceding::select[1]</value>
      <webElementGuid>558a9f39-73eb-4558-a3f5-879aff353c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div/div/div/div/div/select</value>
      <webElementGuid>21f75e54-1bf9-4957-981e-681966bc51f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '6617c94d' and @name = '$PpyWorkPage$pApplicationPage$pPolicyData$pCBIWaitingPeriodType' and (text() = 'SelectHoursMonetary Amount' or . = 'SelectHoursMonetary Amount')]</value>
      <webElementGuid>cb16eecd-36c3-4986-a688-fafd848841b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/div/div/div/div/div/div/div/select)[7]</value>
      <webElementGuid>65f05a4f-48aa-4e22-b66e-933c8dbc4f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
