<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_AddItemLink</name>
   <tag></tag>
   <elementGuidId>312f0fc3-c66b-43ab-9f57-4562a763a377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(text(),'Add Item')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PEGA_GRID28 > #PEGA_GRID_SKIN > #RULE_KEY > table > tbody > tr > td.dataLabelWrite.gridActionAlignLeft > #RULE_KEY > div.layout.layout-none > div.layout-body.clearfix > div.content.layout-content-inline_middle.content-inline_middle > div.content-item.content-layout.item-1 > div.content-inner > div.layout.layout-none > div.layout-body.clearfix > div.content.layout-content-inline_middle.content-inline_middle > div.content-item.content-field.item-2 > div.content-inner > div.field-item.dataValueWrite > span > a[name=&quot;GridAddandDeleteOptions_pyWorkPage.ApplicationPage.SelectedQuote_4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02109031454360087581&quot;] [data-test-id=&quot;\32 018030913301903194833&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73190ff7-64e7-4ad0-bcd0-482ded97bde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2018030913301903194833</value>
      <webElementGuid>f062c5f4-00cb-4747-810b-9fc9e114b022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3fd49ea8-d8cf-436c-8b9e-1875310475c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>a351dea2-0212-4785-8eca-4660b82ed6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>a1af5f62-65a0-4538-88b5-4eaa0e5c0f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GridAddandDeleteOptions_pyWorkPage.ApplicationPage.SelectedQuote_4</value>
      <webElementGuid>b15da46a-a02d-4618-8bb2-abf9e3ace621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;doListAction&quot;,[&quot;:event&quot;,[&quot;ADDITEM&quot;,&quot;&quot;, &quot;INSERTAFTER&quot;,&quot;&quot;,&quot;pyNextGenGridModalTemplate&quot;],[&quot;INSERTAFTER&quot;]]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;Sublimits&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTMzOGU0NDE4MGY5MDA3OTcwZmU5YTI0ZTIwNjg5M2JiMmRiNDhiZmY2ZWFiZjlmNjZiNGU3MDVlYWYwMzI1NGYzNWU4ZDM2ZTdkNWY0ZjE1OTgxNGU4ZDcwZTE2ZDMyMjJlMjk2Nzc2YTk2MDJiMjVlYmI0NzAwODg3ODA1MA%3D%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;Deductible&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTMzOGU0NDE4MGY5MDA3OTcwZmU5YTI0ZTIwNjg5M2JiMmRiNDhiZmY2ZWFiZjlmNjZiNGU3MDVlYWYwMzI1NGYzNWU4ZDM2ZTdkNWY0ZjE1OTgxNGU4ZDcwZTE2ZDMyMjJlMjk2Nzc2YTk2MDJiMjVlYmI0NzAwODg3ODA1MA%3D%3D*&quot;,{},{}],&quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;]]]</value>
      <webElementGuid>26f7d78c-1864-4f0e-a319-461b30a0ed2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Item</value>
      <webElementGuid>3e44e873-d992-4c55-8e37-2bf25ceb3e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID28&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataLabelWrite gridActionAlignLeft&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  layout-content-inline_middle content-inline_middle&quot;]/div[@class=&quot;content-item content-field item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/a[1]</value>
      <webElementGuid>a9cc7da8-8795-4b65-933b-ab62636c7813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>b6051cc9-1f99-4257-a45d-e152de0dba7f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
