<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_SkipQuote</name>
   <tag></tag>
   <elementGuidId>a37cb2bc-f666-4f9f-903e-8dce35d52c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#26e837c6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input/following::label[text()='Skip Quote'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 0210628093632056677&quot;] [data-test-id=&quot;\32 0161113155553033368678&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff858a10-0526-42c9-b7d6-8bd45cf612e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5ab82dd6-e839-4add-b42c-01d0aabe23f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20161113155553033368678</value>
      <webElementGuid>0db7746b-1363-4e6d-bf1f-ae29ad39c6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox chkBxCtl </value>
      <webElementGuid>793ee8e7-c54a-469b-ae1a-89d36cb4cc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5bffbe6-57b6-4a61-bb8b-63aac415c931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pSkipQuote</value>
      <webElementGuid>bf9c187d-d698-4668-a36b-00ba869da979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pSkipQuoteError </value>
      <webElementGuid>b2af8776-bd42-4f38-af24-3d2438f5cbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>26e837c6</value>
      <webElementGuid>ed7e5016-333e-4218-bff7-855ce1148012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>true-false</value>
      <webElementGuid>19769945-1c34-4dd8-abd2-3d0a37315d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Checkbox</value>
      <webElementGuid>39380487-6855-44af-9860-b166df25c9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf07b1b6-19ca-479a-bdad-043d1db44a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cba47848-b7f7-49d3-b7b9-a1607ccff935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;26e837c6&quot;)</value>
      <webElementGuid>e923cb20-68a9-46b8-9133-a11dff131da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>68f33813-2292-4e2c-8a7b-e097916efdb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='26e837c6']</value>
      <webElementGuid>77288a6e-dd26-4cff-82b0-a6528086b689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input[2]</value>
      <webElementGuid>89ecb461-32c3-451c-9755-68f6faa5f5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = '$PpyWorkPage$pSubmissionData$pSkipQuote' and @id = '26e837c6']</value>
      <webElementGuid>1fd758c4-3dee-48f6-a86a-f87655d89bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/input[2]</value>
      <webElementGuid>06d1f393-6655-4923-b9fa-8db9be927eb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
