<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ClearFilter</name>
   <tag></tag>
   <elementGuidId>1d7614dc-e452-42fd-ac01-839004e54607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clearFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='clearFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Clear Filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94a0f948-bbe2-45c1-866c-963282a01a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clearFilter</value>
      <webElementGuid>6173c38b-0dce-4965-9d36-b2c4f4537371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82828234-38d8-450f-9900-434e444edb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter to clear filter</value>
      <webElementGuid>4f6eee15-4bf3-47cc-ada6-e6d27adc6613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear Filter</value>
      <webElementGuid>7da601ce-805e-4b51-81c0-6029c4e6ce45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clearFilter&quot;)</value>
      <webElementGuid>2518593a-808c-429f-8c19-dd0c450c242a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>dfe2892f-1778-423a-8736-da21f5a55239</webElementGuid>
   </webElementProperties>
</WebElementEntity>
