<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ClearFilterPeerReview</name>
   <tag></tag>
   <elementGuidId>4a4e243c-a9cc-4592-899e-a15e9be60aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clearFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='clearFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Clear Filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61b0e0e5-6107-49b5-be12-d69e2baca90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clearFilter</value>
      <webElementGuid>3f8fe610-132b-4225-b6ac-bfdce78f6f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c912f3a7-0f36-40dc-8a4c-1947147cb9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter to clear filter</value>
      <webElementGuid>f9778afe-359f-451a-9b3d-f2a8f0d8b647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear Filter</value>
      <webElementGuid>2fa706d4-cc12-4d42-ba82-7512c11a10f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clearFilter&quot;)</value>
      <webElementGuid>ccf5c0cd-91be-41e3-8a7e-fb5b82b3619a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget0Ifr</value>
      <webElementGuid>1024f52b-2acc-46d6-87ed-b43634e6a0e5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
