<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_PolicyReferenceFilter</name>
   <tag></tag>
   <elementGuidId>e184b347-f2c1-44dd-b9bd-73611ba80c8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a8 > div.oflowDiv > span > #pui_filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@data-attribute-name='Policy Reference']//span//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=columnheader[name=&quot;Policy Reference Click to sort Click to filter&quot;i] >> internal:label=&quot;Click to filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>678678ac-0773-4f64-b131-c5476abec833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pui_filter</value>
      <webElementGuid>6a3ad26f-abcd-4533-add0-7f46f4370c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c1053b43-2feb-4ca4-a814-9d90f4958485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to filter</value>
      <webElementGuid>81fd73bd-fc17-45cb-9cb5-f8ef5b46838f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Click to filter</value>
      <webElementGuid>f4afd8bb-e9b7-410b-83f3-bbadb0094ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>5812b713-daa7-4312-b59c-3886dbcbc681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter highlight-ele</value>
      <webElementGuid>57b8118b-4065-4335-95ea-4870c170bd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filtertype</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aaeee230-a26c-490e-b574-ba11bdd09878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a8&quot;)/div[@class=&quot;oflowDiv&quot;]/span[1]/a[@id=&quot;pui_filter&quot;]</value>
      <webElementGuid>5f2827d9-00de-4254-ad84-3bd2176e20b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>405d1329-1ed1-4993-93e5-61d0a4eacc7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='pui_filter'])[7]</value>
      <webElementGuid>6132a335-9d76-4a68-8427-ae6d72a4fd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Click to filter']</value>
      <webElementGuid>336a2540-e2ba-4423-b216-2c48413845e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]/div/span/a</value>
      <webElementGuid>a0f69e75-1682-487b-8c00-5c0294aacde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='a8']/div/span/a</value>
      <webElementGuid>73833df5-e0ee-4a8c-8baa-90f2346dd918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
