<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ClearFilterPeerReview</name>
   <tag></tag>
   <elementGuidId>4a4e243c-a9cc-4592-899e-a15e9be60aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clearFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='clearFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Clear Filter&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61b0e0e5-6107-49b5-be12-d69e2baca90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clearFilter</value>
      <webElementGuid>3f8fe610-132b-4225-b6ac-bfdce78f6f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c912f3a7-0f36-40dc-8a4c-1947147cb9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter to clear filter</value>
      <webElementGuid>f9778afe-359f-451a-9b3d-f2a8f0d8b647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear Filter</value>
      <webElementGuid>2fa706d4-cc12-4d42-ba82-7512c11a10f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clearFilter&quot;)</value>
      <webElementGuid>ccf5c0cd-91be-41e3-8a7e-fb5b82b3619a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget0Ifr</value>
      <webElementGuid>1024f52b-2acc-46d6-87ed-b43634e6a0e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='clearFilter']</value>
      <webElementGuid>57a7aa76-a91a-4c6c-97fb-66abb43b083d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Clear Filter')]</value>
      <webElementGuid>3c3369e5-6544-4844-811a-f2a84af8b0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No filter applied. filter'])[1]/following::a[1]</value>
      <webElementGuid>21053b29-e927-429d-bd03-15c790e105f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct Primary'])[9]/following::a[1]</value>
      <webElementGuid>fdeb5d4b-9888-443d-bfae-8f6d04b71c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F16H7270A001'])[1]/preceding::a[1]</value>
      <webElementGuid>d948e619-492a-46ed-a0fc-dbf0d1216f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F16H7280A001'])[1]/preceding::a[1]</value>
      <webElementGuid>95a37fe3-c4a1-4b1e-a82f-8f63f86325db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear Filter']/parent::*</value>
      <webElementGuid>4d04597e-6253-4405-9a39-c78b30f96493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Enter to clear filter' and (text() = 'Clear Filter' or . = 'Clear Filter')]</value>
      <webElementGuid>abee8625-aaaf-47b4-8a48-33d7cec20b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>647445b8-e44b-4cc6-841d-7b70a9af8f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/table/tbody/tr/td[2]/nobr/label/a</value>
      <webElementGuid>a8868053-18d9-4c21-9703-fa8908a943c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
