<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_FinalisePolicyPrompt</name>
   <tag></tag>
   <elementGuidId>04f5e05c-c2a4-490f-a96d-871adca7a39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modaldialog_hd_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id = 'modaldialog_hd_title' and (text() = '        Finalise Policy Prompt       ' or . = '        Finalise Policy Prompt       ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modaldialog_hd_title</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d7f6824e-74ab-4093-b545-e70691e3d39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modaldialog_hd_title</value>
      <webElementGuid>9bfc0590-077f-4fb7-89fc-45799aa4e6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        Finalise Policy Prompt       </value>
      <webElementGuid>ece07c5d-fea0-4083-8317-2c07389cd2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modaldialog_hd_title&quot;)</value>
      <webElementGuid>b9aa32cc-6c99-4688-b402-25b20c1f30d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>929caeee-6df0-4bab-81a6-b6d3cc13a626</webElementGuid>
   </webElementProperties>
</WebElementEntity>
