<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ListMailHeader</name>
   <tag></tag>
   <elementGuidId>ea4f33d9-be3c-45a7-b3b9-a2bba62a389d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//label[contains(@class,'Label_Label')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
