<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_SelectQuotePrompt</name>
   <tag></tag>
   <elementGuidId>4964b6b0-d554-4585-82f4-c715c0fb009a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modaldialog_hd_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id = 'modaldialog_hd_title' and (text() = '        Select Quote       ' or . = '        Select Quote       ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modaldialog_hd_title</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00087173-c388-4fd9-b03d-a8fc75d1a4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modaldialog_hd_title</value>
      <webElementGuid>451a87f4-6153-4537-978a-48f2b1dbe6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        Select Quote       </value>
      <webElementGuid>955b15a0-a84f-4889-98de-add7dea90e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modaldialog_hd_title&quot;)</value>
      <webElementGuid>b4072e61-2960-45c5-b299-a41bede89e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Documentation/PolicyCreation/iframe_PegaGadget1Ifr</value>
      <webElementGuid>11b822a0-2021-4a52-b47f-69600f1137e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='modaldialog_hd_title']</value>
      <webElementGuid>912ffbd3-198a-4875-944b-e17ac3682907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Quote'])[2]/preceding::span[1]</value>
      <webElementGuid>9d96824a-46ef-403b-b84b-04f4625dc913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A maximum of 4 quotes can be selected for a Quote document generation'])[1]/preceding::span[2]</value>
      <webElementGuid>f9d7a3b8-24cf-4599-8013-dfbcd60861a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Quote']/parent::*</value>
      <webElementGuid>adf519f2-e378-4a73-b3ad-09e025b0fc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>d56ac1e2-d465-4e8e-ae14-2d541ad77a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'modaldialog_hd_title' and (text() = '        Select Quote       ' or . = '        Select Quote       ')]</value>
      <webElementGuid>05cda874-98ed-4ff9-93a9-1c6cbd5984bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modaldialog_hd']/span</value>
      <webElementGuid>71ea16d3-382e-43ce-890f-612606001b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
