<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_SendMailLabel</name>
   <tag></tag>
   <elementGuidId>2bc958f2-4eab-49d1-a273-68689991550b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[(text() = 'Send' or . = 'Send')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Button_Button__2RCPc.Button_ButtonSmall4__3k7dB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Send&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fde00224-41bc-4e7e-86c0-fc662a092af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_Button__2RCPc Button_ButtonSmall4__3k7dB</value>
      <webElementGuid>b946ba75-b5c0-4480-985c-658fb9ce255b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>76c7bdee-7d5c-48c4-94ff-4b2dc64516d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[1]/div[@class=&quot;htmlMail_Auth__3mkXH&quot;]/div[@class=&quot;htmlMail_buttoncont__mcUHf&quot;]/button[@class=&quot;Button_Button__2RCPc Button_ButtonSmall4__3k7dB&quot;]</value>
      <webElementGuid>3e1a1dd5-2ce3-4b50-a5d2-82a2ba06dbec</webElementGuid>
   </webElementProperties>
</WebElementEntity>
