<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_FinalisePolicyPrompt</name>
   <tag></tag>
   <elementGuidId>04f5e05c-c2a4-490f-a96d-871adca7a39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modaldialog_hd_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id = 'modaldialog_hd_title' and (text() = '        Finalise Policy Prompt       ' or . = '        Finalise Policy Prompt       ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modaldialog_hd_title</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d7f6824e-74ab-4093-b545-e70691e3d39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modaldialog_hd_title</value>
      <webElementGuid>9bfc0590-077f-4fb7-89fc-45799aa4e6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        Finalise Policy Prompt       </value>
      <webElementGuid>ece07c5d-fea0-4083-8317-2c07389cd2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modaldialog_hd_title&quot;)</value>
      <webElementGuid>b9aa32cc-6c99-4688-b402-25b20c1f30d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Documentation/PolicyCreation/iframe_PegaGadget1Ifr</value>
      <webElementGuid>929caeee-6df0-4bab-81a6-b6d3cc13a626</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='modaldialog_hd_title']</value>
      <webElementGuid>81678146-c8a6-4673-947c-16d5a51d683d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finalise Policy Prompt'])[2]/preceding::span[1]</value>
      <webElementGuid>5b86957d-0556-4de0-b443-42b40c41697a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[2]</value>
      <webElementGuid>8be2fedb-ceb3-4fae-9b59-f40ab7eeede6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalise Policy Prompt']/parent::*</value>
      <webElementGuid>50d3d9bc-b639-42f2-a768-9eaedae031c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>240e3e68-5cb6-496f-b8c3-46194fede458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'modaldialog_hd_title' and (text() = '        Finalise Policy Prompt       ' or . = '        Finalise Policy Prompt       ')]</value>
      <webElementGuid>1e29bd0b-b464-4e2e-a90d-d2f9e756f9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modaldialog_hd']/span</value>
      <webElementGuid>16797ac9-5276-4aa3-9260-c3c15f968aff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
