<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_FinalisePolicyPrompt1</name>
   <tag></tag>
   <elementGuidId>04f5e05c-c2a4-490f-a96d-871adca7a39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modaldialog_hd_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id = 'modaldialog_hd_title' and (text() = '        Finalise Policy Prompt       ' or . = '        Finalise Policy Prompt       ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modaldialog_hd_title</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b5da219-5993-4f96-ac71-225a75909580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modaldialog_hd_title</value>
      <webElementGuid>98d8f7b1-75d5-4191-a5a3-45f79c35af1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        Finalise Policy Prompt       </value>
      <webElementGuid>d2544ea2-4585-4cfe-8acd-8ab21cb6cf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modaldialog_hd_title&quot;)</value>
      <webElementGuid>35c060ef-583f-4da9-b4d6-b20bd52d9fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Documentation/PolicyCreation/iframe_PegaGadget2Ifr</value>
      <webElementGuid>6e5295f0-28cf-44a0-9081-411cb3558563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='modaldialog_hd_title']</value>
      <webElementGuid>9277ec53-863f-4ae4-b2a3-363cd3c91c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finalise Policy Prompt'])[2]/preceding::span[1]</value>
      <webElementGuid>1ab5efd9-8dcd-4f0c-bab2-7d8dcc2fde92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[2]</value>
      <webElementGuid>4bfb5712-af9d-41aa-81be-95db209d160d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalise Policy Prompt']/parent::*</value>
      <webElementGuid>668a43ea-31a1-4ec7-a79a-2dfe008cd235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>f70002ce-aa9c-4dd8-ba60-68c59f3bff63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'modaldialog_hd_title' and (text() = '        Finalise Policy Prompt       ' or . = '        Finalise Policy Prompt       ')]</value>
      <webElementGuid>9ee5eac9-2e58-45fd-a0c0-5d71a84bb584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modaldialog_hd']/span</value>
      <webElementGuid>120fc39a-5131-452a-b123-5dcd6647affb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
