<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_CurrentlyOpen</name>
   <tag></tag>
   <elementGuidId>b34d139a-7531-4a60-87f2-ee0829c40f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.textIn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='layout-group-tablist-menu']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Currently open&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9ffc04ec-a59e-4192-bea1-e3539166bbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textIn</value>
      <webElementGuid>453dc9f1-aee3-4389-ad21-d1bbd914047d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>e51e01f6-34f7-48ec-b5b2-34b1554e26a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_TABBED0&quot;)/div[@class=&quot;scrlCntr&quot;]/ol[@class=&quot;yui-nav tsb-menu tab-ul tab-ul-t tab-ul-t-ns  headerTabsList&quot;]/li[@class=&quot;tab-li tab-li-t tab-li-t-ns&quot;]/a[@id=&quot;TABANCHOR&quot;]/span[@id=&quot;TABSPAN&quot;]/span[@class=&quot;textMiddle&quot;]/span[@class=&quot;textIn&quot;]</value>
      <webElementGuid>bb13d4ac-353f-49e9-8b5f-796d8f0ba729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>407d9d4f-4609-42b0-b92e-14da36314946</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance'])[1]/following::span[4]</value>
      <webElementGuid>ff3bffbc-a504-475f-9475-761a54bd184d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placing Type :'])[1]/following::span[5]</value>
      <webElementGuid>62da40c2-0ff1-4a6b-aabe-92b83708982d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::span[1]</value>
      <webElementGuid>e0eefb69-30a8-4ee8-a3d9-fa4e4122bba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insured'])[1]/preceding::span[5]</value>
      <webElementGuid>af634f4e-50da-471c-a767-a09e78e68389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='▼']/parent::*</value>
      <webElementGuid>1d1ea37e-1f71-431f-ab9e-c210b353e486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>0b330b37-d4ea-4a9e-918f-efacc5da3afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '▼' or . = '▼')]</value>
      <webElementGuid>6fe09fc5-2909-4a2c-8d2e-1a6ee4029461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='TABSPAN']/span/span</value>
      <webElementGuid>22eb31e4-475e-4895-a822-75e9777ef8a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
