<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_expandRow0</name>
   <tag></tag>
   <elementGuidId>4a947bcf-ed5f-49de-8f19-50b6396609e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='expandRowDetails']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.expandRowDetails</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;press enter to expand row&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4304de14-9f70-4aed-aaba-225c89e35542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43f5698a-7739-4bc6-9d98-0d818bd88432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>expCollIcon</value>
      <webElementGuid>d49a728f-9530-4ad9-b768-42a033fe1389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;doGridAction&quot;,[&quot;:event&quot;,&quot;EDITITEM&quot;]]]</value>
      <webElementGuid>c8021ace-3ebb-4239-9c48-59c2f14f9b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keyup</name>
      <type>Main</type>
      <value>[[&quot;doGridAction&quot;,[&quot;:event&quot;,&quot;EDITITEM&quot;],null,&quot;enter&quot;]]</value>
      <webElementGuid>5e8da2de-a8dc-4819-b658-1be67c3ec510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expandRowDetails</value>
      <webElementGuid>f9c3df43-7041-426d-93b6-cad0c1ea6bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>press enter to expand row</value>
      <webElementGuid>26bcc038-d262-4a93-82c9-fc7f5287037a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>press enter to expand row</value>
      <webElementGuid>6a7d2e66-0d63-4947-9311-f382a53bcf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PEndorsementVersionPage$pEndorsementVersions$l1&quot;)/td[@class=&quot;expandPane    rowHandle oddRow&quot;]/span[@class=&quot;expandRowDetails&quot;]</value>
      <webElementGuid>6e2d34f1-ac03-45ad-9636-1973d8c3dc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget0Ifr</value>
      <webElementGuid>a07320ed-f550-41b9-9222-785053da76db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
