<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_CurrentlyOpen0</name>
   <tag></tag>
   <elementGuidId>ae490580-bade-4e5a-9911-3740977e986e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.textIn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='layout-group-tablist-menu']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Currently open&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a589c4a4-0056-4661-b1a3-20ac5967e629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textIn</value>
      <webElementGuid>9c31776e-13b4-4522-86f0-7f486eaf2a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>bd0f4925-5d17-4029-9d5c-aef29130cbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_TABBED0&quot;)/div[@class=&quot;scrlCntr&quot;]/ol[@class=&quot;yui-nav tsb-menu tab-ul tab-ul-t tab-ul-t-ns  headerTabsList&quot;]/li[@class=&quot;tab-li tab-li-t tab-li-t-ns&quot;]/a[@id=&quot;TABANCHOR&quot;]/span[@id=&quot;TABSPAN&quot;]/span[@class=&quot;textMiddle&quot;]/span[@class=&quot;textIn&quot;]</value>
      <webElementGuid>808347a0-6685-483b-b988-6c16461ac88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget0Ifr</value>
      <webElementGuid>9666cbec-3f43-4468-8c73-8ed5bd4f6424</webElementGuid>
   </webElementProperties>
</WebElementEntity>
