<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_expandRow</name>
   <tag></tag>
   <elementGuidId>d348ed68-1a66-44c8-aca6-3eda06cf3d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='expandRowDetails']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.expandRowDetails</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;press enter to expand row&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9690a72c-8aa1-4b0e-98f4-dc1170f032ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d144481-dcfa-49f9-864e-5c3ae752e57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>expCollIcon</value>
      <webElementGuid>549dc738-7eed-467f-9e7f-3b50c2248ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;doGridAction&quot;,[&quot;:event&quot;,&quot;EDITITEM&quot;]]]</value>
      <webElementGuid>e5d6725a-ad0d-4c4a-97f5-183a4b37d80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keyup</name>
      <type>Main</type>
      <value>[[&quot;doGridAction&quot;,[&quot;:event&quot;,&quot;EDITITEM&quot;],null,&quot;enter&quot;]]</value>
      <webElementGuid>bd692d2e-d75f-4c07-8c53-ce4f0c9b2c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expandRowDetails</value>
      <webElementGuid>811d2015-c674-4d87-a17e-dbe821241e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>press enter to expand row</value>
      <webElementGuid>22db5b6b-5f58-4695-8232-3a2b78defb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>press enter to expand row</value>
      <webElementGuid>abdb22e7-52b2-4336-bdfa-ab8a72a504dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PEndorsementVersionPage$pEndorsementVersions$l1&quot;)/td[@class=&quot;expandPane    rowHandle oddRow&quot;]/span[@class=&quot;expandRowDetails&quot;]</value>
      <webElementGuid>9311f72c-ab06-44a7-b7d2-ca8cc010eed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_PegaCaseManagerPortal/iframe_PegaGadget1Ifr</value>
      <webElementGuid>2d79c129-1c7b-47d9-be28-0b23efc532d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>fd852eb6-03a6-4cca-86f8-b9e90b76188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'press enter to expand row' and @alt = 'press enter to expand row']</value>
      <webElementGuid>1d9c2d40-6e9b-461f-a189-c6986bbf8a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PEndorsementVersionPage$pEndorsementVersions$l1']/td/span</value>
      <webElementGuid>a29c49cf-b0b0-4f90-b495-a1e82abddf85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
