<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Applies to_pzSearchResultName_pySearchRes_4bbed7</name>
   <tag></tag>
   <elementGuidId>62392923-f8af-44c0-a194-d1becb56ef1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='pzSearchResultName_pySearchResults.pxResults(1)_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pzSearchResultName_pySearchResults.pxResults(1)_3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01703010545400626496-R1&quot;] [data-test-id=&quot;\32 0180627085938070533&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc668bc9-273e-4a2f-b47f-ba9a3de6ed95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20180627085938070533</value>
      <webElementGuid>5d8b7e1e-450e-4a4b-92d8-d9fb68a5879d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>737c2317-09b6-4829-ada6-025c6ae8829b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>43b53489-7e05-4873-afd5-194810eb70d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>995b6af2-2414-4a63-a530-48df014c5a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzSearchResultName_pySearchResults.pxResults(1)_3</value>
      <webElementGuid>232ae1ee-4949-49a6-bff5-1a213aa20c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;closeContainer&quot;,[&quot;:event&quot;]],[&quot;runScript&quot;, [&quot;top.OpenRuleInPortalByInsName(\&quot;#~pySearchResults.pxResults(1).pzCategoryActionKeys~#\&quot;,\&quot;#~pySearchResults.pxResults(1).pxInsName~#\&quot;)&quot;]],[&quot;openRuleByClassAndName&quot;,[&quot;#~pySearchResults.pxResults(1).pxInsName~#&quot;,&quot;#~pySearchResults.pxResults(1).pzCategoryActionKeys~#&quot;,&quot;&quot;,&quot;&quot;]]]</value>
      <webElementGuid>1a1d3fd4-a147-4859-b5ee-ad1601689f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>D_MasterRefData</value>
      <webElementGuid>5c7f2763-2e8b-45d7-9f59-fd6785c79753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PpySearchResults$ppxResults$l1&quot;)/td[@class=&quot;gridCell  gridCellSelected&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataValueRead&quot;]/nobr[1]/span[1]/a[1]</value>
      <webElementGuid>c94c0a75-48d9-4422-9d79-157a26db79f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
