<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Page management_pzbtn-mid</name>
   <tag></tag>
   <elementGuidId>d3ba13f0-5320-45fa-9b62-dc130d3bb019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/div/div/button/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pzbtn-mid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 014101603213008475419&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9770ffa3-4e6e-450c-a603-c189e0c81303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pzbtn-mid</value>
      <webElementGuid>6674d706-679d-4a75-8d49-61c929fb1039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>....</value>
      <webElementGuid>d0532f78-5faa-425d-8f04-841693284691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear data page</value>
      <webElementGuid>bf016a34-b99c-46a6-a500-58b8561ddfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INNERDIV-SubSectionpzInnerRuleFormLayoutBB&quot;)/div[@id=&quot;RULE_KEY&quot;]/div[@id=&quot;EXPAND-OUTERFRAME&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-field item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/button[@class=&quot;pzhc&quot;]/div[@class=&quot;pzbtn-rnd&quot;]/div[@class=&quot;pzbtn-lft&quot;]/div[@class=&quot;pzbtn-rgt&quot;]/div[@class=&quot;pzbtn-mid&quot;]</value>
      <webElementGuid>10f3662f-2b22-4d3a-9898-f17f7865da18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Login_Page/Page_Pega Dev Studio/iframe_Security guide not configured_PegaGa_477f98</value>
      <webElementGuid>0f6718ab-ad32-4f7f-b917-f35d34c40605</webElementGuid>
   </webElementProperties>
</WebElementEntity>
