<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>8f7132a1-ba37-488b-9315-f5a818292742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pzRuleFormToolbarSave_RH_1_8&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01805050354190319333&quot;] [data-test-id=&quot;\32 014102117201604205631&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c52761c4-2414-4fcd-97ad-188469fd146d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2014102117201604205631</value>
      <webElementGuid>3af08826-79dc-4435-95d6-3d65d3cafc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;setValue&quot;, [[&quot;RH_1.pyToolbarSaveLabel&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;Saving&quot;], [&quot;RH_1.pyRMAction.pyAction&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;save&quot;]]],[&quot;runScript&quot;, [&quot;postPRXML()&quot;]],[&quot;runScript&quot;, [&quot;onBeforeExecuteActionWrapper(\&quot;SAVE\&quot;,\&quot;#~RH_1.pzInsKey~#\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;launchStaleAction(this,event,\&quot;#~RH_1.pzInsKey~#\&quot;,\&quot;#~RH_1.pxUpdateDateTime~#\&quot;,\&quot;save\&quot;,\&quot;#~RH_1.pyIsStaleRuleCheckEnabled~#\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;clearQueueForStaleHandling(\&quot;#~RH_1.pyIsStaleRuleCheckEnabled~#\&quot;)&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;RH_1&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iOWI5MjE3NjY4NDIwNzZhMGFhZTQwYmYyMDhkZThlYjJjMjBhNmZmNjJkYWE5MGZiNzAzNGExZDRhNTUxMDJlZjhlNWE4MjUzYWNmYjc1M2FmZTdiYTkwNGY3M2QyZTUyYzg5M2I2Y2Y1MGJiYzc5MDcyYWEwMGZmZWQyYTJlOWE3ZmU1OTdmMTU3YzM0ODMxNWM1NjViMzJlNTk5MDNmODlhZDMxZDhiOTExNDI2MGM2OTk1MjQwNjdjZmEzZGU5YmQzOGVhNjNiNmZhMDcxZDk0MTlkZmYyYTQ5YWY1MTk5MTQ0YWQ5MWExODZiZGUyOGM0OTFiM2MzOTIzZjczNmViNzQxNjAyZGVmM2QwNzZlYjNlYTc3NmYwYmViY2VmOGJmN2Y3MjVmYWFlMzQ5NDkyZGVkYTU3MWQ2YzRjNw%3D%3D*&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PRH_1$ppxObjClass&quot;,&quot;=&quot;,&quot;Rule-HTML-Harness&quot;,&quot;false&quot;]]]],[&quot;runScript&quot;, [&quot;postRuleFormValues(\&quot;pzRuleFormToolbarAction\&quot;,\&quot;ToolbarAction=Save\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;clearDirtyFlags(\&quot;\&quot;,\&quot;#~RH_1.pyRuleFormStatus~#\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;pzGetFormBasedXML(\&quot;SAVE\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;clearQueueConditionally(\&quot;#~RH_1.pyRuleFormStatus~#\&quot;,\&quot;#~RH_1.pyRuleFormStatusOld~#\&quot;)&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;RuleFormMain&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;pzSetSaveLabel,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX02OTFjNjYyYzRlOTk2NTNlY2Q3NDM4ZTJiNGViMzllYTkzZDE0ZDI1ODQ5OTU4NTBhZmQwYjg0NmI2OWRiYmU1MDdjOTJmN2Y1ZWQ1NDIyM2JhYWZlNjIwOWExNjc1NWFkMDg3YmU2YWMxMDQ0YWEzNTFlZjU5MGJiZjMyYTljNmEyN2MzMWFmMjEzMTBjZGRkMzdiYTllMzk0NWQ5NWNkNWU4YTdkMTg2N2I2NGNjZGFhZmRmMWY2YzAyNWMwYWM%3D*&quot;,{},{}],&quot;RH_1&quot;]],[&quot;runScript&quot;, [&quot;setDirtyFlag(\&quot;\&quot;,\&quot;#~RH_1.pyRuleFormStatus~#\&quot;)&quot;]],[&quot;runDataTransform&quot;, [&quot;pzRemoveWorkPage&quot;, &quot;=&quot;, &quot;RH_1&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>d5b849c6-097c-4715-932c-2fde72769942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzRuleFormToolbarSave_RH_1_8</value>
      <webElementGuid>7d543398-7130-4a7b-8688-04792f7ff7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>277508a3-34da-4880-bce2-7325d86e045f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6484fd48-d258-432c-b068-1abd98562cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save your changes to this record</value>
      <webElementGuid>b577313c-367c-49dc-b0c6-55b0d633096d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>59a7e3dd-9ea2-4fac-8a63-bf330d1872dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harness-container&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;harnessBodyNoHead&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@class=&quot;noHeadExpandInnerDivStyle&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@class=&quot;noHeadExpandInnerDivStyle&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-ruleform_header&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle auto-width-column flex-grow-1-item-2&quot;]/div[@class=&quot;content-item content-layout item-2 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  flex-dir-row-reverse ruleform-header-actions&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-all-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  rule-actions nowrap right-aligned&quot;]/div[@class=&quot;content-item content-sub_section item-6 remove-top-spacing remove-bottom-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing set-width-auto flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle set-width-auto pzRuleFormToolbarSave&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-split_button  content-split_button&quot;]/div[@class=&quot;content-item content-field item-1 flex flex-row split-left hotkey-ruleform-save dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>da8e3dd6-0815-4da9-bb1a-f35cae1515bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>dc8bc213-ff42-4643-82be-c4948071261b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
