<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ActivityOption</name>
   <tag></tag>
   <elementGuidId>6e6b0e0d-610e-4e3e-95ec-9bc4a667c119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pzRulesExplorerNode_D_RulesExplorerData.pxResults(15).pxResults(1)_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Activity')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Activity&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25c988ab-7fcb-47f7-a9af-a9de57244000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2015082505545203631273</value>
      <webElementGuid>f013ce21-bb49-48c6-8d28-7a031badca9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>05bb0c4e-5154-455e-9e20-38a5eb23bdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>64bd7ae8-9abd-4f56-972b-9aedefe460bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>6e04d945-8d0f-48a2-a4a0-d92be975f343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzRulesExplorerNode_D_RulesExplorerData.pxResults(15).pxResults(1)_1</value>
      <webElementGuid>7f1d2e41-ad9c-4185-860d-ea9d320e597d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View the instance list for this item</value>
      <webElementGuid>964fe848-e446-4a32-9976-55f9237245d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>explorer_primary</value>
      <webElementGuid>b2cc794f-2950-408a-b07f-5b0b7606d6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activity</value>
      <webElementGuid>33975eec-26d6-4aef-8b80-6dfea565edb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridNode0&quot;)/li[@id=&quot;$PD_RulesExplorerData$ppxResults$l15&quot;]/ul[@id=&quot;gridNode&quot;]/li[@id=&quot;$PD_RulesExplorerData$ppxResults$l15$ppxResults$l1&quot;]/ul[@class=&quot;rowContent gridCellSelected&quot;]/li[@class=&quot;dataLabelRead cellCont gridColumn gridCellSelected&quot;]/div[@class=&quot;oflowDiv&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none has-action&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;content  pointer  layout-content-simple_list content-simple_list&quot;]/div[@class=&quot;content-item content-field item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueRead&quot;]/span[1]/a[@class=&quot;explorer_primary&quot;]</value>
      <webElementGuid>c1ff82e2-c1f5-4d41-bc41-c6cffed68504</webElementGuid>
   </webElementProperties>
</WebElementEntity>
