<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ActivityOption</name>
   <tag></tag>
   <elementGuidId>6e6b0e0d-610e-4e3e-95ec-9bc4a667c119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;pzRulesExplorerNode_D_RulesExplorerData.pxResults(15).pxResults(1)_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Activity')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Activity&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25c988ab-7fcb-47f7-a9af-a9de57244000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2015082505545203631273</value>
      <webElementGuid>f013ce21-bb49-48c6-8d28-7a031badca9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>05bb0c4e-5154-455e-9e20-38a5eb23bdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pd(event);</value>
      <webElementGuid>64bd7ae8-9abd-4f56-972b-9aedefe460bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>6e04d945-8d0f-48a2-a4a0-d92be975f343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzRulesExplorerNode_D_RulesExplorerData.pxResults(15).pxResults(1)_1</value>
      <webElementGuid>7f1d2e41-ad9c-4185-860d-ea9d320e597d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View the instance list for this item</value>
      <webElementGuid>964fe848-e446-4a32-9976-55f9237245d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>explorer_primary</value>
      <webElementGuid>b2cc794f-2950-408a-b07f-5b0b7606d6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activity</value>
      <webElementGuid>33975eec-26d6-4aef-8b80-6dfea565edb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridNode0&quot;)/li[@id=&quot;$PD_RulesExplorerData$ppxResults$l15&quot;]/ul[@id=&quot;gridNode&quot;]/li[@id=&quot;$PD_RulesExplorerData$ppxResults$l15$ppxResults$l1&quot;]/ul[@class=&quot;rowContent gridCellSelected&quot;]/li[@class=&quot;dataLabelRead cellCont gridColumn gridCellSelected&quot;]/div[@class=&quot;oflowDiv&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none has-action&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;content  pointer  layout-content-simple_list content-simple_list&quot;]/div[@class=&quot;content-item content-field item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueRead&quot;]/span[1]/a[@class=&quot;explorer_primary&quot;]</value>
      <webElementGuid>c1ff82e2-c1f5-4d41-bc41-c6cffed68504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='pzRulesExplorerNode_D_RulesExplorerData.pxResults(15).pxResults(1)_1']</value>
      <webElementGuid>3e9f4e2f-5919-4bea-b232-857ad2005c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Activity')]</value>
      <webElementGuid>c4d3b1c4-ce66-420c-b272-51d7ac4621c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical'])[1]/following::a[2]</value>
      <webElementGuid>31420856-aef6-4e91-b3e6-e4dce89ad174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SysAdmin'])[1]/following::a[69]</value>
      <webElementGuid>32b0d668-c809-4921-bc09-590241869bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Interface'])[1]/preceding::a[36]</value>
      <webElementGuid>fecb1b16-bddf-4c11-afc5-67cc29d5c16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorites'])[1]/preceding::a[36]</value>
      <webElementGuid>96e73bd5-6413-4b55-8a8f-4f91825d575d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[97]</value>
      <webElementGuid>ccb5f882-0a2e-4cee-a621-9b92d48e0df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @name = 'pzRulesExplorerNode_D_RulesExplorerData.pxResults(15).pxResults(1)_1' and @title = 'View the instance list for this item' and (text() = 'Activity' or . = 'Activity')]</value>
      <webElementGuid>9699c2aa-7d3c-4529-bb2d-fd175ef0deb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[16]/ul[2]/li/ul/li[2]/div/div/div/div/div/div/div/div/span/a</value>
      <webElementGuid>d0efacd3-1bf5-49a4-9b28-0828e832b511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/div/span/a)[37]</value>
      <webElementGuid>8727731b-2bd4-4f0a-a0a8-d482f7a3d92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
