<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CalculateRatios</name>
   <tag></tag>
   <elementGuidId>dcd413d6-944b-4aa7-9659-0475d665bdfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pzbtn-mid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Calculate Ratios']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b42c47d6-6d2a-4523-a854-55b2175a4387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pzbtn-mid</value>
      <webElementGuid>795181f3-f969-41e8-8c59-91dcdc6ae8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>....</value>
      <webElementGuid>e84af27f-699d-482a-8f17-bdcafb90ba3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>35e68e40-c71b-4806-9fb3-7fe965be595d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none float-right set-width-auto&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content  set-width-auto layout-content-inline content-inline&quot;]/div[@class=&quot;content-item content-field item-1 remove-left-spacing&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/button[@class=&quot;pzhc&quot;]/div[@class=&quot;pzbtn-rnd&quot;]/div[@class=&quot;pzbtn-lft&quot;]/div[@class=&quot;pzbtn-rgt&quot;]/div[@class=&quot;pzbtn-mid&quot;]</value>
      <webElementGuid>b259a8a9-359b-4416-997a-0a06526389b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget2Ifr</value>
      <webElementGuid>e8cfcd7e-4d1e-418f-a9ef-a611c3a25702</webElementGuid>
   </webElementProperties>
</WebElementEntity>
