<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ExpiryDate</name>
   <tag></tag>
   <elementGuidId>3c030acb-3e70-40a1-a48c-1c0c630a8902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name='ExpirationDate')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#565d6bc3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Expiry Date&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf80ae78-0343-452b-a8d9-c9ad77fa33b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef01f03f-0339-461c-b5c3-6a2fb6823698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>565d6bc3</value>
      <webElementGuid>c3458246-74e0-4a74-9a48-b31456482aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pApplicationPage$pSelectedQuote$pExpirationDate</value>
      <webElementGuid>ad6dd60a-240f-4164-a931-0daa43c57c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;DatePicker&quot;]</value>
      <webElementGuid>a889c424-f579-46c9-9640-b5698801cab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20170201070101025711805</value>
      <webElementGuid>9823bda9-f0ce-4dd3-b79e-d89cf7b6b819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autoseparator</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e7f2a58-f549-4a69-88ad-7ce4728554c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactvDtTmTxt</value>
      <webElementGuid>d7cd3d77-9fa1-4e09-9154-3b4b2d532f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>e4abc0be-96ac-47c1-8f20-361dde9a5451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;IsLeapYear&quot;, &quot;=&quot;, &quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;,&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;CalculateDateOrPeriod,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTcwOTcyMGFhYzk3ZDM5ZWY2M2MwYTk4YzAzODg5ZjcxYmMwOTgwMDU2ODQxM2RjNDliMzdiYTlkN2M3MDlkMjAyYzhjNTEwZmFlNzEyMzU3ZDNjMjEzOWQ2MDFhZTBkNDNmN2UzYjUxY2FiZWM1MjU3ODMxMzNhZmE4NjhjMWU5YWI4NzVhZGY5NWU1NjcxY2YwMDU5MGJmODI0NWJiOTM5MmI1ZmMwOTdhNWNkM2ZlY2YzYjVkY2NmZmRlODQ4YjE2OTkyYTk0ZDEzZDJiYjE3Zjc4OWI1YzkwZmI4YmI1N2NlNjdmOWI0Yjg3MGUyMGZlNjQ0MWY3MTdiY2U4ZTRlYjY2MTY0ZGU0NTQ0ZTFmNGU5YmU4NWM2ZTdiOGZlZWRmOTI4YzBlNjBjYzU1ZGU4Y2NkMmRlN2Q0NGJhMzc2MjRlMzFkMzcwMGM2YzI2Y2U2MGRhYjNjNjVhYjJhNmExYmQwZWZiMTc3YmJhMGU5YjcxNWVhMmNjYWIyZTI3MmUyMDE4ZWQ0NDhkNDQwYmVhMTkxZWI4N2Y1OTM3ZjBk*&quot;,{},{&quot;IsInceptionDate&quot;:&quot;&quot;,&quot;IsExpiryDate&quot;:&quot;true&quot;,&quot;IsPeriod&quot;:&quot;&quot;,&quot;spa&quot;:&quot;&quot;}],&quot;pyWorkPage.ApplicationPage.SelectedQuote&quot;]]]</value>
      <webElementGuid>f8d44669-3bed-4b0b-8d14-81020675a75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a54511f-7738-4cb3-a66c-c12a1f284be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;565d6bc3&quot;)</value>
      <webElementGuid>aa45bd5d-6c20-462d-a5bc-a178d69fd501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pega_CreateInsured/Page_PegaCaseManagerPortal/iframe_PegaGadget2Ifr</value>
      <webElementGuid>92a36107-167c-49b2-818c-490a7dca262a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='565d6bc3']</value>
      <webElementGuid>473ed596-632f-4d19-906a-924833887bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='$PpyWorkPage$pApplicationPage$pSelectedQuote$pExpirationDateSpan']/input</value>
      <webElementGuid>d58f0e4b-541e-484e-94fe-2836f6e579f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>865c404d-4b43-458f-9a9e-93896f778ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '565d6bc3' and @name = '$PpyWorkPage$pApplicationPage$pSelectedQuote$pExpirationDate']</value>
      <webElementGuid>1f8f8c2f-60cb-429b-acb3-e666f55ce15b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
