<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_InsuredName</name>
   <tag></tag>
   <elementGuidId>3a4f2c8c-3e15-4489-b95c-ef914f6009b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='Insured Name']/../../following-sibling::div//span//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#96e70369</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Comment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>860dd195-b098-4e4c-b100-92913825f8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2021110114071602632371</value>
      <webElementGuid>6d8c2ed8-cba5-452d-981b-18c2664163e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>54686b8e-41be-4e4c-b13a-0f0015385706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>96e70369</value>
      <webElementGuid>986d5e52-ed59-46e6-b394-318b2e59c00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>122a5517-71c7-4a33-9a4d-a31f3f89d01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PSetProgrammeIDData$pProgramComment</value>
      <webElementGuid>34afe2b0-8b90-4816-92ca-92067f340a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>622bbd9d-9c21-4bfd-bc12-998b989c13c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;ValidateSameMajorClass&quot;, &quot;=&quot;, &quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;,&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;ValidateMultiProgramme&quot;, &quot;=&quot;, &quot;D_GetRelinkingUtilitySubmissions_pa2313497586348685pz.pxResults(1)&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>065eb9b8-f39a-4780-ab88-374e9b263271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8952ef9d-2a29-4574-b3d1-d4a2acc6e443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;96e70369&quot;)</value>
      <webElementGuid>157f5eab-764b-4580-926b-16a5c859f494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget2Ifr</value>
      <webElementGuid>d23dcdc9-5755-43d8-a658-6911e72bcd6b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
