<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownClassType</name>
   <tag></tag>
   <elementGuidId>c582236c-ffbe-4deb-bda7-0b83def481f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'ClassType')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eadeee9e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Class Type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1a63a42e-a62f-41df-98dc-a5ff3a412986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>c941fc55-d93b-40a0-ac55-08511cb22190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201610070553050950186780</value>
      <webElementGuid>5dd79bc3-4df2-4054-9887-2301c4dd08ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>cc69f623-4ec3-4a40-b266-6821cdd07767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eadeee9e</value>
      <webElementGuid>0016f0ae-09f6-40e8-a565-34b6ea087055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pClassType</value>
      <webElementGuid>24f77ea8-8773-454b-a30d-b7bfff11c589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;DefaultMajorClassValue,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTRlZjNhMjU0OWFkZGJhM2NjNWVhMDdlNjcwYjFhMjIxMTJjYmM3ODdlODkwNjc2NGNlMmE0MWY4MTllODVkNjE1MDNlOTliMDU1ZmJlMDU5NjU4MTMwNmMzODZkMWI4OTczNTA1NThjNmZhZGJhZGVjYzg5Y2I3MWMxNzdhMjNlYzJmNGZmMDgwYjU2NDFkYWY4ZTk2YTU0M2QwMTJkNTQ5M2NlN2Q2MDMzNzI4MzdiNmExMDBhZTM3OTNhMDljNmU1NDA1MmRlYzFmY2ZlNzFmN2ZmYmQ4ZmQ4OGMzZTk2ZjlmYTA2MWQ1NTAzYzk0ODI2ZDAyNjIzZWMyOTRkYzM3YWMxYzhiYmZlNmMyMDZmMTNmZDQ5YmU2MDMyMzFkZWVmMWNlYzViNGY3ODNkNjZhY2QxMGMwOTg4ZWVhNjhl*&quot;,{},{&quot;IscalledFrom&quot;:&quot;MajorClass&quot;,&quot;CurrentIndex&quot;:&quot;&quot;}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;ClearClassandMinor,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmI4ZTVhYTJhOTY0NzRlODQ3ZWUxNmRlYmE4OGI2YjY4YTRlZjNhMjU0OWFkZGJhM2NjNWVhMDdlNjcwYjFhMjIxMTJjYmM3ODdlODkwNjc2NGNlMmE0MWY4MTllODVkNjExNjkyOGNhOGEyYWE4MzY0OGU2MDQwMDE5YmE3YzNlMzgyMmExYWRmMWY5YTZkYjhhMzZhZGFkYmU3YzgwYzc1*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;FLSummary&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX04MzA2NGFkMzcxNTE1NDQwOWY0MzBmYTFiYTY1ZmY4NWQxYjAxZWJiMzBmNGZmN2YyNDc4YjAzNjJjMTM4NTRiMzFjMWQ0YzZkYzg3Y2NkYWVlODk3NGNlZmRhZjBiMmJiMTNlMzY1NDlhMzU1Y2NkOTlhZTdiOTQ0MmQ4Y2Q5YQ%3D%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]]]</value>
      <webElementGuid>70f00548-b72e-4479-bd93-9862709c3ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>calculateexpression</value>
      <webElementGuid>871a5a4e-3c8d-4129-82ac-6e0960edbdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Class TypeFinancial LinesKidnap &amp; Ransom</value>
      <webElementGuid>6c3817c7-d8df-490d-8217-c78781c1f275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eadeee9e&quot;)</value>
      <webElementGuid>b941ca94-fae3-479d-9b66-030ead940e10</webElementGuid>
   </webElementProperties>
</WebElementEntity>
