<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DropdownUnderwritingAssistant</name>
   <tag></tag>
   <elementGuidId>ca286165-7ade-477f-a552-a31cae3cf429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'Assistant')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3f490b5e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Underwriting Assistant&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>69324723-a503-48d4-b8c1-178d7820159e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>cbaed3c3-9afe-435e-8ad5-3c9160dcacc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201610070553050950186780</value>
      <webElementGuid>03205cfa-36bb-4523-ba20-5cb01b560898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>69afde49-b5a7-4db7-a827-430e12616491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3f490b5e</value>
      <webElementGuid>ae4edf2c-5133-4a8f-bc75-04bd96650ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pSubmissionData$pAssistant</value>
      <webElementGuid>5136fe05-ad74-455e-b019-47176503fdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iYTA1N2UyMzUyZTQxMmEwZWQ1YmE4ODVlNWYwMzRiODgxNzdjZGVmZDU1OTc4MjYxZjdkMWM1ZTE1OWM2ZTU1ZjgxNjkwNWFlOTA3NTk0YzZjYzgwZDFkOTVlZjc2NTQ4MWU0MTZkYjU1NjVlYmE0Yjg0MTE5YzA1ODQ2ZWU0ODRmMTViODg4OWQwOWY1OTg3OWU2NGUwOGZhOTIwYjg2YWMyZjVkNTg5Y2E0NjVhZTA0ODk2YWY3ZmEzMzE2OGY%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]]]</value>
      <webElementGuid>d7d7d4ba-cff1-4456-a927-7ecb5c8eb369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Underwriting AssistantAna Carolina AguilarAnna WróbelBelinda GostoliCaitlin JohnsCallum HarveyCeri BaileyClara BeauvilainCristina FongElba Bello LarruyEstelle MüllerFrances RadcliffeGemma CastroGethin ThomasIrina Adriana LascuJosep BayonaJosie DaviesKatarzyna LeszekKonstancja PreisnerLibelle VargasLuana NardocciLucia GantestiMariza OliveiraMelesa MartinNadia FranckPukky NaonanRebecca HowellsSandra SimonciniStacey RossTom EllisWilliam HaleyYlenia Biancini</value>
      <webElementGuid>f325a682-b6fa-4094-a6d4-1693ffe67156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3f490b5e&quot;)</value>
      <webElementGuid>eca4174f-a1c9-48fa-8025-44689446ed94</webElementGuid>
   </webElementProperties>
</WebElementEntity>
