<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_BrokerName</name>
   <tag></tag>
   <elementGuidId>8cb051fc-07f2-4307-af16-af6c3e8923cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '${brokerName}' or . = '${brokerName}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.match-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\$PD_BrokerList_pa647299068547797pz\$ppxResults\$l1&quot;] >> internal:text=&quot;Marsh - Barcelona&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f16f05f-e0fe-4989-8351-2de9df8196b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>match-highlight</value>
      <webElementGuid>2a57c02e-ed9b-4e6e-b581-4ce14542adc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marsh - Barcelona</value>
      <webElementGuid>5511877e-91b1-47ae-851e-b10688c3c081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PD_BrokerList_pa647299068547797pz$ppxResults$l1&quot;)/td[@class=&quot;autocompleteAGleft gridCell cellHover&quot;]/div[@class=&quot;oflowDiv&quot;]/div[@class=&quot;divCont&quot;]/div[@class=&quot;cellIn&quot;]/span[1]/span[@class=&quot;match-highlight&quot;]</value>
      <webElementGuid>7d5f27d8-4cb5-4af5-b963-44e5572969b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget2Ifr</value>
      <webElementGuid>29fc79e5-ffc3-4463-b87d-47768b99724c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PD_BrokerList_pa647299068547797pz$ppxResults$l1']/td/div/div/div/span/span</value>
      <webElementGuid>5ebfeec5-fcec-4275-8c2e-fc0c1185e2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddressInfo.AddressLine2'])[1]/following::span[3]</value>
      <webElementGuid>e4fc175d-0d02-49b8-991c-0330427b97a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddressInfo.AddressLine1'])[1]/following::span[4]</value>
      <webElementGuid>a399bf59-681a-4dbb-9a87-bbc225213106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[2]/preceding::span[2]</value>
      <webElementGuid>a52e7210-45b0-45dd-9881-545e5dc07e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barcelona'])[2]/preceding::span[3]</value>
      <webElementGuid>54ef5d03-13f9-4aed-ad6b-f13b97482630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/span/span</value>
      <webElementGuid>d7d2011a-24ad-4d41-968e-fd91a8d9eb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Marsh - Barcelona' or . = 'Marsh - Barcelona')]</value>
      <webElementGuid>e56b1940-3ea1-4b1f-88c9-3ef0b816145d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
