<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__TargetName</name>
   <tag></tag>
   <elementGuidId>55434fd6-79d7-404b-b158-9329e25294c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='44bfe7ae']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#44bfe7ae</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02109140958570310231&quot;] [data-test-id=&quot;\32 014123002323008717229&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0875b8bc-60c2-4ed6-92c9-fda02583fffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runDataTransform&quot;, [&quot;SetNewInsuredSelection&quot;, &quot;=&quot;, &quot;pyWorkPage.NewCustomerInfo.CustomerInfo.TargetDetails&quot;,&quot;:event&quot;],[&quot;&amp;&quot;,[&quot;Act&quot;]]]]</value>
      <webElementGuid>b44e5a0a-e24a-409b-b194-415af33f115a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2014123002323008717229</value>
      <webElementGuid>6cbbbcdd-9ddf-4642-b31e-7847d7c9f0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>f04674d3-9258-4c61-b31d-a64ea33c00f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d6490d4-a019-4483-9411-6c57341762e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>44bfe7ae</value>
      <webElementGuid>a795349f-3b83-4bec-83d3-6831f0232354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>a7374a64-1ca7-4ab1-9251-f0645a68a8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pTargetDetails$pBusinessUnitName</value>
      <webElementGuid>94270d26-443c-46c5-a568-30898ebf6d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>cb7fc2a5-3ea1-42d8-8772-b3528b81dc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PpyWorkPage$pNewCustomerInfo$pCustomerInfo$pTargetDetails$pBusinessUnitNameError</value>
      <webElementGuid>f616efbd-22a6-4263-bb30-67fe56262e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5168b81d-84f4-4fd8-9d06-840dfd433043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>233b31c4-dd88-447a-844b-96a71d8ccd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;44bfe7ae&quot;)</value>
      <webElementGuid>d000635b-467e-4727-9ae7-4ac81a1d4e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>68fb05f1-706a-4280-a99e-c8afdbb0e1dc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
