<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ActionCompletedMessage</name>
   <tag></tag>
   <elementGuidId>ce4d84e6-d481-48dd-b5e1-d11633269293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field-item.dataLabelRead.heading_4_dataLabelRead</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@string_type='label']//div//div[contains(.,'Your action')] | (.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/following::div[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02004271902490394780&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7326eb0-ecc5-4da3-8261-03d55374c469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-item dataLabelRead heading_4_dataLabelRead</value>
      <webElementGuid>5b36c063-1a98-48cb-8843-4e19bab5d56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202004271902490394780</value>
      <webElementGuid>01e92530-3a1e-4bc0-93f5-896e1ec6d519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your action has been completed.</value>
      <webElementGuid>71899198-5e8f-4116-9bb8-7a5b3e17eb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HARNESS_CONTENT&quot;)/div[@class=&quot;workarea-view-scroll-wrapper&quot;]/section[@class=&quot;workarea-view-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-notifications&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-label item-1 remove-top-spacing remove-left-spacing remove-bottom-spacing remove-right-spacing&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataLabelRead heading_4_dataLabelRead&quot;]</value>
      <webElementGuid>f9db03ff-23a0-410d-823d-b5079e7d1b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PartyManagement/Page_UpdateInsured/iframe_PegaGadget1Ifr</value>
      <webElementGuid>fab3c203-c45d-460b-b544-0d61333b6ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/following::div[8]</value>
      <webElementGuid>071c2098-ff29-4e98-b844-f76edb57eed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::div[15]</value>
      <webElementGuid>c9f3b9cb-0e4c-49cc-bd35-8ab07d994d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[1]/preceding::div[20]</value>
      <webElementGuid>8c8d976e-8874-448e-8e8e-7bfed7387033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insured Profile'])[1]/preceding::div[20]</value>
      <webElementGuid>a64d4d7a-03e2-4a1e-aa1b-2884de16c915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your action has been completed.' or . = 'Your action has been completed.')]</value>
      <webElementGuid>b944900d-6d5c-4c0a-a432-a476ace8ddf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/span/div/div/div/div/div/div/div</value>
      <webElementGuid>7a1694ae-d46d-44b8-9b4f-b66f0fcd822c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/div)[3]</value>
      <webElementGuid>e39ab17c-e5b6-417e-8cfe-65a5cf53a63c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
