<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>cd8d1abf-3a2e-4e5b-adf7-079954903f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pzRuleFormToolbarSave_RH_1_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pzRuleFormToolbarSave_RH_1_8&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01805050354190319333&quot;] [data-test-id=&quot;\32 014102117201604205631&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d11f18b-947f-409f-a92c-c0ac2bdb00fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2014102117201604205631</value>
      <webElementGuid>75f05fcf-6d2f-446e-bf72-c75e9ea564b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;setValue&quot;, [[&quot;RH_1.pyToolbarSaveLabel&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;Saving&quot;], [&quot;RH_1.pyRMAction.pyAction&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;save&quot;]]],[&quot;runScript&quot;, [&quot;postPRXML()&quot;]],[&quot;runScript&quot;, [&quot;onBeforeExecuteActionWrapper(\&quot;SAVE\&quot;,\&quot;#~RH_1.pzInsKey~#\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;launchStaleAction(this,event,\&quot;#~RH_1.pzInsKey~#\&quot;,\&quot;#~RH_1.pxUpdateDateTime~#\&quot;,\&quot;save\&quot;,\&quot;#~RH_1.pyIsStaleRuleCheckEnabled~#\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;clearQueueForStaleHandling(\&quot;#~RH_1.pyIsStaleRuleCheckEnabled~#\&quot;)&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;RH_1&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1lYTg2OGI3YTIzYTgxNDgyYTk4MmU3YjkxNzU4ODk5YjRjMDJlYjVkNGNhNjRjMGQ5NTI3Zjc3MWIyMDFlZDc4NzdiMmRiYjVkNTAzNTE0NjgxYWEwOTFjZWI1YjcyNmZiNTIxZGViY2ExNmIwZDQwZjlhZGQxZDg2Y2VjNTlkMmFlYzY2OWNjYTk4ZjZiYTg5MmE4NjlmNWY5ODA4ZWNlOTc5OTkyNDRhMDRlZTU2MWJkNDVjNzZlOWY0ZGYzNmYzNGM5MTY1MDgyOWY5OWIzNjAwMTY4ODNlZDc3NzdiNzBhMzc3M2JiMzNlN2Y5OGM2ZGQ5OWYyYTM4ZmI2YTk0ZmJlYTlmOWNhMDc1NDBjNzViYzU5ZjBiZmE4Y2M3YWM1Y2NkMTc2ODNmZmMyOGEwMzRlYTg2Mzc4OWY2MzM2Nw%3D%3D*&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PRH_1$ppxObjClass&quot;,&quot;=&quot;,&quot;Rule-HTML-Harness&quot;,&quot;false&quot;]]]],[&quot;runScript&quot;, [&quot;postRuleFormValues(\&quot;pzRuleFormToolbarAction\&quot;,\&quot;ToolbarAction=Save\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;clearDirtyFlags(\&quot;\&quot;,\&quot;#~RH_1.pyRuleFormStatus~#\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;pzGetFormBasedXML(\&quot;SAVE\&quot;)&quot;]],[&quot;runScript&quot;, [&quot;clearQueueConditionally(\&quot;#~RH_1.pyRuleFormStatus~#\&quot;,\&quot;#~RH_1.pyRuleFormStatusOld~#\&quot;)&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;RuleFormMain&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;pzSetSaveLabel,&quot;,&quot;:event&quot;,&quot;1&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX1iNzNjNTI1NDU1NzFiZDI4ZTkxMjU2NjlhNDEwNmVkMWRjYzZlNGM5MDAzNDliMWM0NjBiYjIwMDEyYzdjZTUyNTFlNWM3Nzg4OTY1ZTdjMmJiMTI3YWFhOTgzMjlkNjdmYjg2ZjdkMWU4YWJlOGFhZDUyMWI5M2YzZTUxODU4ZTU1MTM4YjlhYjE4NjhlMzFlOGRlZjE5MWNiMjNjYTc4NzA3ODEyZTQ1MGI5MTJjNjlkM2Y5NDFjZDE3MWRjNTE%3D*&quot;,{},{}],&quot;RH_1&quot;]],[&quot;runScript&quot;, [&quot;setDirtyFlag(\&quot;\&quot;,\&quot;#~RH_1.pyRuleFormStatus~#\&quot;)&quot;]],[&quot;runDataTransform&quot;, [&quot;pzRemoveWorkPage&quot;, &quot;=&quot;, &quot;RH_1&quot;,&quot;:event&quot;]]]</value>
      <webElementGuid>ebd08d88-9ba7-4e9b-a067-058641321f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pzRuleFormToolbarSave_RH_1_8</value>
      <webElementGuid>320a9bd6-1232-4a4e-a62e-ff2c3eb54a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>c21eca88-0452-436c-97a3-58996a2c73eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80e99f89-f55d-47d5-956e-35bf3e82b15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save your changes to this record</value>
      <webElementGuid>0a791982-601e-4c51-a278-ddde6cd2c1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>91d0c942-3c54-46c1-a9cc-b2966d48707e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harness-container&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;harnessBodyNoHead&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@class=&quot;noHeadExpandInnerDivStyle&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@class=&quot;noHeadExpandInnerDivStyle&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-ruleform_header&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle auto-width-column flex-grow-1-item-2&quot;]/div[@class=&quot;content-item content-layout item-2 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  flex-dir-row-reverse ruleform-header-actions&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-all-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle  rule-actions nowrap right-aligned&quot;]/div[@class=&quot;content-item content-sub_section item-6 remove-top-spacing remove-bottom-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing set-width-auto flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-inline_middle  content-inline_middle set-width-auto pzRuleFormToolbarSave&quot;]/div[@class=&quot;content-item content-layout item-1 remove-all-spacing flex flex-row&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-split_button  content-split_button&quot;]/div[@class=&quot;content-item content-field item-1 flex flex-row split-left hotkey-ruleform-save dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>6c916d55-881e-421b-bcd8-b6ef68a9614b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NewBusiness/iframe_PegaGadget1Ifr</value>
      <webElementGuid>80f5e047-f4f9-4019-ba81-aeeb8cec5a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pzRuleFormToolbarSave_RH_1_8']</value>
      <webElementGuid>8465d63b-c0bc-4d67-b007-91fb8494f295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/div/div/div/div/div/div/div/span/button)[2]</value>
      <webElementGuid>16c47078-1921-4425-a9a5-d874d18114de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::button[1]</value>
      <webElementGuid>51a7b2cb-2a34-4aa8-a16d-a22601ade19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discard'])[1]/following::button[2]</value>
      <webElementGuid>ced2bdbc-9f2d-4581-954d-b9363d66e511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saving...'])[1]/preceding::button[2]</value>
      <webElementGuid>011eddcd-22a9-41e2-a497-2c8b039154fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit compare'])[1]/preceding::button[5]</value>
      <webElementGuid>82605c86-efb3-44e0-bfa6-b19427e3d435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>05d3add0-8755-47f0-a0b0-5719f18896a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div/div/div/div/div/div/span/button</value>
      <webElementGuid>b41fc132-1726-4921-ab8d-ca9e06121056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pzRuleFormToolbarSave_RH_1_8' and @type = 'button' and @title = 'Save your changes to this record' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>96bd2eb7-484c-4ff5-8a1a-d941b2f75296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
