<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter to sort_oflowDivM</name>
   <tag></tag>
   <elementGuidId>e7bf85cf-8cb1-4f59-9c13-824fbc5c9c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='$PpgRepPgSubSectionpzViewInstancesBBBB$ppxResults$l1']/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oflowDivM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 01704040320550048263-R1&quot;] >> internal:label=&quot;HCC-CL-LL-Work&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f439b34-3f68-47b6-9a5f-2bcb645c5b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oflowDivM </value>
      <webElementGuid>aa05a41b-63f3-4978-88a2-aa73b4e518d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>d7b2f292-b177-430e-b508-8f0ad5c9b619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c6a31d2-22e0-425a-923e-750653683798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>HCC-CL-LL-Work </value>
      <webElementGuid>19a486db-ca73-4e54-9853-a056a41f8216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HCC-CL-LL-Work </value>
      <webElementGuid>fa88ecbe-f2eb-47d3-acde-bd74dbf587cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PpgRepPgSubSectionpzViewInstancesBBBB$ppxResults$l1&quot;)/td[@class=&quot;gridCell    gridCellSelected&quot;]/div[@class=&quot;oflowDivM&quot;]</value>
      <webElementGuid>28e6146f-4f1c-4809-8421-e3598e73d2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RenewalAgent/Page_Pega Dev Studio/Page_Pega Dev Studio/iframe_Security guide not configured_PegaGadget0Ifr</value>
      <webElementGuid>2e34941d-a434-4619-b639-4c4958bdd610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PpgRepPgSubSectionpzViewInstancesBBBB$ppxResults$l1']/td/div</value>
      <webElementGuid>58841313-d7e5-429b-b9d6-b5fad4d55a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[5]/following::div[1]</value>
      <webElementGuid>c27aa23e-9f88-4f8e-918f-9537beb264a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated by'])[1]/following::div[2]</value>
      <webElementGuid>95f5f7bb-f841-450a-90d4-cabc36f81d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RetreiveRenewalPolicies'])[1]/preceding::div[1]</value>
      <webElementGuid>01aa8a1f-0093-40e9-825b-4b24f6a8f5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILITY'])[1]/preceding::div[2]</value>
      <webElementGuid>4bedcc63-00ee-4d22-887f-5fb1e751027d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HCC-CL-LL-Work']/parent::*</value>
      <webElementGuid>10ac0e7a-e643-44cd-97f4-0eab83cb7f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div</value>
      <webElementGuid>c4c787b9-afbe-4fb8-8946-b9b7c59892cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'HCC-CL-LL-Work ' or . = 'HCC-CL-LL-Work ')]</value>
      <webElementGuid>b7ce71c9-f70e-4131-ad05-6ee793f3cc6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
