<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Security guide not configured_PegaGadget0Ifr</name>
   <tag></tag>
   <elementGuidId>84fbc940-c118-419a-9170-9dfecbc719b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='PegaGadget0Ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PegaGadget0Ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;PegaGadget0Ifr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f2eb17ea-bd7b-48c5-b6cb-b65e44a43438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget0Ifr</value>
      <webElementGuid>e75fdbb3-6bd8-4414-9c30-599db9296681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *;</value>
      <webElementGuid>17934173-0c40-48f5-a2f1-5ca19153d1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget0Ifr</value>
      <webElementGuid>8a923398-32ee-45e2-8810-96780d4530fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c8aafff-b67a-4310-b254-56b7dd22b2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a7cf43d8-e8b9-49e7-bd6a-4cb312a28b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a7d70d2-d179-46d2-9a15-33a88c56dfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Activity</value>
      <webElementGuid>e317cfaa-a027-4fe2-bd10-085bc90e5f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget0Ifr&quot;)</value>
      <webElementGuid>dd8b1c1b-5e00-43b2-be84-f4c14c6162de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='PegaGadget0Ifr']</value>
      <webElementGuid>baaee0e2-3974-4805-8a13-540a1d9eb202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PegaWebGadget0']/iframe</value>
      <webElementGuid>85c67c9a-2517-4523-9802-77d7a7338421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>04c6bbf8-72b2-4815-8b42-9f60432ecba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'PegaGadget0Ifr' and @id = 'PegaGadget0Ifr' and @title = 'Activity']</value>
      <webElementGuid>02e87980-9893-46e2-b90e-168a4f83938a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
