<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Resources_PegaGadget1Ifr</name>
   <tag></tag>
   <elementGuidId>37dbf430-ee6a-4190-a62e-bf800d4182d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='PegaGadget1Ifr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PegaGadget1Ifr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;PegaGadget1Ifr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ba4ab3d8-43fe-4042-a5bc-cc46d523512f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
      <webElementGuid>486c6f08-e93e-4fef-ade4-84e4c3f73ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *;</value>
      <webElementGuid>0c803b76-3b61-41c3-a6d8-06ddbd9ff18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget1Ifr</value>
      <webElementGuid>bc5f927b-1229-4892-93b1-e92f55b7a785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5206fb46-7a2a-413b-9b2a-ceb8c3e47b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25f39a68-8327-47e8-9211-0ee1ae7704b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prweb/app/LiabilityLines_/AQrj2LB4NQB7ahNMRtNyrh8oeT_NggknDz3TU5D4xdw*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=openRuleSpecific&amp;openHandle=RULE-OBJ-ACTIVITY%20HCC-CL-LL-WORK%20RETREIVERENEWALPOLICIES%20%2320250226T102722.373%20GMT&amp;Format=harness&amp;contentID=04ade08a-0023-84df-aa66-29d609f201fb&amp;dynamicContainerID=de12ecd7-b2b3-4849-bff1-ee2797014513&amp;tabIndex=3&amp;prevContentID=f8943be6-df6f-1f9e-4677-ffa88b9d2894&amp;prevRecordkey=Activity&amp;portalThreadName=STANDARD&amp;portalName=Developer&amp;eventSrcSection=Embed-ExplorerNode-Ruletype.pzRulesExplorerNode&amp;pzHarnessID=HID621E21B7CCEBE32606BD576ACC94317B</value>
      <webElementGuid>1a819b8b-077e-428a-8179-0ed6ad35d9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>RetreiveRenewalPolicies</value>
      <webElementGuid>754475a2-8126-44c6-961f-15073c83552d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget1Ifr&quot;)</value>
      <webElementGuid>060ae802-795f-4d7b-ae83-329a33bd85a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='PegaGadget1Ifr']</value>
      <webElementGuid>1c8a4ad0-1fd3-45a7-bf0a-95013df7a6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PegaWebGadget1']/iframe</value>
      <webElementGuid>c7479e98-2d17-437f-b1cc-136b20f80863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>1e8ca6de-69b6-42c9-bc2a-2065fe2e6770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'PegaGadget1Ifr' and @id = 'PegaGadget1Ifr' and @src = '/prweb/app/LiabilityLines_/AQrj2LB4NQB7ahNMRtNyrh8oeT_NggknDz3TU5D4xdw*/!TABTHREAD1?pyActivity=%40baseclass.doUIAction&amp;action=openRuleSpecific&amp;openHandle=RULE-OBJ-ACTIVITY%20HCC-CL-LL-WORK%20RETREIVERENEWALPOLICIES%20%2320250226T102722.373%20GMT&amp;Format=harness&amp;contentID=04ade08a-0023-84df-aa66-29d609f201fb&amp;dynamicContainerID=de12ecd7-b2b3-4849-bff1-ee2797014513&amp;tabIndex=3&amp;prevContentID=f8943be6-df6f-1f9e-4677-ffa88b9d2894&amp;prevRecordkey=Activity&amp;portalThreadName=STANDARD&amp;portalName=Developer&amp;eventSrcSection=Embed-ExplorerNode-Ruletype.pzRulesExplorerNode&amp;pzHarnessID=HID621E21B7CCEBE32606BD576ACC94317B' and @title = 'RetreiveRenewalPolicies']</value>
      <webElementGuid>537165af-7b4b-4bf8-ab9a-66d997e64bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
