<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PaginationNext</name>
   <tag></tag>
   <elementGuidId>fc774373-b545-44dc-9f2a-a88b7f5eca4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='>>'])[1]/preceding::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pyGridPaginator_pyDisplayHarness_9&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b2ffc28-d1af-45b6-943e-f17d9d96fc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20141121165713062567558</value>
      <webElementGuid>d0c4260f-38d6-455d-b652-11ea6a57dabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>b3e0eb07-d9f5-4490-9e49-8d7663fc0051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d14a55c5-02e2-4c07-b81d-ab216c1268dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pyGridPaginator_pyDisplayHarness_9</value>
      <webElementGuid>bd9e4b48-13a3-4870-8213-45408f22bb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runScript&quot;, [&quot;doGridAction( event,\&quot;PAGINATE\&quot;,\&quot;\&quot;,\&quot;next\&quot;,\&quot;\&quot;,\&quot;\&quot;,\&quot;true\&quot;)&quot;]]]</value>
      <webElementGuid>2b325b98-ebab-4e75-99c8-3989204e0b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pzhc pzbutton</value>
      <webElementGuid>ce1b4f3e-dc88-4e27-aeac-99867170a388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>11d7662b-437c-43ee-bd00-95e8c92909f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID1&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataLabelWrite gridActionAlignRight&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none float-right set-width-auto&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex  content  set-width-auto layout-content-inline content-inline grid-desktop-paginator nowrap unsized button-noMinWidth flex-align-center&quot;]/div[@class=&quot;content-item content-field item-4 remove-left-spacing   dataValueWrite flex flex-row&quot;]/span[1]/button[@class=&quot;pzhc pzbutton&quot;]</value>
      <webElementGuid>ca2507b7-5664-491c-9efe-2c9ba3a27515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PartyManagement/Page_BrokerSearch/iframe_PegaGadget0Ifr</value>
      <webElementGuid>291d917b-b4ce-4fa4-b4b4-f7f36038beea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
