<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_ArrowIcon</name>
   <tag></tag>
   <elementGuidId>8727cf87-0e9f-4e1e-bf1d-800ad16fbb00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@title='press enter to expand row']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.expandRowDetails</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;press enter to expand row Aon UK Limited AON 1526 The Leadenhall Building 122 Leadenhall Street London EC3V 4AN United Kingdom 44 2070862951 http://www.aon.com True Approved&quot;s] >> internal:attr=[title=&quot;press enter to expand row&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>90a4c46f-02a6-497a-a043-3cba55ec4893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>28e4177f-b107-440f-854a-48dd7dab70c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>expCollIcon</value>
      <webElementGuid>6c2d3a3a-c5aa-462e-9192-65f98e9a3ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;doGridAction&quot;,[&quot;:event&quot;,&quot;EDITITEM&quot;]]]</value>
      <webElementGuid>0d3323d6-dd3e-4ac2-93d1-96c939837e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keyup</name>
      <type>Main</type>
      <value>[[&quot;doGridAction&quot;,[&quot;:event&quot;,&quot;EDITITEM&quot;],null,&quot;enter&quot;]]</value>
      <webElementGuid>5391aa02-3b13-4f1e-a234-d0907c9e443a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expandRowDetails</value>
      <webElementGuid>5ad29679-069f-428b-87fb-a562d283ca19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>press enter to expand row</value>
      <webElementGuid>2661b873-5cc1-49fc-a367-e2d0be248bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>press enter to expand row</value>
      <webElementGuid>b067627d-5a4a-4e37-85fc-9c10d71da655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PD_BrokerList_pa28757253170904pz$ppxResults$l1&quot;)/td[@class=&quot;expandPane    rowHandle oddRow&quot;]/span[@class=&quot;expandRowDetails&quot;]</value>
      <webElementGuid>adec0751-62e7-4c75-8713-1ebfcde13e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PartyManagement/Page_BrokerSearch/iframe_PegaGadget0Ifr</value>
      <webElementGuid>79524f6d-0a85-4214-90cb-8baf8c3dff35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PD_BrokerList_pa28757253170904pz$ppxResults$l1']/td/span</value>
      <webElementGuid>f820bd6c-8e0d-479a-bed9-2bef8f2117bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>5effde01-4f49-4203-b04b-c2bd89249ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'press enter to expand row' and @alt = 'press enter to expand row']</value>
      <webElementGuid>067d6bea-a24f-454b-9a4c-81a2d59e84a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
