<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_Name</name>
   <tag></tag>
   <elementGuidId>3fb0316e-05c3-43fe-aae5-79b1bad9c7a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@data-attribute-name='Name']//div//div//following::div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PEGA_GRID13 > #PEGA_GRID_SKIN > #PEGA_GRID_CONTENT > #gridLayoutTable > tbody > tr > td.mainGridTableCell > #gridBody_right > #bodyTbl_right > tbody > tr.cellCont > #a2 > div.oflowDiv > div.divCont > div.cellIn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Name&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8fad19f-d0c7-4fa2-988d-edd07ac220a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cellIn </value>
      <webElementGuid>91eca8a4-7cde-40e4-9a72-03bd80157c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>a759d354-8d78-4711-96ea-66ec8a6b9824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID13&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;PEGA_GRID_CONTENT&quot;]/table[@id=&quot;gridLayoutTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;mainGridTableCell&quot;]/div[@id=&quot;gridBody_right&quot;]/table[@id=&quot;bodyTbl_right&quot;]/tbody[1]/tr[@class=&quot;cellCont&quot;]/th[@id=&quot;a2&quot;]/div[@class=&quot;oflowDiv&quot;]/div[@class=&quot;divCont&quot;]/div[@class=&quot;cellIn&quot;]</value>
      <webElementGuid>77bfea07-6f0a-428e-a897-a1aea0400447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PartyManagement/Page_BrokerSearch/iframe_PegaGadget0Ifr</value>
      <webElementGuid>6835a842-460d-476f-9905-9d01b78d1553</webElementGuid>
   </webElementProperties>
</WebElementEntity>
