<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ContinueGeneral_pre</name>
   <tag></tag>
   <elementGuidId>aba3cf25-402c-4c73-960c-702795bda71b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name = 'GeneralDetails_pyWorkPage.SubmissionData_196' and @type = 'button' and (text() = 'Continue' or . = 'Continue')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;GeneralDetails_pyWorkPage.SubmissionData_196&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 02106280936320566502&quot;] [data-test-id=&quot;\32 01701181235120120327907&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19735f33-6943-4e3f-b0da-3685e375da06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>201701181235120120327907</value>
      <webElementGuid>6c64e465-c438-42bc-a684-02092dfa1aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runDataTransform&quot;, [&quot;SetFloatingErrFlag&quot;, &quot;=&quot;, &quot;pyWorkPage.SubmissionData&quot;,&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;InvokeCreatePackageFromGenData&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTI2YzVlNTBjMTNkZWVmOTQzN2M1ODgzOTQ5M2Y3YjU0YzU0Y2RhYjUyODc1OGNkZGY2YTE4MjBjZmZmMWNlZmQ0NjQ3MGYxOWVmZWQwZjRjYzkyZDUwMjFlYWNmMDQ4NWNkNDdiZGU1YThhMWZhZWI5MDZmYTNjY2MxMTBlN2I0MzBlMzM4ZGMxMDYwOTRiOGVjMTY0NGUyMGUzOWMyODM3ZTM0ZTE5NDlhNjZjNTBiNTZhZjNlOGY3ZDhjYmY4MGJhMWU4NTU3OTljNzczNWRkOWQ1Zjk4OGNlNGI5MThmODA2ZmZmNWFjN2NlODY1MmU0Y2UzODgxZDNlZTc2*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;pyCaseContentInner&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX01YTI2YzVlNTBjMTNkZWVmOTQzN2M1ODgzOTQ5M2Y3YjU0YzU0Y2RhYjUyODc1OGNkZGY2YTE4MjBjZmZmMWNlZmQ0NjQ3MGYxOWVmZWQwZjRjYzkyZDUwMjFlYWNmMDQ2MzYxOGYzNGM0NzY1NDMwMzgxZWM1YzI4MTE1ZjIzYw%3D%3D*&quot;,{},{}],&quot;pyWorkPage.SubmissionData&quot;]],[&quot;runScript&quot;, [&quot;ContinueEventsConditionally(\&quot;#~pyWorkPage.SubmissionData.ContinueActionEvents~#\&quot;)&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;pyWorkPage.SubmissionData&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFEMX05OTVkYWEzYjVjZDA5NjgyODUwNjYyMTAxYTExOWUyMjU3YTUyZDNiMzdhNzA0MzRiOTE4MjkzZTc1MmJmYzI3OTVlNmRhYzY1ZWM3MGZmYTJlNjhiZjVjZTJiOTc5ODNmZjhiYzRhYTI4MWViYzBjNGZhNjk2YjJmODNjNTU2OWQ1MGNhYzRhN2Q3OGVkMDEzYWMzY2IzZjViZTI2ZTZjYjQzNzAwYTU1NmMzM2MwN2YyOTAwNGRjM2UzZDY5YjU1Zjg1MTU5ZjRhMWQwZDI3MmNmMzYxMDM1YWNmYzEwZTAxMzA2YWM0ZmM3ZGFlOWRlN2U4NDc1ZWNiMWJiYzc2NTkxMDRjOTM1ZTZmMWNjM2QzZWVkNDAxMThlNmJmZmYxMWQyODIwNTg3ZTViOGMxMjA4MGM0OGVmYjZmNjJhMA%3D%3D*&quot;]],[&quot;processAction&quot;, [&quot;DisplayPolicyReference&quot;,&quot;true&quot;,&quot;:event&quot;,&quot;pyWorkPage.SubmissionData&quot;,&quot;Rule-HTML-Section&quot;,&quot;&quot;,&quot;PolicyModalTemplate&quot;,&quot;%7B%22mobile%22%3A%7B%22reveal%22%3A%7B%22effect%22%3A%22anim-null%22%7D%2C%22isCustomDismiss%22%3A%22true%22%2C%22dismiss%22%3A%7B%22effect%22%3A%22anim-null%22%7D%7D%7D&quot;,&quot;true&quot;,&quot;HCC-CL-LL-Data-Submission-Com&quot;,&quot;HCC-CL-LL-Data-Submission-Com&quot;,&quot;false&quot;,&quot;false&quot;,&quot;&quot;,&quot;&quot;]]]</value>
      <webElementGuid>538f14c3-b19c-4c83-addd-740ff65b6bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GeneralDetails_pyWorkPage.SubmissionData_196</value>
      <webElementGuid>e851baf0-69fb-48ff-9c8f-c8bd3de7dcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pzhc pzbutton</value>
      <webElementGuid>aca31061-455c-4073-afcc-fe52f7b525c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6d883b4-e4b6-4c0f-97a8-ee3eefdabad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>46316afe-bdd9-4d97-9efb-825873148a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default  clear-floated-layouts&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-simple_list  content-simple_list&quot;]/div[@class=&quot;content-item content-layout item-1&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle auto-width-column&quot;]/div[@class=&quot;content-item content-layout item-1 remove-bottom-spacing float-right set-width-auto&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;content layout-content-inline_middle  content-inline_middle set-width-auto&quot;]/div[@class=&quot;content-item content-field item-3&quot;]/div[@class=&quot;content-inner&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/span[1]/button[@class=&quot;pzhc pzbutton&quot;]</value>
      <webElementGuid>09a00311-543c-4b78-88c2-4587e80e1f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OutwardsPolicy/iframe_PegaGadget1Ifr</value>
      <webElementGuid>8de4e88d-dba4-458f-b2a8-b95d8a04c47a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='GeneralDetails_pyWorkPage.SubmissionData_196']</value>
      <webElementGuid>4859a759-a934-4f4a-b1cd-d170197c1763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::button[1]</value>
      <webElementGuid>61700625-b29e-4a49-8a57-0ec5c80f3d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Quote?'])[1]/following::button[2]</value>
      <webElementGuid>827c500d-4ed6-4409-a2ea-bbeee3c4c4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='▼'])[1]/preceding::button[1]</value>
      <webElementGuid>ab2d2cef-096c-4ccf-8a99-4f78205014de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::button[1]</value>
      <webElementGuid>4ff19bc6-d96a-40b9-b795-a152b1c1dc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>2f293d4f-88c1-4a55-8679-7b150483e648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'GeneralDetails_pyWorkPage.SubmissionData_196' and @type = 'button' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>014824dd-4044-4541-93ea-b75f7970d763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/button</value>
      <webElementGuid>be9fd5e2-e8f4-4c51-af80-563da57e851b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/span/button</value>
      <webElementGuid>a7f76896-2bea-4512-87fa-bc8ff03da439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
