<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_PegaGadget2Ifr</name>
   <tag></tag>
   <elementGuidId>cf6e00c2-c77a-4327-a6b6-b52746c993de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PegaGadget2Ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='PegaGadget2Ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;PegaGadget2Ifr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2d87882c-fcb4-4dba-aed0-3c142bfa2772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
      <webElementGuid>e35ad46e-9c8f-489c-85a0-5763937dff11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *;</value>
      <webElementGuid>9fbdb499-1cbd-4cba-9c84-dd3a9229ec89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PegaGadget2Ifr</value>
      <webElementGuid>80dfe49e-ab48-4b09-944d-00c928974f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1eeef31e-1a83-4fa1-a2a1-c3e40722255f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>35a9b8ae-38e0-4afd-9a77-7e0025488833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/prweb/app/LiabilityLines_/AQrj2LB4NQCKaV10lflPLOnOAP4olJWCG1vcOaRKU9iAwaE8P9peJQ*/!TABTHREAD2?pyActivity=%40baseclass.doUIAction&amp;action=createNewWork&amp;className=HCC-CL-LL-Work-Submission-FL&amp;flowName=pyStartCase&amp;dynamicContainerID=f9e64470-c4fa-4e63-b814-0a50f75d0647&amp;contentID=b439bd93-74c0-e170-d1f9-cc85056c4489&amp;tabIndex=3&amp;prevContentID=c07cd4b3-c5cd-c000-f81c-dd4c2fcfa7a4&amp;prevRecordkey=2T&amp;portalThreadName=STANDARD&amp;portalName=pyCaseManager7&amp;pzHarnessID=HIDDBCFAE7F947B812F65F135AA122D5A5E</value>
      <webElementGuid>b7879d08-f67b-4265-a876-5f8fd4f9633e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>16d9b124-ca3c-4e0c-be10-1d30e3122536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PegaGadget2Ifr&quot;)</value>
      <webElementGuid>1a886719-11f7-4a79-8ce6-03a3988cf9b6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
