<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_FacilitiesDropDown</name>
   <tag></tag>
   <elementGuidId>2730f78e-9b99-4e2c-8e4d-3242152d990e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a05b5af9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[contains(@data-attribute-name,'Facilities')]//div//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;\32 021083008215404551-R1&quot;] [data-test-id=&quot;\32 016051308324401031007191&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cb70542d-07a0-4212-8600-e1385bbd6809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>c07be695-cfcb-465a-a480-2fe2a11d4a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2016051308324401031007191</value>
      <webElementGuid>1eac8d93-1978-44bd-b262-88f63f7cde93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>standard</value>
      <webElementGuid>ab5f8e39-1ce4-498e-9b4d-84432689287b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a05b5af9</value>
      <webElementGuid>83cd61f3-5ddc-48b4-9690-db07396b1391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyWorkPage$pFacilityList$l1$pFacilities</value>
      <webElementGuid>f6cca4c5-7c4f-4971-bf76-c587f2dd3bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;FacRiWarningmsgfFlagDetailsFacil,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17VEFCVEhSRUFENH1mMjk1MjcyZmI4MjI3ZWRjNGM3ZTAxYTcyYmIwOGNmNWNlN2VkN2ViMzZlMWZkMDE0ZDI2ZTE0N2MzZTg0Mjk4MzhjY2JhMjJjZWMyMTY0YzllNmFkYzQ3Zjc0Yzg1ZDI2MTliZGM4Y2JjNTUwNjJkY2U4YTg5YWZhNGZkOWQxOTM1NjBkMGUwN2VkYzIzZTI1NmZmYzczYWM0MmJmNmRkNjc1ZjMzNGQwZTg5NGZjYzYzZWI1ZDZiYTE5NWY2Y2RmZDZjZjAxMmQ1OTkxOTRjYWZlMzg1MzY2NmUzNTVjNWIyYTlmN2E4YWI4M2YyZmNjN2ZmNTM5MTFiODQ4MmJhZTg2MzIxMTYwMzEzYTFjNmJkODAwNGJkMGQ4OTRkMTQ%3D*&quot;,{},{}],&quot;&quot;]]]</value>
      <webElementGuid>36419d1f-3a81-43d8-b7f2-9190d77e191a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...16/HCCG/MUNICH16/HCCG/TRI17/DAM/QS17/HCCG/MUNICH17/HCCG/TRI17/USDAMP/QS18/DAM/QS18/HCCG/MUNICH18/HCCG/TRI18/MUNK&amp;R/QS18/USDAMP/QS19/DAMTME/QS19/MUNK&amp;R/QS19/USDAMP/QS19CYBNJ20/DAM/QS20/HCCG/MUNICH20/HCCG/SWISS20/HCCG/TRIMUNICH20/HCCG/TRISWISS20/MUNK&amp;R/QS20/USDAMP/QS20CYBNJ21/DAM/QS21/HCCG/MUNICH21/HCCG/SWISS21/HCCG/TRIMUNICH21/HCCG/TRISWISS21/MUNK&amp;R/QS21/SAFETYNAT/QS/FL21/USDAMP/QS21CYBNJ22/DAM/QS22/HCCG/MUNICH22/HCCG/SWISS22/HCCG/TRIMUNICH22/HCCG/TRISWISS22/MUNK&amp;R/QS22/SAFETYNAT/QS/FL22/USDAMP/QS22CYBNJ23/DAMPJTAYKL/QS23/DAMTME/QS23/HCCG/MUNICH23/HCCG/SWISS23/HCCG/TRIMUNICH23/HCCG/TRISWISS23/MUNK&amp;R/QS23/SAFETYNAT/QS/FL23/USDAMP/QS23CYBNJ24/DAMTME/QS24/HCCG/EV/CYBER24/HCCG/EV/DOPI24/HCCG/MUNICH24/HCCG/SWISS24/HCCG/TRIMUNICH24/HCCG/TRISWISS24/IRIS/TMNF24/MUNK&amp;R/QS24/PROJECTDELTA24/SAFETYNAT/QS/FL24/USDAMP/QS/FL24CYBNJ24DAMPJTAYFL25/DAMTME/QS25/HCCG/EV/CYBER25/HCCG/EV/DOPI25/HCCG/SWISS25/HCCG/TRIMUNICH25/HCCG/TRISWISS25/IRIS/TMNF25/MUNK&amp;R/QS25/SAFETYNAT/QS/FL25/USDAMP/QS/FL25CYBNJ25DAMPJTAYFLNone</value>
      <webElementGuid>1ff2a4f6-5a02-4753-880f-a4e26b4151e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a05b5af9&quot;)</value>
      <webElementGuid>39b599ce-14c1-4638-a057-5ac219c375d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OutwardsPolicy/iframe_PegaGadget2Ifr</value>
      <webElementGuid>50ede71a-72be-462b-accf-5a7421da7430</webElementGuid>
   </webElementProperties>
</WebElementEntity>
