<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>webElement_CopySubmissionText</name>
   <tag></tag>
   <elementGuidId>c465976e-195b-41e7-874c-19b843a31fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '        Copy Submission       ' or . = '        Copy Submission       ')] | //h2[text()='        Copy Submission       ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modaldialog_hd_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modaldialog_hd_title</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d98d332-ee2a-4347-9a4f-c9ed2cfaf809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modaldialog_hd_title</value>
      <webElementGuid>e7cf1b28-77a5-43d1-84fa-0927217927a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        Copy Submission       </value>
      <webElementGuid>e855d78f-b173-4bf4-be37-036cd9774252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modaldialog_hd_title&quot;)</value>
      <webElementGuid>cc686dc1-2391-443d-9ea8-18a3c87a714f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboards/iframe_PegaGadget1Ifr</value>
      <webElementGuid>4f257dd4-318b-4018-a058-d9a697f1383c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
